## Sustainability Rating + Exposición + Controversia + Estrategias
### Chequeos descarga SNT-WORLD Aladdin vs DF con overwrites

In [1]:
## DF
#Librerías
import numpy as np
import pandas as pd
import pandas
print(pandas.__version__)

1.4.2

In [2]:
!python --version

Python 3.9.12

In [3]:
pd.__version__

'1.4.2'

In [4]:
#Read descarga de Aladdin (Workspace "Descarga_incumplimientos")
file_path= 'C:/Users/n629352/Downloads/Risk and exposure - 2023-10-19T143603.392.xlsx'
Aladdin =pd.read_excel(file_path, sheet_name =None, skiprows=4)

C:\Program Files\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [5]:
Aladdin= pd.concat(Aladdin.values(), ignore_index=True)
Aladdin.info()
Aladdin.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75057 entries, 0 to 75056
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SNT-WORLD    75056 non-null  object
 1   SNT-WORLD.1  75054 non-null  object
 2   1.0          75054 non-null  float64
 3   Unnamed: 3   60250 non-null  object
 4   Unnamed: 4   75054 non-null  object
 5   Unnamed: 5   30619 non-null  object
 6   Unnamed: 6   30619 non-null  object
 7   Unnamed: 7   30619 non-null  object
 8   Unnamed: 8   28184 non-null  object
 9   Unnamed: 9   30674 non-null  object
 10  Unnamed: 10  30538 non-null  object
 11  Unnamed: 11  30538 non-null  object
 12  Unnamed: 12  30538 non-null  object
 13  Unnamed: 13  30555 non-null  object
 14  Unnamed: 14  30538 non-null  object
 15  Unnamed: 15  30555 non-null  object
 16  Unnamed: 16  29375 non-null  object
dtypes: float64(1), object(16)
memory usage: 9.7+ MB

,SNT-WORLD,SNT-WORLD.1,1.0,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLSFIO0519,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
1,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLSFIO0085,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
2,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLFIO00337,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
3,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLFIO00003,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
4,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLFIO00004,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok

In [6]:
#Read DF con overwrites
DF_OVR=pd.read_csv('X:/INVDESPRO/INVESTIGACION/Fondos éticos/3. DATASETS/04_Datos Clarity/01_Equities_feed/DF_para_python/202310_DF_Octubre.csv', sep=';', dtype='unicode')

In [7]:
#CROSS REFERENCE 
CROSS_REFERENCE=pd.read_excel('X:/INVDESPRO/INVESTIGACION/Fondos éticos/3. DATASETS/03_Cross Reference/20231001_Aladdin_Clarity_Issuers.xlsx')

In [8]:
#Pasar el 'permId' y 'ClarityID' a int
DF_OVR[['permId','ClarityID']] = DF_OVR[['permId', 'ClarityID']].astype('int64')
DF_OVR[['permId', 'ClarityID']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313453 entries, 0 to 1313452
Data columns (total 2 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   permId     1313453 non-null  int64
 1   ClarityID  1313453 non-null  int64
dtypes: int64(2)
memory usage: 20.0 MB

In [9]:
#DF_OVR= DF_OVR.drop_duplicates(subset='permId')

In [10]:
#Filtrar el DF solo la columna que necesito
DF_OVR_filtered = DF_OVR[['permId','ClarityID','issuer_name','str_001_s','str_002_ec','str_003_ec','str_004_asec','str_005_ec','str_006_sec','str_007_sect','cs_001_sec','cs_002_ec','cs_003_sec','art_8_basicos','gp_esccp_22','str_003b_ec']]
DF_OVR_filtered.head()

,permId,ClarityID,issuer_name,str_001_s,str_002_ec,str_003_ec,str_004_asec,str_005_ec,str_006_sec,str_007_sect,cs_001_sec,cs_002_ec,cs_003_sec,art_8_basicos,gp_esccp_22,str_003b_ec
0,4296063555,90284,Banque Federative du Credit Mutuel SA,OK,OK,OK,EXCLUDED,OK,OK,EXCLUDED,EXCLUDED,OK,EXCLUDED,OK,OK,OK
1,4295862902,47977,Toronto-Dominion Bank,OK,EXCLUDED,OK,OK,EXCLUDED,OK,OK,OK,OK,OK,OK,OK,OK
2,4296537659,60596,RCI Banque SA,OK,OK,OK,OK,OK,OK,OK,OK,OK,EXCLUDED,OK,OK,OK
3,5000727906,159387980,CPPIB Capital Inc,EXCLUDED,OK,OK,EXCLUDED,OK,EXCLUDED,EXCLUDED,EXCLUDED,EXCLUDED,EXCLUDED,OK,OK,OK
4,4295875735,26931,Intesa Sanpaolo SpA,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK

In [11]:
DF_OVR_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313453 entries, 0 to 1313452
Data columns (total 16 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   permId         1313453 non-null  int64
 1   ClarityID      1313453 non-null  int64
 2   issuer_name    1313453 non-null  object
 3   str_001_s      1313453 non-null  object
 4   str_002_ec     1313453 non-null  object
 5   str_003_ec     1313453 non-null  object
 6   str_004_asec   1313453 non-null  object
 7   str_005_ec     1313453 non-null  object
 8   str_006_sec    1313453 non-null  object
 9   str_007_sect   1313453 non-null  object
 10  cs_001_sec     1313453 non-null  object
 11  cs_002_ec      1313453 non-null  object
 12  cs_003_sec     1313453 non-null  object
 13  art_8_basicos  1313453 non-null  object
 14  gp_esccp_22    1313453 non-null  object
 15  str_003b_ec    1313453 non-null  object
dtypes: int64(2), object(14)
memory usage: 160.3+ MB

### CROSS_REFERENCE

In [12]:
#CROSS REFERENCE 
CROSS_REFERENCE.info()  #SI ESTA EN Float64 cambiar a Int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112963 entries, 0 to 112962
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Aladdin_Issuer  112963 non-null  object
 1   Issuer_Name     112963 non-null  object
 2   CLARITY_AI      112963 non-null  int64
dtypes: int64(1), object(2)
memory usage: 2.6+ MB

In [13]:
CROSS_REFERENCE.head()

  Aladdin_Issuer                      Issuer_Name  CLARITY_AI
0         000176      AMERICAN AIRLINES GROUP INC  4295903254
1         000375                           BP PLC  4295894740
2         00038A                          ABB LTD  4295890743
3         00077B               NATWEST MARKETS NV  4296540158
4         00138E  AIG MATCHED FUNDING CORPORATION  4296435746

In [14]:
#CROSS_REFERENCE_before['CLARITY_AI'] = CROSS_REFERENCE_before['CLARITY_AI'].astype('float')
CROSS_REFERENCE['CLARITY_AI'] = pd.to_numeric(CROSS_REFERENCE['CLARITY_AI'], errors='coerce')
CROSS_REFERENCE['CLARITY_AI'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 112963 entries, 0 to 112962
Series name: CLARITY_AI
Non-Null Count   Dtype
--------------   -----
112963 non-null  int64
dtypes: int64(1)
memory usage: 882.6 KB

In [15]:
CROSS_REFERENCE['CLARITY_AI'] = CROSS_REFERENCE['CLARITY_AI'].round().astype('Int64')
CROSS_REFERENCE['CLARITY_AI'].head()

0    4295903254
1    4295894740
2    4295890743
3    4296540158
4    4296435746
Name: CLARITY_AI, dtype: Int64

In [16]:
CROSS_REFERENCE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112963 entries, 0 to 112962
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Aladdin_Issuer  112963 non-null  object
 1   Issuer_Name     112963 non-null  object
 2   CLARITY_AI      112963 non-null  Int64
dtypes: Int64(1), object(2)
memory usage: 2.7+ MB

In [17]:
CROSS_REFERENCE.head()

  Aladdin_Issuer                      Issuer_Name  CLARITY_AI
0         000176      AMERICAN AIRLINES GROUP INC  4295903254
1         000375                           BP PLC  4295894740
2         00038A                          ABB LTD  4295890743
3         00077B               NATWEST MARKETS NV  4296540158
4         00138E  AIG MATCHED FUNDING CORPORATION  4296435746

## Aladdin

In [32]:
Aladdin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75057 entries, 0 to 75056
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SNT-WORLD    75056 non-null  object
 1   SNT-WORLD.1  75054 non-null  object
 2   1.0          75054 non-null  float64
 3   Unnamed: 3   60250 non-null  object
 4   Unnamed: 4   75054 non-null  object
 5   Unnamed: 5   30619 non-null  object
 6   Unnamed: 6   30619 non-null  object
 7   Unnamed: 7   30619 non-null  object
 8   Unnamed: 8   28184 non-null  object
 9   Unnamed: 9   30674 non-null  object
 10  Unnamed: 10  30538 non-null  object
 11  Unnamed: 11  30538 non-null  object
 12  Unnamed: 12  30538 non-null  object
 13  Unnamed: 13  30555 non-null  object
 14  Unnamed: 14  30538 non-null  object
 15  Unnamed: 15  30555 non-null  object
 16  Unnamed: 16  29375 non-null  object
dtypes: float64(1), object(16)
memory usage: 9.7+ MB

In [33]:
Aladdin.head()

,SNT-WORLD,SNT-WORLD.1,1.0,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLSFIO0519,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
1,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLSFIO0085,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
2,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLFIO00337,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
3,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLFIO00003,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
4,11 BIT STUDIOS SA,SNT-WORLD,0.0,F79892,PLFIO00004,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok

In [34]:
Aladdin_filtered=Aladdin.iloc[:,[0,3,4,5,6,7,8,9,10,11,12,13,14,15,16]]
Aladdin_filtered.columns = ['IssuerName', 'IssuerID','Portfolio','STR001','STR002','STR003','STR003B','STR004','STR005','STR006','STR007','CS001','CS002','CS003','SFDR_ART8']
Aladdin_filtered.info()
Aladdin_filtered.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75057 entries, 0 to 75056
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IssuerName  75056 non-null  object
 1   IssuerID    60250 non-null  object
 2   Portfolio   75054 non-null  object
 3   STR001      30619 non-null  object
 4   STR002      30619 non-null  object
 5   STR003      30619 non-null  object
 6   STR003B     28184 non-null  object
 7   STR004      30674 non-null  object
 8   STR005      30538 non-null  object
 9   STR006      30538 non-null  object
 10  STR007      30538 non-null  object
 11  CS001       30555 non-null  object
 12  CS002       30538 non-null  object
 13  CS003       30555 non-null  object
 14  SFDR_ART8   29375 non-null  object
dtypes: object(15)
memory usage: 8.6+ MB

,IssuerName,IssuerID,Portfolio,STR001,STR002,STR003,STR003B,STR004,STR005,STR006,STR007,CS001,CS002,CS003,SFDR_ART8
0,11 BIT STUDIOS SA,F79892,PLSFIO0519,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
1,11 BIT STUDIOS SA,F79892,PLSFIO0085,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
2,11 BIT STUDIOS SA,F79892,PLFIO00337,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
3,11 BIT STUDIOS SA,F79892,PLFIO00003,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok
4,11 BIT STUDIOS SA,F79892,PLFIO00004,Ok,Ok,Ok,Ok,Excluded,OK,Excluded,Excluded,Excluded,OK,Excluded,Ok

In [35]:
rows_to_drop = Aladdin_filtered[Aladdin_filtered['IssuerID'].isna()].index
Aladdin_filtered = Aladdin_filtered.drop(rows_to_drop)
Aladdin_filtered = Aladdin_filtered.drop(Aladdin_filtered[Aladdin_filtered['IssuerID'].isna()].index)
Aladdin_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60250 entries, 0 to 75053
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IssuerName  60250 non-null  object
 1   IssuerID    60250 non-null  object
 2   Portfolio   60250 non-null  object
 3   STR001      30619 non-null  object
 4   STR002      30619 non-null  object
 5   STR003      30619 non-null  object
 6   STR003B     28184 non-null  object
 7   STR004      30674 non-null  object
 8   STR005      30538 non-null  object
 9   STR006      30538 non-null  object
 10  STR007      30538 non-null  object
 11  CS001       30555 non-null  object
 12  CS002       30538 non-null  object
 13  CS003       30555 non-null  object
 14  SFDR_ART8   29375 non-null  object
dtypes: object(15)
memory usage: 7.4+ MB

In [36]:
# Lista de nombres para filtrar
#Filtrar por portfolio de las estrategías
#STR001	STR002	STR003	STR004	STR004 SB	STR005	STR006	STR007	CS001	CS002	CS003	ART8

lista_nombres = ['CL19778','CMD07211','CMD07212','CMD07213','CMD07214','CMD07215','CMD08211','CMD08212','CMD08213','CMD08214',
'CMD08215','CPE00035','CPE00169','CPE00264','CPE00277','CPE00363','CPE00375','CPE00448','CPE00456','CPE00464','CPE03002',
'CPE03290','CPE03519','CPE03570','CPE03744','CPE03853','CPE03861','CPE03867','CPE03912','CPE03913','CPE03928','CPE03986',
'CPE04024','CPE04036','CPE04037','CPE04039','CPE04041','CPE04044','CPE04053','CPE04059','CPE04063','CPE04070','CPE04071',
'CPE04075','CPE04076','CPE04077','CPE04080','CPE04081','CPE04082','CPE04084','CPE04087','CPE05134','CPE05137','CPE05148',
'CPE05150','CPE05151','CPE05152','CPE05162','CPE05174','CPE05177','CPE05180','CPE05189','CPE05190','CPE05191','CPE05192',
'CPE05207','CPE05208','CPE05211','CPE05212','CPE05218','CPE05219','CPE05226','CPE05234','CPE05239','CPE05242','CPE05244',
'CPE05245','CPE05248','CPE05252','CPE05258','CPE05261','CPE05314','CPE05315','CPE05317','CPE05318','CPE05337','CPE05340',
'CPE05341','CPE05344','CPE05351','CPE05355','CPE05361','CPE05362','CPE05363','CPE05366','EPH00107','EPV00005','EPV00043',
'EPV00050','EPV00051','EPV00052','EPV00060','EPV00061','EPV00062','EPV00063','EPV00064','EPV14004','EPV14005','EPV14006',
'FIF00154','FIF04284','FIF04285','FIG00026','FIG00677','FIG00689','FIG01973','FIG01988','FIG02164','FIG02410','FIG02787',
'FIG04251','FIG04253','FIG04868','FIG05178','FIG05198','FIG05240','FIG05241','FIG05273','FIG05402','FIG05415','FIG05428',
'FIG05698','FIH00058','FIH00208','FIH00529','FIH01197','FIH01920','FIN00315','FIN00441','FIN00637','FPB01158','FPG00002',
'FPG00015','FPG00026','FPG00027','FPG00028','FPG00112','FPG00555','FPG00603','FPG00687','FPG01066','FPG01072','FPG01079',
'FPG01213','FPG01214','FPG01278','FPG01421','FPG01697','FPH00254','FPH00457','LXMS0020','LXMS0040','LXMS0240','LXMS0340',
'LXMS0350','LXMS0360','LXMS0520','LXMS0530','LXMS0540','LXMS0550','LXMS0560','LXMS0570','LXMS0630','LXMS0650','LXMS0660',
'LXMS0720','PFI01541','PFI01549','PFIT0011','PFIT0042','PFIT0516','PFIT0605','PFIT0647','PFIT1421','PFIT1422','PFIT1423',
'PFIT1424','PFIT1425','PFIT1426','PFIT1830','PFS00001','PFS00002','PFS00058','PFS00059','PFS00358','PFS00359','PFS00360',
'PFS00365','PFS00366','PFS00371','PFSULM01','PFSULM02','PFSULM03','PFSULM04','PFSULM05']

# Filtrar por la lista de nombres
Aladdin_filtered2 = Aladdin_filtered[Aladdin_filtered['Portfolio'].isin(lista_nombres)].copy()

# Mostrar el nuevo DataFrame Carteras__before_2
print(Aladdin_filtered2)

                      IssuerName IssuerID Portfolio STR001 STR002 STR003  \
22               2I RETE GAS SPA   G70839  PFIT0605     Ok     Ok     Ok
24               2I RETE GAS SPA   G70839  PFS00059     Ok     Ok     Ok
70        A1 TOWERS HOLDING GMBH   L58476  PFS00059    NaN    NaN    NaN
73        A1 TOWERS HOLDING GMBH   L58476  LXMS0020    NaN    NaN    NaN
76        A1 TOWERS HOLDING GMBH   L58476  PFIT0605    NaN    NaN    NaN
...                          ...      ...       ...    ...    ...    ...
75049  ZURICH INSURANCE GROUP AG   B00344  FPG00027     Ok     Ok     Ok
75050  ZURICH INSURANCE GROUP AG   B00344  EPV00060     Ok     Ok     Ok
75051  ZURICH INSURANCE GROUP AG   B00344  FPG01214     Ok     Ok     Ok
75052  ZURICH INSURANCE GROUP AG   B00344  FPG01213     Ok     Ok     Ok
75053  ZURICH INSURANCE GROUP AG   B00344  LXMS0040     Ok     Ok     Ok

      STR003B    STR004 STR005 STR006    STR007     CS001 CS002     CS003  \
22         Ok  Excluded     OK     OK  Excluded  Excluded    OK  Excluded
24         Ok  Excluded     OK     OK  Excluded  Excluded    OK  Excluded
70        NaN       NaN    NaN    NaN       NaN       NaN   NaN       NaN
73        NaN       NaN    NaN    NaN       NaN       NaN   NaN       NaN
76        NaN       NaN    NaN    NaN       NaN       NaN   NaN       NaN
...       ...       ...    ...    ...       ...       ...   ...       ...
75049      Ok        Ok     OK     OK        OK        OK    OK        OK
75050      Ok        Ok     OK     OK        OK        OK    OK        OK
75051      Ok        Ok     OK     OK        OK        OK    OK        OK
75052      Ok        Ok     OK     OK        OK        OK    OK        OK
75053      Ok        Ok     OK     OK        OK        OK    OK        OK

      SFDR_ART8
22           Ok
24           Ok
70          NaN
73          NaN
76          NaN
...         ...
75049        Ok
75050        Ok
75051        Ok
75052        Ok
75053        Ok

[12871 rows x 15 columns]

In [37]:
Aladdin_filtered2.info()
Aladdin_filtered2.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12871 entries, 22 to 75053
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IssuerName  12871 non-null  object
 1   IssuerID    12871 non-null  object
 2   Portfolio   12871 non-null  object
 3   STR001      8359 non-null   object
 4   STR002      8359 non-null   object
 5   STR003      8359 non-null   object
 6   STR003B     7117 non-null   object
 7   STR004      8384 non-null   object
 8   STR005      8355 non-null   object
 9   STR006      8355 non-null   object
 10  STR007      8355 non-null   object
 11  CS001       8359 non-null   object
 12  CS002       8355 non-null   object
 13  CS003       8359 non-null   object
 14  SFDR_ART8   7724 non-null   object
dtypes: object(15)
memory usage: 1.6+ MB

,IssuerName,IssuerID,Portfolio,STR001,STR002,STR003,STR003B,STR004,STR005,STR006,STR007,CS001,CS002,CS003,SFDR_ART8
22,2I RETE GAS SPA,G70839,PFIT0605,Ok,Ok,Ok,Ok,Excluded,OK,OK,Excluded,Excluded,OK,Excluded,Ok
24,2I RETE GAS SPA,G70839,PFS00059,Ok,Ok,Ok,Ok,Excluded,OK,OK,Excluded,Excluded,OK,Excluded,Ok
70,A1 TOWERS HOLDING GMBH,L58476,PFS00059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,A1 TOWERS HOLDING GMBH,L58476,LXMS0020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,A1 TOWERS HOLDING GMBH,L58476,PFIT0605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Cross Reference

**"CROSS REFERENCE"=    `IssuerID`  == "CARTERAS" = `IssuerID`**

In [47]:
CROSS_REFERENCE_filtered = CROSS_REFERENCE.loc[CROSS_REFERENCE_after['Aladdin_Issuer'].isin(Aladdin_filtered2['IssuerID'])]

In [48]:
CROSS_REFERENCE_filtered.info()
CROSS_REFERENCE_filtered.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 773 entries, 5 to 112789
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Aladdin_Issuer  773 non-null    object
 1   Issuer_Name     773 non-null    object
 2   CLARITY_AI      773 non-null    Int64
dtypes: Int64(1), object(2)
memory usage: 24.9+ KB

,Aladdin_Issuer,Issuer_Name,CLARITY_AI
5,001625,NETHERLANDS (KINGDOM OF),4297544384
9,002824,ABBOTT LABORATORIES,4295903265
10,003001,AB SKF,4295890078
11,005560,EUROPEAN BANK FOR RECONSTRUCTION AND DEVELOPMENT,8589934160
12,007699,BANCO SANTANDER SA,8589934205

In [49]:
CROSS_REFERENCE_before_filtered = CROSS_REFERENCE_before.loc[CROSS_REFERENCE_before['Aladdin_Issuer'].isin(Carteras_before_2['Issuer ID'])]

In [50]:
CROSS_REFERENCE_before_filtered.info()
CROSS_REFERENCE_before_filtered.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 773 entries, 5 to 112789
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Aladdin_Issuer  773 non-null    object
 1   Issuer_Name     773 non-null    object
 2   CLARITY_AI      773 non-null    Int64
dtypes: Int64(1), object(2)
memory usage: 24.9+ KB

,Aladdin_Issuer,Issuer_Name,CLARITY_AI
5,001625,NETHERLANDS (KINGDOM OF),4297544384
9,002824,ABBOTT LABORATORIES,4295903265
10,003001,AB SKF,4295890078
11,005560,EUROPEAN BANK FOR RECONSTRUCTION AND DEVELOPMENT,8589934160
12,007699,BANCO SANTANDER SA,8589934205

In [51]:
DF_before_filtered = DF_before.loc[DF_before['permId'].isin(CROSS_REFERENCE_before_filtered['CLARITY_AI'])]

In [52]:
DF_before_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 32 to 1246761
Columns: 255 entries, isin to str_003b_ec
dtypes: int64(2), object(253)
memory usage: 1.3+ MB

In [53]:
DF_before_filtered.head()

,isin,instrument_type,issuer_name,issuer_country,gics2_industry,region,company_inheriting,parent_company,esg_score,esg_score_relevance,...,cs_002_ec,str_006_sec,str_007_sect,gp_esccp_22,gp_esccp_25,gp_esccp_30,art_8_basicos,permId,countryCode,str_003b_ec
32,XS0072700114,FIXED_INCOME,International Bank for Reconstruction and Deve...,United States of America,Financial Services,N America,False,-,57,79.53000000000003,...,OK,OK,OK,OK,OK,OK,OK,8589934570,US,OK
159,XS0744716928,FIXED_INCOME,Cooperatieve Rabobank UA,Netherlands,Banks,Europe,False,-,47,81.25,...,OK,OK,EXCLUDED,OK,OK,OK,OK,4298009762,NL,OK
2092,US37045XDQ60,FIXED_INCOME,General Motors Financial Company Inc,United States of America,Financial Services,N America,False,-,33,64.45000000000003,...,OK,EXCLUDED,EXCLUDED,OK,OK,OK,OK,4295903360,US,OK
2114,US86562LGM81,FIXED_INCOME,Sumitomo Mitsui Banking Corp,Japan,Banks,Asia Pacific,True,Sumitomo Mitsui Financial Group Inc,47,84.74,...,OK,OK,OK,OK,OK,OK,OK,5000001007,JP,OK
2145,XS0029197299,FIXED_INCOME,European Investment Bank,Luxembourg,Banks,Europe,False,-,67,77.41,...,OK,OK,OK,OK,OK,OK,OK,8589934159,LU,OK

In [54]:
DF_before_filtered= DF_before_filtered.drop_duplicates(subset='ClarityID')
DF_before_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 32 to 1246761
Columns: 255 entries, isin to str_003b_ec
dtypes: int64(2), object(253)
memory usage: 1.3+ MB

In [55]:
DF_after_filtered = DF_after.loc[DF_after['permId'].isin(CROSS_REFERENCE_after_filtered['CLARITY_AI'])]

In [56]:
DF_after_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 1246874
Columns: 255 entries, isin to str_003b_ec
dtypes: Int64(2), object(253)
memory usage: 1.3+ MB

In [57]:
DF_after_filtered= DF_after_filtered.drop_duplicates(subset='ClarityID')
DF_after_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 1246874
Columns: 255 entries, isin to str_003b_ec
dtypes: Int64(2), object(253)
memory usage: 1.3+ MB

In [58]:
DF_after_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 1246874
Columns: 255 entries, isin to str_003b_ec
dtypes: Int64(2), object(253)
memory usage: 1.3+ MB

In [59]:
DF_after_filtered = DF_after_filtered.drop_duplicates()
DF_after_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 1246874
Columns: 255 entries, isin to str_003b_ec
dtypes: Int64(2), object(253)
memory usage: 1.3+ MB

### Sustainability_rating

In [60]:
#columnas correspondientes en ambos dataframes
DF_before_filtered_sr = DF_before_filtered.loc[:, ['issuer_name', 'permId', 'sustainability_rating']]
DF_after_filtered_sr = DF_after_filtered.loc[:, ['issuer_name','permId', 'sustainability_rating']]

In [61]:
DF_before_filtered_sr = DF_before_filtered_sr.drop_duplicates()
DF_after_filtered_sr = DF_after_filtered_sr.drop_duplicates()

In [62]:
DF_before_filtered_sr.info()
DF_after_filtered_sr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 32 to 1246761
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   issuer_name            686 non-null    object
 1   permId                 686 non-null    int64
 2   sustainability_rating  686 non-null    object
dtypes: int64(1), object(2)
memory usage: 21.4+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 1246874
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   issuer_name            686 non-null    object
 1   permId                 686 non-null    Int64
 2   sustainability_rating  686 non-null    object
dtypes: Int64(1), object(2)
memory usage: 22.1+ KB

In [63]:
# Cambinar en función de permId
DF_merged_sr = pd.merge(DF_before_filtered_sr, DF_after_filtered_sr, on='permId',suffixes=('_before', '_after'))

In [64]:
DF_merged_sr.head()
DF_merged_sr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   issuer_name_before            686 non-null    object
 1   permId                        686 non-null    int64
 2   sustainability_rating_before  686 non-null    object
 3   issuer_name_after             686 non-null    object
 4   sustainability_rating_after   686 non-null    object
dtypes: int64(1), object(4)
memory usage: 32.2+ KB

In [65]:
DF_merged_sr_without_duplicates = DF_merged_sr.drop_duplicates()
DF_merged_sr_without_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   issuer_name_before            686 non-null    object
 1   permId                        686 non-null    int64
 2   sustainability_rating_before  686 non-null    object
 3   issuer_name_after             686 non-null    object
 4   sustainability_rating_after   686 non-null    object
dtypes: int64(1), object(4)
memory usage: 32.2+ KB

In [66]:
DF_merged_sr_without_duplicates.drop(['issuer_name_after'], axis = 'columns', inplace=True)
DF_merged_sr_without_duplicates.rename(columns = {'issuer_name_before':'issuer_name'},inplace =True)
DF_merged_sr_without_duplicates= DF_merged_sr_without_duplicates[['permId','issuer_name', 'sustainability_rating_before','sustainability_rating_after']]

In [67]:
DF_merged_sr_without_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   permId                        686 non-null    int64
 1   issuer_name                   686 non-null    object
 2   sustainability_rating_before  686 non-null    object
 3   sustainability_rating_after   686 non-null    object
dtypes: int64(1), object(3)
memory usage: 26.8+ KB

In [68]:
# Crear columna de variación, verificación
DF_merged_sr_without_duplicates['Variation_Sust_rating'] = DF_merged_sr_without_duplicates.apply(
    lambda row: row['sustainability_rating_before'] != row['sustainability_rating_after'], axis=1)

In [69]:
DF_merged_sr_without_duplicates.head()
DF_merged_sr_without_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   permId                        686 non-null    int64
 1   issuer_name                   686 non-null    object
 2   sustainability_rating_before  686 non-null    object
 3   sustainability_rating_after   686 non-null    object
 4   Variation_Sust_rating         686 non-null    bool
dtypes: bool(1), int64(1), object(3)
memory usage: 27.5+ KB

In [70]:
DF_merged_sr_without_duplicates['permId'].value_counts()

8589934570    1
5042243092    1
5000023943    1
5045949737    1
4295904341    1
             ..
4295885708    1
4296669053    1
4295904557    1
8589934254    1
5051611662    1
Name: permId, Length: 686, dtype: int64

In [71]:
# Crear una lista con el orden deseado de las columnas
column_order = ['permId','issuer_name'] + [col for col in DF_merged_sr_without_duplicates.columns if col not in ['permId','issuer_name']]

# Reordenar las columnas del dataframe según la lista creada
DF_merged_sr_without_duplicates = DF_merged_sr_without_duplicates.reindex(columns=column_order)

In [72]:
DF_merged_sr_without_duplicates.head()

,permId,issuer_name,sustainability_rating_before,sustainability_rating_after,Variation_Sust_rating
0,8589934570,International Bank for Reconstruction and Deve...,Good,Good,False
1,4298009762,Cooperatieve Rabobank UA,Sufficient,Sufficient,False
2,4295903360,General Motors Financial Company Inc,Poor,Poor,False
3,5000001007,Sumitomo Mitsui Banking Corp,Average,Average,False
4,8589934159,European Investment Bank,Leader,Leader,False

In [73]:
#Para solo seleecionar las col que a unir en el resumen 
V_sustainability_rating =DF_merged_sr_without_duplicates[['permId','issuer_name','Variation_Sust_rating']]

In [74]:
V_sustainability_rating.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permId                 686 non-null    int64
 1   issuer_name            686 non-null    object
 2   Variation_Sust_rating  686 non-null    bool
dtypes: bool(1), int64(1), object(1)
memory usage: 16.7+ KB

In [75]:
pd.Series(V_sustainability_rating.Variation_Sust_rating).value_counts()

False    686
Name: Variation_Sust_rating, dtype: int64

In [76]:
SR_True=DF_merged_sr_without_duplicates
in_True_SR= SR_True['Variation_Sust_rating']==True
SR_True= SR_True[in_True_SR]
SR_True.head()
#SR_true.to_excel('X:/INVDESPRO/INVESTIGACION/Fondos éticos/Misbel/Pruebas/Var_SR_True.xlsx',index=False)

Empty DataFrame
Columns: [permId, issuer_name, sustainability_rating_before, sustainability_rating_after, Variation_Sust_rating]
Index: []

In [77]:
SR_True = SR_True[['permId','issuer_name','Variation_Sust_rating','sustainability_rating_before','sustainability_rating_after']]

In [78]:
SR_True.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   permId                        0 non-null      int64
 1   issuer_name                   0 non-null      object
 2   Variation_Sust_rating         0 non-null      bool
 3   sustainability_rating_before  0 non-null      object
 4   sustainability_rating_after   0 non-null      object
dtypes: bool(1), int64(1), object(3)
memory usage: 0.0+ bytes

In [79]:
pd.Series(SR_True.Variation_Sust_rating).value_counts()

Series([], Name: Variation_Sust_rating, dtype: int64)

## Exposure

#### Nota: Si se agrega al DF nueva exposure, agregar a la siguiente lista

In [80]:
Exposure_before = DF_before_filtered.loc[:, ['issuer_name','permId','maxexp_abortifacents_part','maxexp_agrochemical_products_part','maxexp_agrochemical_products_prod','maxexp_alcohol_part',
'maxexp_alchol_prod','maxexp_animal_testing_part','maxexp_animal_testing_cosmetic_part','maxexp_antip_landmines_part',
'maxexp_armament_part','maxexp_armament_prod','maxexp_chemic_biolog_weapons_part','maxexp_cluster_bombs_part','maxexp_coal_mining_part',
'maxexp_coal_mining_prod','maxexp_coal_power_gen_part','maxexp_coal_power_gen_prod','maxexp_contraceptives_part','maxexp_depleted_uranium_part',
'maxexp_embryonic_stem_cell_research_part','maxexp_fossil_fuels_part','maxexp_fossil_fuels_prod','maxexp_fur_exotic_leather_part','maxexp_gambling_part',
'maxexp_gambling_prod','maxexp_gmo_products_part','maxexp_gmo_research_part','maxexp_meat_products_part','maxexp_meat_products_prod','maxexp_cannabis_part',
'maxexp_nuclear_energy_part','maxexp_nuclear_energy_prod','maxexp_nuclear_weapons_part','maxexp_oil_sands_part','maxexp_oil_sands_prod','maxexp_palm_oil_part',
'maxexp_pork_products_part','maxexp_pork_products_prod','maxexp_pornography_part','maxexp_shale_energy_part','maxexp_shale_energy_prod',
'maxexp_stem_cell_research','maxexp_tobacco_part','maxexp_tobacco_prod','maxexp_artic_oil_part','maxexp_predatory_lending_part','maxexp_small_arms_part','maxexp_white_phosporus_part']]

Exposure_before.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 32 to 1246761
Data columns (total 49 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   issuer_name                               686 non-null    object
 1   permId                                    686 non-null    int64
 2   maxexp_abortifacents_part                 585 non-null    object
 3   maxexp_agrochemical_products_part         581 non-null    object
 4   maxexp_agrochemical_products_prod         601 non-null    object
 5   maxexp_alcohol_part                       528 non-null    object
 6   maxexp_alchol_prod                        570 non-null    object
 7   maxexp_animal_testing_part                601 non-null    object
 8   maxexp_animal_testing_cosmetic_part       606 non-null    object
 9   maxexp_antip_landmines_part               616 non-null    object
 10  maxexp_armament_part                      520 non-null    object
 11  maxexp_armament_prod                      574 non-null    object
 12  maxexp_chemic_biolog_weapons_part         615 non-null    object
 13  maxexp_cluster_bombs_part                 572 non-null    object
 14  maxexp_coal_mining_part                   558 non-null    object
 15  maxexp_coal_mining_prod                   566 non-null    object
 16  maxexp_coal_power_gen_part                558 non-null    object
 17  maxexp_coal_power_gen_prod                595 non-null    object
 18  maxexp_contraceptives_part                582 non-null    object
 19  maxexp_depleted_uranium_part              0 non-null      object
 20  maxexp_embryonic_stem_cell_research_part  613 non-null    object
 21  maxexp_fossil_fuels_part                  555 non-null    object
 22  maxexp_fossil_fuels_prod                  564 non-null    object
 23  maxexp_fur_exotic_leather_part            597 non-null    object
 24  maxexp_gambling_part                      529 non-null    object
 25  maxexp_gambling_prod                      537 non-null    object
 26  maxexp_gmo_products_part                  582 non-null    object
 27  maxexp_gmo_research_part                  584 non-null    object
 28  maxexp_meat_products_part                 562 non-null    object
 29  maxexp_meat_products_prod                 608 non-null    object
 30  maxexp_cannabis_part                      604 non-null    object
 31  maxexp_nuclear_energy_part                548 non-null    object
 32  maxexp_nuclear_energy_prod                562 non-null    object
 33  maxexp_nuclear_weapons_part               573 non-null    object
 34  maxexp_oil_sands_part                     546 non-null    object
 35  maxexp_oil_sands_prod                     591 non-null    object
 36  maxexp_palm_oil_part                      601 non-null    object
 37  maxexp_pork_products_part                 604 non-null    object
 38  maxexp_pork_products_prod                 616 non-null    object
 39  maxexp_pornography_part                   581 non-null    object
 40  maxexp_shale_energy_part                  546 non-null    object
 41  maxexp_shale_energy_prod                  566 non-null    object
 42  maxexp_stem_cell_research                 591 non-null    object
 43  maxexp_tobacco_part                       566 non-null    object
 44  maxexp_tobacco_prod                       585 non-null    object
 45  maxexp_artic_oil_part                     606 non-null    object
 46  maxexp_predatory_lending_part             482 non-null    object
 47  maxexp_small_arms_part                    592 non-null    object
 48  maxexp_white_phosporus_part               614 non-null    object
dtypes: int64(1), object(48)
memory usage: 268.0+ KB

In [81]:
Exposure_after = DF_after_filtered.loc[:, ['issuer_name','permId','maxexp_abortifacents_part','maxexp_agrochemical_products_part','maxexp_agrochemical_products_prod','maxexp_alcohol_part',
'maxexp_alchol_prod','maxexp_animal_testing_part','maxexp_animal_testing_cosmetic_part','maxexp_antip_landmines_part',
'maxexp_armament_part','maxexp_armament_prod','maxexp_chemic_biolog_weapons_part','maxexp_cluster_bombs_part','maxexp_coal_mining_part',
'maxexp_coal_mining_prod','maxexp_coal_power_gen_part','maxexp_coal_power_gen_prod','maxexp_contraceptives_part','maxexp_depleted_uranium_part',
'maxexp_embryonic_stem_cell_research_part','maxexp_fossil_fuels_part','maxexp_fossil_fuels_prod','maxexp_fur_exotic_leather_part','maxexp_gambling_part',
'maxexp_gambling_prod','maxexp_gmo_products_part','maxexp_gmo_research_part','maxexp_meat_products_part','maxexp_meat_products_prod','maxexp_cannabis_part',
'maxexp_nuclear_energy_part','maxexp_nuclear_energy_prod','maxexp_nuclear_weapons_part','maxexp_oil_sands_part','maxexp_oil_sands_prod','maxexp_palm_oil_part',
'maxexp_pork_products_part','maxexp_pork_products_prod','maxexp_pornography_part','maxexp_shale_energy_part','maxexp_shale_energy_prod',
'maxexp_stem_cell_research','maxexp_tobacco_part','maxexp_tobacco_prod','maxexp_artic_oil_part','maxexp_predatory_lending_part','maxexp_small_arms_part','maxexp_white_phosporus_part']]
Exposure_after.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 1246874
Data columns (total 49 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   issuer_name                               686 non-null    object
 1   permId                                    686 non-null    Int64
 2   maxexp_abortifacents_part                 585 non-null    object
 3   maxexp_agrochemical_products_part         581 non-null    object
 4   maxexp_agrochemical_products_prod         601 non-null    object
 5   maxexp_alcohol_part                       528 non-null    object
 6   maxexp_alchol_prod                        570 non-null    object
 7   maxexp_animal_testing_part                601 non-null    object
 8   maxexp_animal_testing_cosmetic_part       606 non-null    object
 9   maxexp_antip_landmines_part               616 non-null    object
 10  maxexp_armament_part                      520 non-null    object
 11  maxexp_armament_prod                      574 non-null    object
 12  maxexp_chemic_biolog_weapons_part         615 non-null    object
 13  maxexp_cluster_bombs_part                 572 non-null    object
 14  maxexp_coal_mining_part                   558 non-null    object
 15  maxexp_coal_mining_prod                   566 non-null    object
 16  maxexp_coal_power_gen_part                558 non-null    object
 17  maxexp_coal_power_gen_prod                595 non-null    object
 18  maxexp_contraceptives_part                582 non-null    object
 19  maxexp_depleted_uranium_part              0 non-null      object
 20  maxexp_embryonic_stem_cell_research_part  613 non-null    object
 21  maxexp_fossil_fuels_part                  555 non-null    object
 22  maxexp_fossil_fuels_prod                  564 non-null    object
 23  maxexp_fur_exotic_leather_part            597 non-null    object
 24  maxexp_gambling_part                      529 non-null    object
 25  maxexp_gambling_prod                      537 non-null    object
 26  maxexp_gmo_products_part                  582 non-null    object
 27  maxexp_gmo_research_part                  584 non-null    object
 28  maxexp_meat_products_part                 562 non-null    object
 29  maxexp_meat_products_prod                 608 non-null    object
 30  maxexp_cannabis_part                      604 non-null    object
 31  maxexp_nuclear_energy_part                548 non-null    object
 32  maxexp_nuclear_energy_prod                562 non-null    object
 33  maxexp_nuclear_weapons_part               573 non-null    object
 34  maxexp_oil_sands_part                     546 non-null    object
 35  maxexp_oil_sands_prod                     591 non-null    object
 36  maxexp_palm_oil_part                      601 non-null    object
 37  maxexp_pork_products_part                 604 non-null    object
 38  maxexp_pork_products_prod                 616 non-null    object
 39  maxexp_pornography_part                   581 non-null    object
 40  maxexp_shale_energy_part                  546 non-null    object
 41  maxexp_shale_energy_prod                  566 non-null    object
 42  maxexp_stem_cell_research                 591 non-null    object
 43  maxexp_tobacco_part                       566 non-null    object
 44  maxexp_tobacco_prod                       585 non-null    object
 45  maxexp_artic_oil_part                     606 non-null    object
 46  maxexp_predatory_lending_part             482 non-null    object
 47  maxexp_small_arms_part                    592 non-null    object
 48  maxexp_white_phosporus_part               614 non-null    object
dtypes: Int64(1), object(48)
memory usage: 268.6+ KB

In [82]:
Exposure_before = Exposure_before.drop_duplicates()
Exposure_after = Exposure_after.drop_duplicates()

In [83]:
# Combinar en función de permId
DF_merged_exp = pd.merge(Exposure_before, Exposure_after, on='permId', suffixes=('_before', '_after'))
DF_merged_exp.info()
DF_merged_exp.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 97 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   issuer_name_before                               686 non-null    object
 1   permId                                           686 non-null    int64
 2   maxexp_abortifacents_part_before                 585 non-null    object
 3   maxexp_agrochemical_products_part_before         581 non-null    object
 4   maxexp_agrochemical_products_prod_before         601 non-null    object
 5   maxexp_alcohol_part_before                       528 non-null    object
 6   maxexp_alchol_prod_before                        570 non-null    object
 7   maxexp_animal_testing_part_before                601 non-null    object
 8   maxexp_animal_testing_cosmetic_part_before       606 non-null    object
 9   maxexp_antip_landmines_part_before               616 non-null    object
 10  maxexp_armament_part_before                      520 non-null    object
 11  maxexp_armament_prod_before                      574 non-null    object
 12  maxexp_chemic_biolog_weapons_part_before         615 non-null    object
 13  maxexp_cluster_bombs_part_before                 572 non-null    object
 14  maxexp_coal_mining_part_before                   558 non-null    object
 15  maxexp_coal_mining_prod_before                   566 non-null    object
 16  maxexp_coal_power_gen_part_before                558 non-null    object
 17  maxexp_coal_power_gen_prod_before                595 non-null    object
 18  maxexp_contraceptives_part_before                582 non-null    object
 19  maxexp_depleted_uranium_part_before              0 non-null      object
 20  maxexp_embryonic_stem_cell_research_part_before  613 non-null    object
 21  maxexp_fossil_fuels_part_before                  555 non-null    object
 22  maxexp_fossil_fuels_prod_before                  564 non-null    object
 23  maxexp_fur_exotic_leather_part_before            597 non-null    object
 24  maxexp_gambling_part_before                      529 non-null    object
 25  maxexp_gambling_prod_before                      537 non-null    object
 26  maxexp_gmo_products_part_before                  582 non-null    object
 27  maxexp_gmo_research_part_before                  584 non-null    object
 28  maxexp_meat_products_part_before                 562 non-null    object
 29  maxexp_meat_products_prod_before                 608 non-null    object
 30  maxexp_cannabis_part_before                      604 non-null    object
 31  maxexp_nuclear_energy_part_before                548 non-null    object
 32  maxexp_nuclear_energy_prod_before                562 non-null    object
 33  maxexp_nuclear_weapons_part_before               573 non-null    object
 34  maxexp_oil_sands_part_before                     546 non-null    object
 35  maxexp_oil_sands_prod_before                     591 non-null    object
 36  maxexp_palm_oil_part_before                      601 non-null    object
 37  maxexp_pork_products_part_before                 604 non-null    object
 38  maxexp_pork_products_prod_before                 616 non-null    object
 39  maxexp_pornography_part_before                   581 non-null    object
 40  maxexp_shale_energy_part_before                  546 non-null    object
 41  maxexp_shale_energy_prod_before                  566 non-null    object
 42  maxexp_stem_cell_research_before                 591 non-null    object
 43  maxexp_tobacco_part_before                       566 non-null    object
 44  maxexp_tobacco_prod_before                       585 non-null    object
 45  maxexp_artic_oil_part_before                     606 non-null    object
 46  maxexp_predatory_lending_part_before             482 non-null    object
 47  maxexp_small_arms_part_before                    592 non-null    object
 48  maxexp_white_phosporus_part_before               614 non-null    object
 49  issuer_name_after                                686 non-null    object
 50  maxexp_abortifacents_part_after                  585 non-null    object
 51  maxexp_agrochemical_products_part_after          581 non-null    object
 52  maxexp_agrochemical_products_prod_after          601 non-null    object
 53  maxexp_alcohol_part_after                        528 non-null    object
 54  maxexp_alchol_prod_after                         570 non-null    object
 55  maxexp_animal_testing_part_after                 601 non-null    object
 56  maxexp_animal_testing_cosmetic_part_after        606 non-null    object
 57  maxexp_antip_landmines_part_after                616 non-null    object
 58  maxexp_armament_part_after                       520 non-null    object
 59  maxexp_armament_prod_after                       574 non-null    object
 60  maxexp_chemic_biolog_weapons_part_after          615 non-null    object
 61  maxexp_cluster_bombs_part_after                  572 non-null    object
 62  maxexp_coal_mining_part_after                    558 non-null    object
 63  maxexp_coal_mining_prod_after                    566 non-null    object
 64  maxexp_coal_power_gen_part_after                 558 non-null    object
 65  maxexp_coal_power_gen_prod_after                 595 non-null    object
 66  maxexp_contraceptives_part_after                 582 non-null    object
 67  maxexp_depleted_uranium_part_after               0 non-null      object
 68  maxexp_embryonic_stem_cell_research_part_after   613 non-null    object
 69  maxexp_fossil_fuels_part_after                   555 non-null    object
 70  maxexp_fossil_fuels_prod_after                   564 non-null    object
 71  maxexp_fur_exotic_leather_part_after             597 non-null    object
 72  maxexp_gambling_part_after                       529 non-null    object
 73  maxexp_gambling_prod_after                       537 non-null    object
 74  maxexp_gmo_products_part_after                   582 non-null    object
 75  maxexp_gmo_research_part_after                   584 non-null    object
 76  maxexp_meat_products_part_after                  562 non-null    object
 77  maxexp_meat_products_prod_after                  608 non-null    object
 78  maxexp_cannabis_part_after                       604 non-null    object
 79  maxexp_nuclear_energy_part_after                 548 non-null    object
 80  maxexp_nuclear_energy_prod_after                 562 non-null    object
 81  maxexp_nuclear_weapons_part_after                573 non-null    object
 82  maxexp_oil_sands_part_after                      546 non-null    object
 83  maxexp_oil_sands_prod_after                      591 non-null    object
 84  maxexp_palm_oil_part_after                       601 non-null    object
 85  maxexp_pork_products_part_after                  604 non-null    object
 86  maxexp_pork_products_prod_after                  616 non-null    object
 87  maxexp_pornography_part_after                    581 non-null    object
 88  maxexp_shale_energy_part_after                   546 non-null    object
 89  maxexp_shale_energy_prod_after                   566 non-null    object
 90  maxexp_stem_cell_research_after                  591 non-null    object
 91  maxexp_tobacco_part_after                        566 non-null    object
 92  maxexp_tobacco_prod_after                        585 non-null    object
 93  maxexp_artic_oil_part_after                      606 non-null    object
 94  maxexp_predatory_lending_part_after              482 non-null    object
 95  maxexp_small_arms_part_after                     592 non-null    object
 96  maxexp_white_phosporus_part_after                614 non-null    object
dtypes: int64(1), object(96)
memory usage: 525.2+ KB

,issuer_name_before,permId,maxexp_abortifacents_part_before,maxexp_agrochemical_products_part_before,maxexp_agrochemical_products_prod_before,maxexp_alcohol_part_before,maxexp_alchol_prod_before,maxexp_animal_testing_part_before,maxexp_animal_testing_cosmetic_part_before,maxexp_antip_landmines_part_before,...,maxexp_pornography_part_after,maxexp_shale_energy_part_after,maxexp_shale_energy_prod_after,maxexp_stem_cell_research_after,maxexp_tobacco_part_after,maxexp_tobacco_prod_after,maxexp_artic_oil_part_after,maxexp_predatory_lending_part_after,maxexp_small_arms_part_after,maxexp_white_phosporus_part_after
0,International Bank for Reconstruction and Deve...,8589934570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Cooperatieve Rabobank UA,4298009762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
2,General Motors Financial Company Inc,4295903360,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0
3,Sumitomo Mitsui Banking Corp,5000001007,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,NaN,0.0,0.0
4,European Investment Bank,8589934159,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0

In [84]:
DF_merged_exp = DF_merged_exp.fillna(0)
DF_merged_exp.info()
DF_merged_exp.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 97 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   issuer_name_before                               686 non-null    object
 1   permId                                           686 non-null    int64
 2   maxexp_abortifacents_part_before                 686 non-null    object
 3   maxexp_agrochemical_products_part_before         686 non-null    object
 4   maxexp_agrochemical_products_prod_before         686 non-null    object
 5   maxexp_alcohol_part_before                       686 non-null    object
 6   maxexp_alchol_prod_before                        686 non-null    object
 7   maxexp_animal_testing_part_before                686 non-null    object
 8   maxexp_animal_testing_cosmetic_part_before       686 non-null    object
 9   maxexp_antip_landmines_part_before               686 non-null    object
 10  maxexp_armament_part_before                      686 non-null    object
 11  maxexp_armament_prod_before                      686 non-null    object
 12  maxexp_chemic_biolog_weapons_part_before         686 non-null    object
 13  maxexp_cluster_bombs_part_before                 686 non-null    object
 14  maxexp_coal_mining_part_before                   686 non-null    object
 15  maxexp_coal_mining_prod_before                   686 non-null    object
 16  maxexp_coal_power_gen_part_before                686 non-null    object
 17  maxexp_coal_power_gen_prod_before                686 non-null    object
 18  maxexp_contraceptives_part_before                686 non-null    object
 19  maxexp_depleted_uranium_part_before              686 non-null    int64
 20  maxexp_embryonic_stem_cell_research_part_before  686 non-null    object
 21  maxexp_fossil_fuels_part_before                  686 non-null    object
 22  maxexp_fossil_fuels_prod_before                  686 non-null    object
 23  maxexp_fur_exotic_leather_part_before            686 non-null    object
 24  maxexp_gambling_part_before                      686 non-null    object
 25  maxexp_gambling_prod_before                      686 non-null    object
 26  maxexp_gmo_products_part_before                  686 non-null    object
 27  maxexp_gmo_research_part_before                  686 non-null    object
 28  maxexp_meat_products_part_before                 686 non-null    object
 29  maxexp_meat_products_prod_before                 686 non-null    object
 30  maxexp_cannabis_part_before                      686 non-null    object
 31  maxexp_nuclear_energy_part_before                686 non-null    object
 32  maxexp_nuclear_energy_prod_before                686 non-null    object
 33  maxexp_nuclear_weapons_part_before               686 non-null    object
 34  maxexp_oil_sands_part_before                     686 non-null    object
 35  maxexp_oil_sands_prod_before                     686 non-null    object
 36  maxexp_palm_oil_part_before                      686 non-null    object
 37  maxexp_pork_products_part_before                 686 non-null    object
 38  maxexp_pork_products_prod_before                 686 non-null    object
 39  maxexp_pornography_part_before                   686 non-null    object
 40  maxexp_shale_energy_part_before                  686 non-null    object
 41  maxexp_shale_energy_prod_before                  686 non-null    object
 42  maxexp_stem_cell_research_before                 686 non-null    object
 43  maxexp_tobacco_part_before                       686 non-null    object
 44  maxexp_tobacco_prod_before                       686 non-null    object
 45  maxexp_artic_oil_part_before                     686 non-null    object
 46  maxexp_predatory_lending_part_before             686 non-null    object
 47  maxexp_small_arms_part_before                    686 non-null    object
 48  maxexp_white_phosporus_part_before               686 non-null    object
 49  issuer_name_after                                686 non-null    object
 50  maxexp_abortifacents_part_after                  686 non-null    object
 51  maxexp_agrochemical_products_part_after          686 non-null    object
 52  maxexp_agrochemical_products_prod_after          686 non-null    object
 53  maxexp_alcohol_part_after                        686 non-null    object
 54  maxexp_alchol_prod_after                         686 non-null    object
 55  maxexp_animal_testing_part_after                 686 non-null    object
 56  maxexp_animal_testing_cosmetic_part_after        686 non-null    object
 57  maxexp_antip_landmines_part_after                686 non-null    object
 58  maxexp_armament_part_after                       686 non-null    object
 59  maxexp_armament_prod_after                       686 non-null    object
 60  maxexp_chemic_biolog_weapons_part_after          686 non-null    object
 61  maxexp_cluster_bombs_part_after                  686 non-null    object
 62  maxexp_coal_mining_part_after                    686 non-null    object
 63  maxexp_coal_mining_prod_after                    686 non-null    object
 64  maxexp_coal_power_gen_part_after                 686 non-null    object
 65  maxexp_coal_power_gen_prod_after                 686 non-null    object
 66  maxexp_contraceptives_part_after                 686 non-null    object
 67  maxexp_depleted_uranium_part_after               686 non-null    int64
 68  maxexp_embryonic_stem_cell_research_part_after   686 non-null    object
 69  maxexp_fossil_fuels_part_after                   686 non-null    object
 70  maxexp_fossil_fuels_prod_after                   686 non-null    object
 71  maxexp_fur_exotic_leather_part_after             686 non-null    object
 72  maxexp_gambling_part_after                       686 non-null    object
 73  maxexp_gambling_prod_after                       686 non-null    object
 74  maxexp_gmo_products_part_after                   686 non-null    object
 75  maxexp_gmo_research_part_after                   686 non-null    object
 76  maxexp_meat_products_part_after                  686 non-null    object
 77  maxexp_meat_products_prod_after                  686 non-null    object
 78  maxexp_cannabis_part_after                       686 non-null    object
 79  maxexp_nuclear_energy_part_after                 686 non-null    object
 80  maxexp_nuclear_energy_prod_after                 686 non-null    object
 81  maxexp_nuclear_weapons_part_after                686 non-null    object
 82  maxexp_oil_sands_part_after                      686 non-null    object
 83  maxexp_oil_sands_prod_after                      686 non-null    object
 84  maxexp_palm_oil_part_after                       686 non-null    object
 85  maxexp_pork_products_part_after                  686 non-null    object
 86  maxexp_pork_products_prod_after                  686 non-null    object
 87  maxexp_pornography_part_after                    686 non-null    object
 88  maxexp_shale_energy_part_after                   686 non-null    object
 89  maxexp_shale_energy_prod_after                   686 non-null    object
 90  maxexp_stem_cell_research_after                  686 non-null    object
 91  maxexp_tobacco_part_after                        686 non-null    object
 92  maxexp_tobacco_prod_after                        686 non-null    object
 93  maxexp_artic_oil_part_after                      686 non-null    object
 94  maxexp_predatory_lending_part_after              686 non-null    object
 95  maxexp_small_arms_part_after                     686 non-null    object
 96  maxexp_white_phosporus_part_after                686 non-null    object
dtypes: int64(3), object(94)
memory usage: 525.2+ KB

,issuer_name_before,permId,maxexp_abortifacents_part_before,maxexp_agrochemical_products_part_before,maxexp_agrochemical_products_prod_before,maxexp_alcohol_part_before,maxexp_alchol_prod_before,maxexp_animal_testing_part_before,maxexp_animal_testing_cosmetic_part_before,maxexp_antip_landmines_part_before,...,maxexp_pornography_part_after,maxexp_shale_energy_part_after,maxexp_shale_energy_prod_after,maxexp_stem_cell_research_after,maxexp_tobacco_part_after,maxexp_tobacco_prod_after,maxexp_artic_oil_part_after,maxexp_predatory_lending_part_after,maxexp_small_arms_part_after,maxexp_white_phosporus_part_after
0,International Bank for Reconstruction and Deve...,8589934570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Cooperatieve Rabobank UA,4298009762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
2,General Motors Financial Company Inc,4295903360,0.0,0.0,0.0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
3,Sumitomo Mitsui Banking Corp,5000001007,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0,0.0,0.0
4,European Investment Bank,8589934159,0.0,0.0,0.0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0

In [85]:
DF_merged_exp.drop(['issuer_name_after'], axis = 'columns', inplace=True)
DF_merged_exp.rename(columns = {'issuer_name_before':'issuer_name'},inplace =True)
DF_merged_exp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 96 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   issuer_name                                      686 non-null    object
 1   permId                                           686 non-null    int64
 2   maxexp_abortifacents_part_before                 686 non-null    object
 3   maxexp_agrochemical_products_part_before         686 non-null    object
 4   maxexp_agrochemical_products_prod_before         686 non-null    object
 5   maxexp_alcohol_part_before                       686 non-null    object
 6   maxexp_alchol_prod_before                        686 non-null    object
 7   maxexp_animal_testing_part_before                686 non-null    object
 8   maxexp_animal_testing_cosmetic_part_before       686 non-null    object
 9   maxexp_antip_landmines_part_before               686 non-null    object
 10  maxexp_armament_part_before                      686 non-null    object
 11  maxexp_armament_prod_before                      686 non-null    object
 12  maxexp_chemic_biolog_weapons_part_before         686 non-null    object
 13  maxexp_cluster_bombs_part_before                 686 non-null    object
 14  maxexp_coal_mining_part_before                   686 non-null    object
 15  maxexp_coal_mining_prod_before                   686 non-null    object
 16  maxexp_coal_power_gen_part_before                686 non-null    object
 17  maxexp_coal_power_gen_prod_before                686 non-null    object
 18  maxexp_contraceptives_part_before                686 non-null    object
 19  maxexp_depleted_uranium_part_before              686 non-null    int64
 20  maxexp_embryonic_stem_cell_research_part_before  686 non-null    object
 21  maxexp_fossil_fuels_part_before                  686 non-null    object
 22  maxexp_fossil_fuels_prod_before                  686 non-null    object
 23  maxexp_fur_exotic_leather_part_before            686 non-null    object
 24  maxexp_gambling_part_before                      686 non-null    object
 25  maxexp_gambling_prod_before                      686 non-null    object
 26  maxexp_gmo_products_part_before                  686 non-null    object
 27  maxexp_gmo_research_part_before                  686 non-null    object
 28  maxexp_meat_products_part_before                 686 non-null    object
 29  maxexp_meat_products_prod_before                 686 non-null    object
 30  maxexp_cannabis_part_before                      686 non-null    object
 31  maxexp_nuclear_energy_part_before                686 non-null    object
 32  maxexp_nuclear_energy_prod_before                686 non-null    object
 33  maxexp_nuclear_weapons_part_before               686 non-null    object
 34  maxexp_oil_sands_part_before                     686 non-null    object
 35  maxexp_oil_sands_prod_before                     686 non-null    object
 36  maxexp_palm_oil_part_before                      686 non-null    object
 37  maxexp_pork_products_part_before                 686 non-null    object
 38  maxexp_pork_products_prod_before                 686 non-null    object
 39  maxexp_pornography_part_before                   686 non-null    object
 40  maxexp_shale_energy_part_before                  686 non-null    object
 41  maxexp_shale_energy_prod_before                  686 non-null    object
 42  maxexp_stem_cell_research_before                 686 non-null    object
 43  maxexp_tobacco_part_before                       686 non-null    object
 44  maxexp_tobacco_prod_before                       686 non-null    object
 45  maxexp_artic_oil_part_before                     686 non-null    object
 46  maxexp_predatory_lending_part_before             686 non-null    object
 47  maxexp_small_arms_part_before                    686 non-null    object
 48  maxexp_white_phosporus_part_before               686 non-null    object
 49  maxexp_abortifacents_part_after                  686 non-null    object
 50  maxexp_agrochemical_products_part_after          686 non-null    object
 51  maxexp_agrochemical_products_prod_after          686 non-null    object
 52  maxexp_alcohol_part_after                        686 non-null    object
 53  maxexp_alchol_prod_after                         686 non-null    object
 54  maxexp_animal_testing_part_after                 686 non-null    object
 55  maxexp_animal_testing_cosmetic_part_after        686 non-null    object
 56  maxexp_antip_landmines_part_after                686 non-null    object
 57  maxexp_armament_part_after                       686 non-null    object
 58  maxexp_armament_prod_after                       686 non-null    object
 59  maxexp_chemic_biolog_weapons_part_after          686 non-null    object
 60  maxexp_cluster_bombs_part_after                  686 non-null    object
 61  maxexp_coal_mining_part_after                    686 non-null    object
 62  maxexp_coal_mining_prod_after                    686 non-null    object
 63  maxexp_coal_power_gen_part_after                 686 non-null    object
 64  maxexp_coal_power_gen_prod_after                 686 non-null    object
 65  maxexp_contraceptives_part_after                 686 non-null    object
 66  maxexp_depleted_uranium_part_after               686 non-null    int64
 67  maxexp_embryonic_stem_cell_research_part_after   686 non-null    object
 68  maxexp_fossil_fuels_part_after                   686 non-null    object
 69  maxexp_fossil_fuels_prod_after                   686 non-null    object
 70  maxexp_fur_exotic_leather_part_after             686 non-null    object
 71  maxexp_gambling_part_after                       686 non-null    object
 72  maxexp_gambling_prod_after                       686 non-null    object
 73  maxexp_gmo_products_part_after                   686 non-null    object
 74  maxexp_gmo_research_part_after                   686 non-null    object
 75  maxexp_meat_products_part_after                  686 non-null    object
 76  maxexp_meat_products_prod_after                  686 non-null    object
 77  maxexp_cannabis_part_after                       686 non-null    object
 78  maxexp_nuclear_energy_part_after                 686 non-null    object
 79  maxexp_nuclear_energy_prod_after                 686 non-null    object
 80  maxexp_nuclear_weapons_part_after                686 non-null    object
 81  maxexp_oil_sands_part_after                      686 non-null    object
 82  maxexp_oil_sands_prod_after                      686 non-null    object
 83  maxexp_palm_oil_part_after                       686 non-null    object
 84  maxexp_pork_products_part_after                  686 non-null    object
 85  maxexp_pork_products_prod_after                  686 non-null    object
 86  maxexp_pornography_part_after                    686 non-null    object
 87  maxexp_shale_energy_part_after                   686 non-null    object
 88  maxexp_shale_energy_prod_after                   686 non-null    object
 89  maxexp_stem_cell_research_after                  686 non-null    object
 90  maxexp_tobacco_part_after                        686 non-null    object
 91  maxexp_tobacco_prod_after                        686 non-null    object
 92  maxexp_artic_oil_part_after                      686 non-null    object
 93  maxexp_predatory_lending_part_after              686 non-null    object
 94  maxexp_small_arms_part_after                     686 non-null    object
 95  maxexp_white_phosporus_part_after                686 non-null    object
dtypes: int64(3), object(93)
memory usage: 519.9+ KB

In [86]:
DF_merged_exp['permId'].value_counts()

8589934570    1
5042243092    1
5000023943    1
5045949737    1
4295904341    1
             ..
4295885708    1
4296669053    1
4295904557    1
8589934254    1
5051611662    1
Name: permId, Length: 686, dtype: int64

In [87]:
DF_exp_v = DF_merged_exp.copy()
DF_exp_v.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 96 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   issuer_name                                      686 non-null    object
 1   permId                                           686 non-null    int64
 2   maxexp_abortifacents_part_before                 686 non-null    object
 3   maxexp_agrochemical_products_part_before         686 non-null    object
 4   maxexp_agrochemical_products_prod_before         686 non-null    object
 5   maxexp_alcohol_part_before                       686 non-null    object
 6   maxexp_alchol_prod_before                        686 non-null    object
 7   maxexp_animal_testing_part_before                686 non-null    object
 8   maxexp_animal_testing_cosmetic_part_before       686 non-null    object
 9   maxexp_antip_landmines_part_before               686 non-null    object
 10  maxexp_armament_part_before                      686 non-null    object
 11  maxexp_armament_prod_before                      686 non-null    object
 12  maxexp_chemic_biolog_weapons_part_before         686 non-null    object
 13  maxexp_cluster_bombs_part_before                 686 non-null    object
 14  maxexp_coal_mining_part_before                   686 non-null    object
 15  maxexp_coal_mining_prod_before                   686 non-null    object
 16  maxexp_coal_power_gen_part_before                686 non-null    object
 17  maxexp_coal_power_gen_prod_before                686 non-null    object
 18  maxexp_contraceptives_part_before                686 non-null    object
 19  maxexp_depleted_uranium_part_before              686 non-null    int64
 20  maxexp_embryonic_stem_cell_research_part_before  686 non-null    object
 21  maxexp_fossil_fuels_part_before                  686 non-null    object
 22  maxexp_fossil_fuels_prod_before                  686 non-null    object
 23  maxexp_fur_exotic_leather_part_before            686 non-null    object
 24  maxexp_gambling_part_before                      686 non-null    object
 25  maxexp_gambling_prod_before                      686 non-null    object
 26  maxexp_gmo_products_part_before                  686 non-null    object
 27  maxexp_gmo_research_part_before                  686 non-null    object
 28  maxexp_meat_products_part_before                 686 non-null    object
 29  maxexp_meat_products_prod_before                 686 non-null    object
 30  maxexp_cannabis_part_before                      686 non-null    object
 31  maxexp_nuclear_energy_part_before                686 non-null    object
 32  maxexp_nuclear_energy_prod_before                686 non-null    object
 33  maxexp_nuclear_weapons_part_before               686 non-null    object
 34  maxexp_oil_sands_part_before                     686 non-null    object
 35  maxexp_oil_sands_prod_before                     686 non-null    object
 36  maxexp_palm_oil_part_before                      686 non-null    object
 37  maxexp_pork_products_part_before                 686 non-null    object
 38  maxexp_pork_products_prod_before                 686 non-null    object
 39  maxexp_pornography_part_before                   686 non-null    object
 40  maxexp_shale_energy_part_before                  686 non-null    object
 41  maxexp_shale_energy_prod_before                  686 non-null    object
 42  maxexp_stem_cell_research_before                 686 non-null    object
 43  maxexp_tobacco_part_before                       686 non-null    object
 44  maxexp_tobacco_prod_before                       686 non-null    object
 45  maxexp_artic_oil_part_before                     686 non-null    object
 46  maxexp_predatory_lending_part_before             686 non-null    object
 47  maxexp_small_arms_part_before                    686 non-null    object
 48  maxexp_white_phosporus_part_before               686 non-null    object
 49  maxexp_abortifacents_part_after                  686 non-null    object
 50  maxexp_agrochemical_products_part_after          686 non-null    object
 51  maxexp_agrochemical_products_prod_after          686 non-null    object
 52  maxexp_alcohol_part_after                        686 non-null    object
 53  maxexp_alchol_prod_after                         686 non-null    object
 54  maxexp_animal_testing_part_after                 686 non-null    object
 55  maxexp_animal_testing_cosmetic_part_after        686 non-null    object
 56  maxexp_antip_landmines_part_after                686 non-null    object
 57  maxexp_armament_part_after                       686 non-null    object
 58  maxexp_armament_prod_after                       686 non-null    object
 59  maxexp_chemic_biolog_weapons_part_after          686 non-null    object
 60  maxexp_cluster_bombs_part_after                  686 non-null    object
 61  maxexp_coal_mining_part_after                    686 non-null    object
 62  maxexp_coal_mining_prod_after                    686 non-null    object
 63  maxexp_coal_power_gen_part_after                 686 non-null    object
 64  maxexp_coal_power_gen_prod_after                 686 non-null    object
 65  maxexp_contraceptives_part_after                 686 non-null    object
 66  maxexp_depleted_uranium_part_after               686 non-null    int64
 67  maxexp_embryonic_stem_cell_research_part_after   686 non-null    object
 68  maxexp_fossil_fuels_part_after                   686 non-null    object
 69  maxexp_fossil_fuels_prod_after                   686 non-null    object
 70  maxexp_fur_exotic_leather_part_after             686 non-null    object
 71  maxexp_gambling_part_after                       686 non-null    object
 72  maxexp_gambling_prod_after                       686 non-null    object
 73  maxexp_gmo_products_part_after                   686 non-null    object
 74  maxexp_gmo_research_part_after                   686 non-null    object
 75  maxexp_meat_products_part_after                  686 non-null    object
 76  maxexp_meat_products_prod_after                  686 non-null    object
 77  maxexp_cannabis_part_after                       686 non-null    object
 78  maxexp_nuclear_energy_part_after                 686 non-null    object
 79  maxexp_nuclear_energy_prod_after                 686 non-null    object
 80  maxexp_nuclear_weapons_part_after                686 non-null    object
 81  maxexp_oil_sands_part_after                      686 non-null    object
 82  maxexp_oil_sands_prod_after                      686 non-null    object
 83  maxexp_palm_oil_part_after                       686 non-null    object
 84  maxexp_pork_products_part_after                  686 non-null    object
 85  maxexp_pork_products_prod_after                  686 non-null    object
 86  maxexp_pornography_part_after                    686 non-null    object
 87  maxexp_shale_energy_part_after                   686 non-null    object
 88  maxexp_shale_energy_prod_after                   686 non-null    object
 89  maxexp_stem_cell_research_after                  686 non-null    object
 90  maxexp_tobacco_part_after                        686 non-null    object
 91  maxexp_tobacco_prod_after                        686 non-null    object
 92  maxexp_artic_oil_part_after                      686 non-null    object
 93  maxexp_predatory_lending_part_after              686 non-null    object
 94  maxexp_small_arms_part_after                     686 non-null    object
 95  maxexp_white_phosporus_part_after                686 non-null    object
dtypes: int64(3), object(93)
memory usage: 519.9+ KB

In [88]:
#Ordenar
col_groups = {}
for col in DF_exp_v.columns:
    col_name, _, suffix = col.rpartition('_')
    col_groups.setdefault(col_name, []).append((suffix, col))

sorted_cols = []
for col_name in sorted(col_groups.keys()):
    sorted_cols.extend(col for _, col in sorted(col_groups[col_name]))
    
df_sorted = DF_exp_v[sorted_cols]
df_sorted = df_sorted.reindex(sorted(df_sorted.columns), axis=1)


permId_col = df_sorted.pop("permId")
df_sorted.insert(0, "permId", permId_col)

In [89]:
df_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 96 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   permId                                           686 non-null    int64
 1   issuer_name                                      686 non-null    object
 2   maxexp_abortifacents_part_after                  686 non-null    object
 3   maxexp_abortifacents_part_before                 686 non-null    object
 4   maxexp_agrochemical_products_part_after          686 non-null    object
 5   maxexp_agrochemical_products_part_before         686 non-null    object
 6   maxexp_agrochemical_products_prod_after          686 non-null    object
 7   maxexp_agrochemical_products_prod_before         686 non-null    object
 8   maxexp_alchol_prod_after                         686 non-null    object
 9   maxexp_alchol_prod_before                        686 non-null    object
 10  maxexp_alcohol_part_after                        686 non-null    object
 11  maxexp_alcohol_part_before                       686 non-null    object
 12  maxexp_animal_testing_cosmetic_part_after        686 non-null    object
 13  maxexp_animal_testing_cosmetic_part_before       686 non-null    object
 14  maxexp_animal_testing_part_after                 686 non-null    object
 15  maxexp_animal_testing_part_before                686 non-null    object
 16  maxexp_antip_landmines_part_after                686 non-null    object
 17  maxexp_antip_landmines_part_before               686 non-null    object
 18  maxexp_armament_part_after                       686 non-null    object
 19  maxexp_armament_part_before                      686 non-null    object
 20  maxexp_armament_prod_after                       686 non-null    object
 21  maxexp_armament_prod_before                      686 non-null    object
 22  maxexp_artic_oil_part_after                      686 non-null    object
 23  maxexp_artic_oil_part_before                     686 non-null    object
 24  maxexp_cannabis_part_after                       686 non-null    object
 25  maxexp_cannabis_part_before                      686 non-null    object
 26  maxexp_chemic_biolog_weapons_part_after          686 non-null    object
 27  maxexp_chemic_biolog_weapons_part_before         686 non-null    object
 28  maxexp_cluster_bombs_part_after                  686 non-null    object
 29  maxexp_cluster_bombs_part_before                 686 non-null    object
 30  maxexp_coal_mining_part_after                    686 non-null    object
 31  maxexp_coal_mining_part_before                   686 non-null    object
 32  maxexp_coal_mining_prod_after                    686 non-null    object
 33  maxexp_coal_mining_prod_before                   686 non-null    object
 34  maxexp_coal_power_gen_part_after                 686 non-null    object
 35  maxexp_coal_power_gen_part_before                686 non-null    object
 36  maxexp_coal_power_gen_prod_after                 686 non-null    object
 37  maxexp_coal_power_gen_prod_before                686 non-null    object
 38  maxexp_contraceptives_part_after                 686 non-null    object
 39  maxexp_contraceptives_part_before                686 non-null    object
 40  maxexp_depleted_uranium_part_after               686 non-null    int64
 41  maxexp_depleted_uranium_part_before              686 non-null    int64
 42  maxexp_embryonic_stem_cell_research_part_after   686 non-null    object
 43  maxexp_embryonic_stem_cell_research_part_before  686 non-null    object
 44  maxexp_fossil_fuels_part_after                   686 non-null    object
 45  maxexp_fossil_fuels_part_before                  686 non-null    object
 46  maxexp_fossil_fuels_prod_after                   686 non-null    object
 47  maxexp_fossil_fuels_prod_before                  686 non-null    object
 48  maxexp_fur_exotic_leather_part_after             686 non-null    object
 49  maxexp_fur_exotic_leather_part_before            686 non-null    object
 50  maxexp_gambling_part_after                       686 non-null    object
 51  maxexp_gambling_part_before                      686 non-null    object
 52  maxexp_gambling_prod_after                       686 non-null    object
 53  maxexp_gambling_prod_before                      686 non-null    object
 54  maxexp_gmo_products_part_after                   686 non-null    object
 55  maxexp_gmo_products_part_before                  686 non-null    object
 56  maxexp_gmo_research_part_after                   686 non-null    object
 57  maxexp_gmo_research_part_before                  686 non-null    object
 58  maxexp_meat_products_part_after                  686 non-null    object
 59  maxexp_meat_products_part_before                 686 non-null    object
 60  maxexp_meat_products_prod_after                  686 non-null    object
 61  maxexp_meat_products_prod_before                 686 non-null    object
 62  maxexp_nuclear_energy_part_after                 686 non-null    object
 63  maxexp_nuclear_energy_part_before                686 non-null    object
 64  maxexp_nuclear_energy_prod_after                 686 non-null    object
 65  maxexp_nuclear_energy_prod_before                686 non-null    object
 66  maxexp_nuclear_weapons_part_after                686 non-null    object
 67  maxexp_nuclear_weapons_part_before               686 non-null    object
 68  maxexp_oil_sands_part_after                      686 non-null    object
 69  maxexp_oil_sands_part_before                     686 non-null    object
 70  maxexp_oil_sands_prod_after                      686 non-null    object
 71  maxexp_oil_sands_prod_before                     686 non-null    object
 72  maxexp_palm_oil_part_after                       686 non-null    object
 73  maxexp_palm_oil_part_before                      686 non-null    object
 74  maxexp_pork_products_part_after                  686 non-null    object
 75  maxexp_pork_products_part_before                 686 non-null    object
 76  maxexp_pork_products_prod_after                  686 non-null    object
 77  maxexp_pork_products_prod_before                 686 non-null    object
 78  maxexp_pornography_part_after                    686 non-null    object
 79  maxexp_pornography_part_before                   686 non-null    object
 80  maxexp_predatory_lending_part_after              686 non-null    object
 81  maxexp_predatory_lending_part_before             686 non-null    object
 82  maxexp_shale_energy_part_after                   686 non-null    object
 83  maxexp_shale_energy_part_before                  686 non-null    object
 84  maxexp_shale_energy_prod_after                   686 non-null    object
 85  maxexp_shale_energy_prod_before                  686 non-null    object
 86  maxexp_small_arms_part_after                     686 non-null    object
 87  maxexp_small_arms_part_before                    686 non-null    object
 88  maxexp_stem_cell_research_after                  686 non-null    object
 89  maxexp_stem_cell_research_before                 686 non-null    object
 90  maxexp_tobacco_part_after                        686 non-null    object
 91  maxexp_tobacco_part_before                       686 non-null    object
 92  maxexp_tobacco_prod_after                        686 non-null    object
 93  maxexp_tobacco_prod_before                       686 non-null    object
 94  maxexp_white_phosporus_part_after                686 non-null    object
 95  maxexp_white_phosporus_part_before               686 non-null    object
dtypes: int64(3), object(93)
memory usage: 519.9+ KB

In [90]:
nombres_columnas = df_sorted.columns.tolist()
nombres_columnas

['permId',
 'issuer_name',
 'maxexp_abortifacents_part_after',
 'maxexp_abortifacents_part_before',
 'maxexp_agrochemical_products_part_after',
 'maxexp_agrochemical_products_part_before',
 'maxexp_agrochemical_products_prod_after',
 'maxexp_agrochemical_products_prod_before',
 'maxexp_alchol_prod_after',
 'maxexp_alchol_prod_before',
 'maxexp_alcohol_part_after',
 'maxexp_alcohol_part_before',
 'maxexp_animal_testing_cosmetic_part_after',
 'maxexp_animal_testing_cosmetic_part_before',
 'maxexp_animal_testing_part_after',
 'maxexp_animal_testing_part_before',
 'maxexp_antip_landmines_part_after',
 'maxexp_antip_landmines_part_before',
 'maxexp_armament_part_after',
 'maxexp_armament_part_before',
 'maxexp_armament_prod_after',
 'maxexp_armament_prod_before',
 'maxexp_artic_oil_part_after',
 'maxexp_artic_oil_part_before',
 'maxexp_cannabis_part_after',
 'maxexp_cannabis_part_before',
 'maxexp_chemic_biolog_weapons_part_after',
 'maxexp_chemic_biolog_weapons_part_before',
 'maxexp_cluster_bombs_part_after',
 'maxexp_cluster_bombs_part_before',
 'maxexp_coal_mining_part_after',
 'maxexp_coal_mining_part_before',
 'maxexp_coal_mining_prod_after',
 'maxexp_coal_mining_prod_before',
 'maxexp_coal_power_gen_part_after',
 'maxexp_coal_power_gen_part_before',
 'maxexp_coal_power_gen_prod_after',
 'maxexp_coal_power_gen_prod_before',
 'maxexp_contraceptives_part_after',
 'maxexp_contraceptives_part_before',
 'maxexp_depleted_uranium_part_after',
 'maxexp_depleted_uranium_part_before',
 'maxexp_embryonic_stem_cell_research_part_after',
 'maxexp_embryonic_stem_cell_research_part_before',
 'maxexp_fossil_fuels_part_after',
 'maxexp_fossil_fuels_part_before',
 'maxexp_fossil_fuels_prod_after',
 'maxexp_fossil_fuels_prod_before',
 'maxexp_fur_exotic_leather_part_after',
 'maxexp_fur_exotic_leather_part_before',
 'maxexp_gambling_part_after',
 'maxexp_gambling_part_before',
 'maxexp_gambling_prod_after',
 'maxexp_gambling_prod_before',
 'maxexp_gmo_products_part_after',
 'maxexp_gmo_products_part_before',
 'maxexp_gmo_research_part_after',
 'maxexp_gmo_research_part_before',
 'maxexp_meat_products_part_after',
 'maxexp_meat_products_part_before',
 'maxexp_meat_products_prod_after',
 'maxexp_meat_products_prod_before',
 'maxexp_nuclear_energy_part_after',
 'maxexp_nuclear_energy_part_before',
 'maxexp_nuclear_energy_prod_after',
 'maxexp_nuclear_energy_prod_before',
 'maxexp_nuclear_weapons_part_after',
 'maxexp_nuclear_weapons_part_before',
 'maxexp_oil_sands_part_after',
 'maxexp_oil_sands_part_before',
 'maxexp_oil_sands_prod_after',
 'maxexp_oil_sands_prod_before',
 'maxexp_palm_oil_part_after',
 'maxexp_palm_oil_part_before',
 'maxexp_pork_products_part_after',
 'maxexp_pork_products_part_before',
 'maxexp_pork_products_prod_after',
 'maxexp_pork_products_prod_before',
 'maxexp_pornography_part_after',
 'maxexp_pornography_part_before',
 'maxexp_predatory_lending_part_after',
 'maxexp_predatory_lending_part_before',
 'maxexp_shale_energy_part_after',
 'maxexp_shale_energy_part_before',
 'maxexp_shale_energy_prod_after',
 'maxexp_shale_energy_prod_before',
 'maxexp_small_arms_part_after',
 'maxexp_small_arms_part_before',
 'maxexp_stem_cell_research_after',
 'maxexp_stem_cell_research_before',
 'maxexp_tobacco_part_after',
 'maxexp_tobacco_part_before',
 'maxexp_tobacco_prod_after',
 'maxexp_tobacco_prod_before',
 'maxexp_white_phosporus_part_after',
 'maxexp_white_phosporus_part_before']

In [91]:
df_sorted= df_sorted[['permId',
 'issuer_name',
 'maxexp_abortifacents_part_before',
 'maxexp_abortifacents_part_after',
 'maxexp_agrochemical_products_part_before',
 'maxexp_agrochemical_products_part_after',
 'maxexp_agrochemical_products_prod_before',
 'maxexp_agrochemical_products_prod_after',
 'maxexp_alchol_prod_before',
 'maxexp_alchol_prod_after',
 'maxexp_alcohol_part_before',
 'maxexp_alcohol_part_after',
 'maxexp_animal_testing_cosmetic_part_before',
 'maxexp_animal_testing_cosmetic_part_after',
 'maxexp_animal_testing_part_before',
 'maxexp_animal_testing_part_after',
 'maxexp_antip_landmines_part_before',
 'maxexp_antip_landmines_part_after',
 'maxexp_armament_part_before',
 'maxexp_armament_part_after',
 'maxexp_armament_prod_before',
 'maxexp_armament_prod_after',
 'maxexp_artic_oil_part_before',
 'maxexp_artic_oil_part_after',
 'maxexp_cannabis_part_before',
 'maxexp_cannabis_part_after',
 'maxexp_chemic_biolog_weapons_part_before',
 'maxexp_chemic_biolog_weapons_part_after',
 'maxexp_cluster_bombs_part_before',
 'maxexp_cluster_bombs_part_after',
 'maxexp_coal_mining_part_before',
 'maxexp_coal_mining_part_after',
 'maxexp_coal_mining_prod_before',
 'maxexp_coal_mining_prod_after',
 'maxexp_coal_power_gen_part_before',
 'maxexp_coal_power_gen_part_after',
 'maxexp_coal_power_gen_prod_before',
 'maxexp_coal_power_gen_prod_after',
 'maxexp_contraceptives_part_before',
 'maxexp_contraceptives_part_after',
 'maxexp_depleted_uranium_part_before',
 'maxexp_depleted_uranium_part_after',
 'maxexp_embryonic_stem_cell_research_part_before',
 'maxexp_embryonic_stem_cell_research_part_after',
 'maxexp_fossil_fuels_part_before',
 'maxexp_fossil_fuels_part_after',
 'maxexp_fossil_fuels_prod_before',
 'maxexp_fossil_fuels_prod_after',
 'maxexp_fur_exotic_leather_part_before',
 'maxexp_fur_exotic_leather_part_after',
 'maxexp_gambling_part_before',
 'maxexp_gambling_part_after',
 'maxexp_gambling_prod_before',
 'maxexp_gambling_prod_after',
 'maxexp_gmo_products_part_before',
 'maxexp_gmo_products_part_after',
 'maxexp_gmo_research_part_before',
 'maxexp_gmo_research_part_after',
 'maxexp_meat_products_part_before',
 'maxexp_meat_products_part_after',
 'maxexp_meat_products_prod_before',
 'maxexp_meat_products_prod_after',
 'maxexp_nuclear_energy_part_before',
 'maxexp_nuclear_energy_part_after',
 'maxexp_nuclear_energy_prod_before',
 'maxexp_nuclear_energy_prod_after',
 'maxexp_nuclear_weapons_part_before',
 'maxexp_nuclear_weapons_part_after',
 'maxexp_oil_sands_part_before',
 'maxexp_oil_sands_part_after',
 'maxexp_oil_sands_prod_before',
 'maxexp_oil_sands_prod_after',
 'maxexp_palm_oil_part_before',
 'maxexp_palm_oil_part_after',
 'maxexp_pork_products_part_before',
 'maxexp_pork_products_part_after',
 'maxexp_pork_products_prod_before',
 'maxexp_pork_products_prod_after',
 'maxexp_pornography_part_before',
 'maxexp_pornography_part_after',
 'maxexp_predatory_lending_part_before',
 'maxexp_predatory_lending_part_after',
 'maxexp_shale_energy_part_before',
 'maxexp_shale_energy_part_after',
 'maxexp_shale_energy_prod_before',
 'maxexp_shale_energy_prod_after',
 'maxexp_small_arms_part_before',
 'maxexp_small_arms_part_after',
 'maxexp_stem_cell_research_before',
 'maxexp_stem_cell_research_after',
 'maxexp_tobacco_part_before',
 'maxexp_tobacco_part_after',
 'maxexp_tobacco_prod_before',
 'maxexp_tobacco_prod_after',
 'maxexp_white_phosporus_part_before',
 'maxexp_white_phosporus_part_after']]

In [92]:

df_sorted.info()
df_sorted.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 96 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   permId                                           686 non-null    int64
 1   issuer_name                                      686 non-null    object
 2   maxexp_abortifacents_part_before                 686 non-null    object
 3   maxexp_abortifacents_part_after                  686 non-null    object
 4   maxexp_agrochemical_products_part_before         686 non-null    object
 5   maxexp_agrochemical_products_part_after          686 non-null    object
 6   maxexp_agrochemical_products_prod_before         686 non-null    object
 7   maxexp_agrochemical_products_prod_after          686 non-null    object
 8   maxexp_alchol_prod_before                        686 non-null    object
 9   maxexp_alchol_prod_after                         686 non-null    object
 10  maxexp_alcohol_part_before                       686 non-null    object
 11  maxexp_alcohol_part_after                        686 non-null    object
 12  maxexp_animal_testing_cosmetic_part_before       686 non-null    object
 13  maxexp_animal_testing_cosmetic_part_after        686 non-null    object
 14  maxexp_animal_testing_part_before                686 non-null    object
 15  maxexp_animal_testing_part_after                 686 non-null    object
 16  maxexp_antip_landmines_part_before               686 non-null    object
 17  maxexp_antip_landmines_part_after                686 non-null    object
 18  maxexp_armament_part_before                      686 non-null    object
 19  maxexp_armament_part_after                       686 non-null    object
 20  maxexp_armament_prod_before                      686 non-null    object
 21  maxexp_armament_prod_after                       686 non-null    object
 22  maxexp_artic_oil_part_before                     686 non-null    object
 23  maxexp_artic_oil_part_after                      686 non-null    object
 24  maxexp_cannabis_part_before                      686 non-null    object
 25  maxexp_cannabis_part_after                       686 non-null    object
 26  maxexp_chemic_biolog_weapons_part_before         686 non-null    object
 27  maxexp_chemic_biolog_weapons_part_after          686 non-null    object
 28  maxexp_cluster_bombs_part_before                 686 non-null    object
 29  maxexp_cluster_bombs_part_after                  686 non-null    object
 30  maxexp_coal_mining_part_before                   686 non-null    object
 31  maxexp_coal_mining_part_after                    686 non-null    object
 32  maxexp_coal_mining_prod_before                   686 non-null    object
 33  maxexp_coal_mining_prod_after                    686 non-null    object
 34  maxexp_coal_power_gen_part_before                686 non-null    object
 35  maxexp_coal_power_gen_part_after                 686 non-null    object
 36  maxexp_coal_power_gen_prod_before                686 non-null    object
 37  maxexp_coal_power_gen_prod_after                 686 non-null    object
 38  maxexp_contraceptives_part_before                686 non-null    object
 39  maxexp_contraceptives_part_after                 686 non-null    object
 40  maxexp_depleted_uranium_part_before              686 non-null    int64
 41  maxexp_depleted_uranium_part_after               686 non-null    int64
 42  maxexp_embryonic_stem_cell_research_part_before  686 non-null    object
 43  maxexp_embryonic_stem_cell_research_part_after   686 non-null    object
 44  maxexp_fossil_fuels_part_before                  686 non-null    object
 45  maxexp_fossil_fuels_part_after                   686 non-null    object
 46  maxexp_fossil_fuels_prod_before                  686 non-null    object
 47  maxexp_fossil_fuels_prod_after                   686 non-null    object
 48  maxexp_fur_exotic_leather_part_before            686 non-null    object
 49  maxexp_fur_exotic_leather_part_after             686 non-null    object
 50  maxexp_gambling_part_before                      686 non-null    object
 51  maxexp_gambling_part_after                       686 non-null    object
 52  maxexp_gambling_prod_before                      686 non-null    object
 53  maxexp_gambling_prod_after                       686 non-null    object
 54  maxexp_gmo_products_part_before                  686 non-null    object
 55  maxexp_gmo_products_part_after                   686 non-null    object
 56  maxexp_gmo_research_part_before                  686 non-null    object
 57  maxexp_gmo_research_part_after                   686 non-null    object
 58  maxexp_meat_products_part_before                 686 non-null    object
 59  maxexp_meat_products_part_after                  686 non-null    object
 60  maxexp_meat_products_prod_before                 686 non-null    object
 61  maxexp_meat_products_prod_after                  686 non-null    object
 62  maxexp_nuclear_energy_part_before                686 non-null    object
 63  maxexp_nuclear_energy_part_after                 686 non-null    object
 64  maxexp_nuclear_energy_prod_before                686 non-null    object
 65  maxexp_nuclear_energy_prod_after                 686 non-null    object
 66  maxexp_nuclear_weapons_part_before               686 non-null    object
 67  maxexp_nuclear_weapons_part_after                686 non-null    object
 68  maxexp_oil_sands_part_before                     686 non-null    object
 69  maxexp_oil_sands_part_after                      686 non-null    object
 70  maxexp_oil_sands_prod_before                     686 non-null    object
 71  maxexp_oil_sands_prod_after                      686 non-null    object
 72  maxexp_palm_oil_part_before                      686 non-null    object
 73  maxexp_palm_oil_part_after                       686 non-null    object
 74  maxexp_pork_products_part_before                 686 non-null    object
 75  maxexp_pork_products_part_after                  686 non-null    object
 76  maxexp_pork_products_prod_before                 686 non-null    object
 77  maxexp_pork_products_prod_after                  686 non-null    object
 78  maxexp_pornography_part_before                   686 non-null    object
 79  maxexp_pornography_part_after                    686 non-null    object
 80  maxexp_predatory_lending_part_before             686 non-null    object
 81  maxexp_predatory_lending_part_after              686 non-null    object
 82  maxexp_shale_energy_part_before                  686 non-null    object
 83  maxexp_shale_energy_part_after                   686 non-null    object
 84  maxexp_shale_energy_prod_before                  686 non-null    object
 85  maxexp_shale_energy_prod_after                   686 non-null    object
 86  maxexp_small_arms_part_before                    686 non-null    object
 87  maxexp_small_arms_part_after                     686 non-null    object
 88  maxexp_stem_cell_research_before                 686 non-null    object
 89  maxexp_stem_cell_research_after                  686 non-null    object
 90  maxexp_tobacco_part_before                       686 non-null    object
 91  maxexp_tobacco_part_after                        686 non-null    object
 92  maxexp_tobacco_prod_before                       686 non-null    object
 93  maxexp_tobacco_prod_after                        686 non-null    object
 94  maxexp_white_phosporus_part_before               686 non-null    object
 95  maxexp_white_phosporus_part_after                686 non-null    object
dtypes: int64(3), object(93)
memory usage: 519.9+ KB

,permId,issuer_name,maxexp_abortifacents_part_before,maxexp_abortifacents_part_after,maxexp_agrochemical_products_part_before,maxexp_agrochemical_products_part_after,maxexp_agrochemical_products_prod_before,maxexp_agrochemical_products_prod_after,maxexp_alchol_prod_before,maxexp_alchol_prod_after,...,maxexp_small_arms_part_before,maxexp_small_arms_part_after,maxexp_stem_cell_research_before,maxexp_stem_cell_research_after,maxexp_tobacco_part_before,maxexp_tobacco_part_after,maxexp_tobacco_prod_before,maxexp_tobacco_prod_after,maxexp_white_phosporus_part_before,maxexp_white_phosporus_part_after
0,8589934570,International Bank for Reconstruction and Deve...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4298009762,Cooperatieve Rabobank UA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4295903360,General Motors Financial Company Inc,0.0,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
3,5000001007,Sumitomo Mitsui Banking Corp,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0
4,8589934159,European Investment Bank,0.0,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [93]:
#Convertir a int
df_sorted.iloc[:,2:] = df_sorted.iloc[:,2:].astype('float')

In [94]:
df_sorted.iloc[:,2:] = df_sorted.iloc[:,2:].astype('int64')
df_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 96 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   permId                                           686 non-null    int64
 1   issuer_name                                      686 non-null    object
 2   maxexp_abortifacents_part_before                 686 non-null    int64
 3   maxexp_abortifacents_part_after                  686 non-null    int64
 4   maxexp_agrochemical_products_part_before         686 non-null    int64
 5   maxexp_agrochemical_products_part_after          686 non-null    int64
 6   maxexp_agrochemical_products_prod_before         686 non-null    int64
 7   maxexp_agrochemical_products_prod_after          686 non-null    int64
 8   maxexp_alchol_prod_before                        686 non-null    int64
 9   maxexp_alchol_prod_after                         686 non-null    int64
 10  maxexp_alcohol_part_before                       686 non-null    int64
 11  maxexp_alcohol_part_after                        686 non-null    int64
 12  maxexp_animal_testing_cosmetic_part_before       686 non-null    int64
 13  maxexp_animal_testing_cosmetic_part_after        686 non-null    int64
 14  maxexp_animal_testing_part_before                686 non-null    int64
 15  maxexp_animal_testing_part_after                 686 non-null    int64
 16  maxexp_antip_landmines_part_before               686 non-null    int64
 17  maxexp_antip_landmines_part_after                686 non-null    int64
 18  maxexp_armament_part_before                      686 non-null    int64
 19  maxexp_armament_part_after                       686 non-null    int64
 20  maxexp_armament_prod_before                      686 non-null    int64
 21  maxexp_armament_prod_after                       686 non-null    int64
 22  maxexp_artic_oil_part_before                     686 non-null    int64
 23  maxexp_artic_oil_part_after                      686 non-null    int64
 24  maxexp_cannabis_part_before                      686 non-null    int64
 25  maxexp_cannabis_part_after                       686 non-null    int64
 26  maxexp_chemic_biolog_weapons_part_before         686 non-null    int64
 27  maxexp_chemic_biolog_weapons_part_after          686 non-null    int64
 28  maxexp_cluster_bombs_part_before                 686 non-null    int64
 29  maxexp_cluster_bombs_part_after                  686 non-null    int64
 30  maxexp_coal_mining_part_before                   686 non-null    int64
 31  maxexp_coal_mining_part_after                    686 non-null    int64
 32  maxexp_coal_mining_prod_before                   686 non-null    int64
 33  maxexp_coal_mining_prod_after                    686 non-null    int64
 34  maxexp_coal_power_gen_part_before                686 non-null    int64
 35  maxexp_coal_power_gen_part_after                 686 non-null    int64
 36  maxexp_coal_power_gen_prod_before                686 non-null    int64
 37  maxexp_coal_power_gen_prod_after                 686 non-null    int64
 38  maxexp_contraceptives_part_before                686 non-null    int64
 39  maxexp_contraceptives_part_after                 686 non-null    int64
 40  maxexp_depleted_uranium_part_before              686 non-null    int64
 41  maxexp_depleted_uranium_part_after               686 non-null    int64
 42  maxexp_embryonic_stem_cell_research_part_before  686 non-null    int64
 43  maxexp_embryonic_stem_cell_research_part_after   686 non-null    int64
 44  maxexp_fossil_fuels_part_before                  686 non-null    int64
 45  maxexp_fossil_fuels_part_after                   686 non-null    int64
 46  maxexp_fossil_fuels_prod_before                  686 non-null    int64
 47  maxexp_fossil_fuels_prod_after                   686 non-null    int64
 48  maxexp_fur_exotic_leather_part_before            686 non-null    int64
 49  maxexp_fur_exotic_leather_part_after             686 non-null    int64
 50  maxexp_gambling_part_before                      686 non-null    int64
 51  maxexp_gambling_part_after                       686 non-null    int64
 52  maxexp_gambling_prod_before                      686 non-null    int64
 53  maxexp_gambling_prod_after                       686 non-null    int64
 54  maxexp_gmo_products_part_before                  686 non-null    int64
 55  maxexp_gmo_products_part_after                   686 non-null    int64
 56  maxexp_gmo_research_part_before                  686 non-null    int64
 57  maxexp_gmo_research_part_after                   686 non-null    int64
 58  maxexp_meat_products_part_before                 686 non-null    int64
 59  maxexp_meat_products_part_after                  686 non-null    int64
 60  maxexp_meat_products_prod_before                 686 non-null    int64
 61  maxexp_meat_products_prod_after                  686 non-null    int64
 62  maxexp_nuclear_energy_part_before                686 non-null    int64
 63  maxexp_nuclear_energy_part_after                 686 non-null    int64
 64  maxexp_nuclear_energy_prod_before                686 non-null    int64
 65  maxexp_nuclear_energy_prod_after                 686 non-null    int64
 66  maxexp_nuclear_weapons_part_before               686 non-null    int64
 67  maxexp_nuclear_weapons_part_after                686 non-null    int64
 68  maxexp_oil_sands_part_before                     686 non-null    int64
 69  maxexp_oil_sands_part_after                      686 non-null    int64
 70  maxexp_oil_sands_prod_before                     686 non-null    int64
 71  maxexp_oil_sands_prod_after                      686 non-null    int64
 72  maxexp_palm_oil_part_before                      686 non-null    int64
 73  maxexp_palm_oil_part_after                       686 non-null    int64
 74  maxexp_pork_products_part_before                 686 non-null    int64
 75  maxexp_pork_products_part_after                  686 non-null    int64
 76  maxexp_pork_products_prod_before                 686 non-null    int64
 77  maxexp_pork_products_prod_after                  686 non-null    int64
 78  maxexp_pornography_part_before                   686 non-null    int64
 79  maxexp_pornography_part_after                    686 non-null    int64
 80  maxexp_predatory_lending_part_before             686 non-null    int64
 81  maxexp_predatory_lending_part_after              686 non-null    int64
 82  maxexp_shale_energy_part_before                  686 non-null    int64
 83  maxexp_shale_energy_part_after                   686 non-null    int64
 84  maxexp_shale_energy_prod_before                  686 non-null    int64
 85  maxexp_shale_energy_prod_after                   686 non-null    int64
 86  maxexp_small_arms_part_before                    686 non-null    int64
 87  maxexp_small_arms_part_after                     686 non-null    int64
 88  maxexp_stem_cell_research_before                 686 non-null    int64
 89  maxexp_stem_cell_research_after                  686 non-null    int64
 90  maxexp_tobacco_part_before                       686 non-null    int64
 91  maxexp_tobacco_part_after                        686 non-null    int64
 92  maxexp_tobacco_prod_before                       686 non-null    int64
 93  maxexp_tobacco_prod_after                        686 non-null    int64
 94  maxexp_white_phosporus_part_before               686 non-null    int64
 95  maxexp_white_phosporus_part_after                686 non-null    int64
dtypes: int64(95), object(1)
memory usage: 519.9+ KB

In [95]:
df_sorted.head()

,permId,issuer_name,maxexp_abortifacents_part_before,maxexp_abortifacents_part_after,maxexp_agrochemical_products_part_before,maxexp_agrochemical_products_part_after,maxexp_agrochemical_products_prod_before,maxexp_agrochemical_products_prod_after,maxexp_alchol_prod_before,maxexp_alchol_prod_after,...,maxexp_small_arms_part_before,maxexp_small_arms_part_after,maxexp_stem_cell_research_before,maxexp_stem_cell_research_after,maxexp_tobacco_part_before,maxexp_tobacco_part_after,maxexp_tobacco_prod_before,maxexp_tobacco_prod_after,maxexp_white_phosporus_part_before,maxexp_white_phosporus_part_after
0,8589934570,International Bank for Reconstruction and Deve...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4298009762,Cooperatieve Rabobank UA,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4295903360,General Motors Financial Company Inc,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5000001007,Sumitomo Mitsui Banking Corp,0,0,0,0,0,0,0,0,...,0,0,0,0,5,5,0,0,0,0
4,8589934159,European Investment Bank,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [96]:
# Filtro
cols = df_sorted.filter(regex='_before$').columns

#función para generar "Variation_" 
def generate_variation_col(col):
    col_name = col.rpartition("_")[0]
    before_col = col.replace("_before", "_after")
    verification_col = "Variation_" + col_name
    bool_series = df_sorted[col].ne(df_sorted[before_col])
    return verification_col, bool_series

# Comprobación
for col in cols:
    verification_col, bool_series = generate_variation_col(col)
    df_sorted.insert(df_sorted.columns.get_loc(col), verification_col, bool_series)

In [97]:
df_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Columns: 143 entries, permId to maxexp_white_phosporus_part_after
dtypes: bool(47), int64(95), object(1)
memory usage: 551.3+ KB

In [98]:
df_sorted.head()

,permId,issuer_name,Variation_maxexp_abortifacents_part,maxexp_abortifacents_part_before,maxexp_abortifacents_part_after,Variation_maxexp_agrochemical_products_part,maxexp_agrochemical_products_part_before,maxexp_agrochemical_products_part_after,Variation_maxexp_agrochemical_products_prod,maxexp_agrochemical_products_prod_before,...,maxexp_stem_cell_research_after,Variation_maxexp_tobacco_part,maxexp_tobacco_part_before,maxexp_tobacco_part_after,Variation_maxexp_tobacco_prod,maxexp_tobacco_prod_before,maxexp_tobacco_prod_after,Variation_maxexp_white_phosporus_part,maxexp_white_phosporus_part_before,maxexp_white_phosporus_part_after
0,8589934570,International Bank for Reconstruction and Deve...,False,0,0,False,0,0,False,0,...,0,False,0,0,False,0,0,False,0,0
1,4298009762,Cooperatieve Rabobank UA,False,0,0,False,0,0,False,0,...,0,False,0,0,False,0,0,False,0,0
2,4295903360,General Motors Financial Company Inc,False,0,0,False,0,0,False,0,...,0,False,0,0,False,0,0,False,0,0
3,5000001007,Sumitomo Mitsui Banking Corp,False,0,0,False,0,0,False,0,...,0,False,5,5,False,0,0,False,0,0
4,8589934159,European Investment Bank,False,0,0,False,0,0,False,0,...,0,False,0,0,False,0,0,False,0,0

In [99]:
pd.Series(df_sorted.Variation_maxexp_abortifacents_part).value_counts()

False    686
Name: Variation_maxexp_abortifacents_part, dtype: int64

In [100]:
Variation_Max_Expo = df_sorted.copy() #todas las max exp y su col de variación

In [101]:
variation_cols = [col for col in Variation_Max_Expo.columns if col.startswith("Variation_")]

# Creacion
Variation_Max_Expo["Max_Expo_Variation"] = Variation_Max_Expo[variation_cols].any(axis=1)

In [102]:
Variation_Max_Expo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Columns: 144 entries, permId to Max_Expo_Variation
dtypes: bool(48), int64(95), object(1)
memory usage: 552.0+ KB

In [103]:
Variation_Max_Expo.head()

,permId,issuer_name,Variation_maxexp_abortifacents_part,maxexp_abortifacents_part_before,maxexp_abortifacents_part_after,Variation_maxexp_agrochemical_products_part,maxexp_agrochemical_products_part_before,maxexp_agrochemical_products_part_after,Variation_maxexp_agrochemical_products_prod,maxexp_agrochemical_products_prod_before,...,Variation_maxexp_tobacco_part,maxexp_tobacco_part_before,maxexp_tobacco_part_after,Variation_maxexp_tobacco_prod,maxexp_tobacco_prod_before,maxexp_tobacco_prod_after,Variation_maxexp_white_phosporus_part,maxexp_white_phosporus_part_before,maxexp_white_phosporus_part_after,Max_Expo_Variation
0,8589934570,International Bank for Reconstruction and Deve...,False,0,0,False,0,0,False,0,...,False,0,0,False,0,0,False,0,0,False
1,4298009762,Cooperatieve Rabobank UA,False,0,0,False,0,0,False,0,...,False,0,0,False,0,0,False,0,0,False
2,4295903360,General Motors Financial Company Inc,False,0,0,False,0,0,False,0,...,False,0,0,False,0,0,False,0,0,False
3,5000001007,Sumitomo Mitsui Banking Corp,False,0,0,False,0,0,False,0,...,False,5,5,False,0,0,False,0,0,False
4,8589934159,European Investment Bank,False,0,0,False,0,0,False,0,...,False,0,0,False,0,0,False,0,0,False

In [104]:
pd.Series(Variation_Max_Expo.Max_Expo_Variation).value_counts()

False    679
True       7
Name: Max_Expo_Variation, dtype: int64

In [105]:
#Obtener resultado ordenado, vista de variaciones como principios
column_order_e = ['permId','issuer_name', 'Max_Expo_Variation']
variation_columns_e = [col for col in Variation_Max_Expo.columns if col.startswith('Variation_')]
other_columns_e =sorted(set(Variation_Max_Expo.columns)- set(column_order_e) - set(variation_columns_e))
n_df_e = Variation_Max_Expo[column_order_e + variation_columns_e + other_columns_e]

In [106]:
nombres_columnas_n_df_e = n_df_e.columns.tolist()
nombres_columnas_n_df_e

['permId',
 'issuer_name',
 'Max_Expo_Variation',
 'Variation_maxexp_abortifacents_part',
 'Variation_maxexp_agrochemical_products_part',
 'Variation_maxexp_agrochemical_products_prod',
 'Variation_maxexp_alchol_prod',
 'Variation_maxexp_alcohol_part',
 'Variation_maxexp_animal_testing_cosmetic_part',
 'Variation_maxexp_animal_testing_part',
 'Variation_maxexp_antip_landmines_part',
 'Variation_maxexp_armament_part',
 'Variation_maxexp_armament_prod',
 'Variation_maxexp_artic_oil_part',
 'Variation_maxexp_cannabis_part',
 'Variation_maxexp_chemic_biolog_weapons_part',
 'Variation_maxexp_cluster_bombs_part',
 'Variation_maxexp_coal_mining_part',
 'Variation_maxexp_coal_mining_prod',
 'Variation_maxexp_coal_power_gen_part',
 'Variation_maxexp_coal_power_gen_prod',
 'Variation_maxexp_contraceptives_part',
 'Variation_maxexp_depleted_uranium_part',
 'Variation_maxexp_embryonic_stem_cell_research_part',
 'Variation_maxexp_fossil_fuels_part',
 'Variation_maxexp_fossil_fuels_prod',
 'Variation_maxexp_fur_exotic_leather_part',
 'Variation_maxexp_gambling_part',
 'Variation_maxexp_gambling_prod',
 'Variation_maxexp_gmo_products_part',
 'Variation_maxexp_gmo_research_part',
 'Variation_maxexp_meat_products_part',
 'Variation_maxexp_meat_products_prod',
 'Variation_maxexp_nuclear_energy_part',
 'Variation_maxexp_nuclear_energy_prod',
 'Variation_maxexp_nuclear_weapons_part',
 'Variation_maxexp_oil_sands_part',
 'Variation_maxexp_oil_sands_prod',
 'Variation_maxexp_palm_oil_part',
 'Variation_maxexp_pork_products_part',
 'Variation_maxexp_pork_products_prod',
 'Variation_maxexp_pornography_part',
 'Variation_maxexp_predatory_lending_part',
 'Variation_maxexp_shale_energy_part',
 'Variation_maxexp_shale_energy_prod',
 'Variation_maxexp_small_arms_part',
 'Variation_maxexp_stem_cell_research',
 'Variation_maxexp_tobacco_part',
 'Variation_maxexp_tobacco_prod',
 'Variation_maxexp_white_phosporus_part',
 'maxexp_abortifacents_part_after',
 'maxexp_abortifacents_part_before',
 'maxexp_agrochemical_products_part_after',
 'maxexp_agrochemical_products_part_before',
 'maxexp_agrochemical_products_prod_after',
 'maxexp_agrochemical_products_prod_before',
 'maxexp_alchol_prod_after',
 'maxexp_alchol_prod_before',
 'maxexp_alcohol_part_after',
 'maxexp_alcohol_part_before',
 'maxexp_animal_testing_cosmetic_part_after',
 'maxexp_animal_testing_cosmetic_part_before',
 'maxexp_animal_testing_part_after',
 'maxexp_animal_testing_part_before',
 'maxexp_antip_landmines_part_after',
 'maxexp_antip_landmines_part_before',
 'maxexp_armament_part_after',
 'maxexp_armament_part_before',
 'maxexp_armament_prod_after',
 'maxexp_armament_prod_before',
 'maxexp_artic_oil_part_after',
 'maxexp_artic_oil_part_before',
 'maxexp_cannabis_part_after',
 'maxexp_cannabis_part_before',
 'maxexp_chemic_biolog_weapons_part_after',
 'maxexp_chemic_biolog_weapons_part_before',
 'maxexp_cluster_bombs_part_after',
 'maxexp_cluster_bombs_part_before',
 'maxexp_coal_mining_part_after',
 'maxexp_coal_mining_part_before',
 'maxexp_coal_mining_prod_after',
 'maxexp_coal_mining_prod_before',
 'maxexp_coal_power_gen_part_after',
 'maxexp_coal_power_gen_part_before',
 'maxexp_coal_power_gen_prod_after',
 'maxexp_coal_power_gen_prod_before',
 'maxexp_contraceptives_part_after',
 'maxexp_contraceptives_part_before',
 'maxexp_depleted_uranium_part_after',
 'maxexp_depleted_uranium_part_before',
 'maxexp_embryonic_stem_cell_research_part_after',
 'maxexp_embryonic_stem_cell_research_part_before',
 'maxexp_fossil_fuels_part_after',
 'maxexp_fossil_fuels_part_before',
 'maxexp_fossil_fuels_prod_after',
 'maxexp_fossil_fuels_prod_before',
 'maxexp_fur_exotic_leather_part_after',
 'maxexp_fur_exotic_leather_part_before',
 'maxexp_gambling_part_after',
 'maxexp_gambling_part_before',
 'maxexp_gambling_prod_after',
 'maxexp_gambling_prod_before',
 'maxexp_gmo_products_part_after',
 'maxexp_gmo_products_part_before',
 'maxexp_gmo_research_part_after',
 'maxexp_gmo_research_part_before',
 'maxexp_meat_products_part_after',
 'maxexp_meat_products_part_before',
 'maxexp_meat_products_prod_after',
 'maxexp_meat_products_prod_before',
 'maxexp_nuclear_energy_part_after',
 'maxexp_nuclear_energy_part_before',
 'maxexp_nuclear_energy_prod_after',
 'maxexp_nuclear_energy_prod_before',
 'maxexp_nuclear_weapons_part_after',
 'maxexp_nuclear_weapons_part_before',
 'maxexp_oil_sands_part_after',
 'maxexp_oil_sands_part_before',
 'maxexp_oil_sands_prod_after',
 'maxexp_oil_sands_prod_before',
 'maxexp_palm_oil_part_after',
 'maxexp_palm_oil_part_before',
 'maxexp_pork_products_part_after',
 'maxexp_pork_products_part_before',
 'maxexp_pork_products_prod_after',
 'maxexp_pork_products_prod_before',
 'maxexp_pornography_part_after',
 'maxexp_pornography_part_before',
 'maxexp_predatory_lending_part_after',
 'maxexp_predatory_lending_part_before',
 'maxexp_shale_energy_part_after',
 'maxexp_shale_energy_part_before',
 'maxexp_shale_energy_prod_after',
 'maxexp_shale_energy_prod_before',
 'maxexp_small_arms_part_after',
 'maxexp_small_arms_part_before',
 'maxexp_stem_cell_research_after',
 'maxexp_stem_cell_research_before',
 'maxexp_tobacco_part_after',
 'maxexp_tobacco_part_before',
 'maxexp_tobacco_prod_after',
 'maxexp_tobacco_prod_before',
 'maxexp_white_phosporus_part_after',
 'maxexp_white_phosporus_part_before']

In [107]:
n_df_e= n_df_e[['permId',
 'issuer_name',
 'Max_Expo_Variation',
 'Variation_maxexp_abortifacents_part',
 'Variation_maxexp_agrochemical_products_part',
 'Variation_maxexp_agrochemical_products_prod',
 'Variation_maxexp_alchol_prod',
 'Variation_maxexp_alcohol_part',
 'Variation_maxexp_animal_testing_cosmetic_part',
 'Variation_maxexp_animal_testing_part',
 'Variation_maxexp_antip_landmines_part',
 'Variation_maxexp_armament_part',
 'Variation_maxexp_armament_prod',
 'Variation_maxexp_artic_oil_part',
 'Variation_maxexp_cannabis_part',
 'Variation_maxexp_chemic_biolog_weapons_part',
 'Variation_maxexp_cluster_bombs_part',
 'Variation_maxexp_coal_mining_part',
 'Variation_maxexp_coal_mining_prod',
 'Variation_maxexp_coal_power_gen_part',
 'Variation_maxexp_coal_power_gen_prod',
 'Variation_maxexp_contraceptives_part',
 'Variation_maxexp_depleted_uranium_part',
 'Variation_maxexp_embryonic_stem_cell_research_part',
 'Variation_maxexp_fossil_fuels_part',
 'Variation_maxexp_fossil_fuels_prod',
 'Variation_maxexp_fur_exotic_leather_part',
 'Variation_maxexp_gambling_part',
 'Variation_maxexp_gambling_prod',
 'Variation_maxexp_gmo_products_part',
 'Variation_maxexp_gmo_research_part',
 'Variation_maxexp_meat_products_part',
 'Variation_maxexp_meat_products_prod',
 'Variation_maxexp_nuclear_energy_part',
 'Variation_maxexp_nuclear_energy_prod',
 'Variation_maxexp_nuclear_weapons_part',
 'Variation_maxexp_oil_sands_part',
 'Variation_maxexp_oil_sands_prod',
 'Variation_maxexp_palm_oil_part',
 'Variation_maxexp_pork_products_part',
 'Variation_maxexp_pork_products_prod',
 'Variation_maxexp_pornography_part',
 'Variation_maxexp_predatory_lending_part',
 'Variation_maxexp_shale_energy_part',
 'Variation_maxexp_shale_energy_prod',
 'Variation_maxexp_small_arms_part',
 'Variation_maxexp_stem_cell_research',
 'Variation_maxexp_tobacco_part',
 'Variation_maxexp_tobacco_prod',
 'Variation_maxexp_white_phosporus_part',
 'maxexp_abortifacents_part_before',
 'maxexp_abortifacents_part_after',
 'maxexp_agrochemical_products_part_before',
 'maxexp_agrochemical_products_part_after',
 'maxexp_agrochemical_products_prod_before',
 'maxexp_agrochemical_products_prod_after',
 'maxexp_alchol_prod_before',
 'maxexp_alchol_prod_after',
 'maxexp_alcohol_part_before',
 'maxexp_alcohol_part_after',
 'maxexp_animal_testing_cosmetic_part_before',
 'maxexp_animal_testing_cosmetic_part_after',
 'maxexp_animal_testing_part_before',
 'maxexp_animal_testing_part_after',
 'maxexp_antip_landmines_part_before',
 'maxexp_antip_landmines_part_after',
 'maxexp_armament_part_before',
 'maxexp_armament_part_after',
 'maxexp_armament_prod_before',
 'maxexp_armament_prod_after',
 'maxexp_artic_oil_part_before',
 'maxexp_artic_oil_part_after',
 'maxexp_cannabis_part_before',
 'maxexp_cannabis_part_after',
 'maxexp_chemic_biolog_weapons_part_before',
 'maxexp_chemic_biolog_weapons_part_after',
 'maxexp_cluster_bombs_part_before',
 'maxexp_cluster_bombs_part_after',
 'maxexp_coal_mining_part_before',
 'maxexp_coal_mining_part_after',
 'maxexp_coal_mining_prod_before',
 'maxexp_coal_mining_prod_after',
 'maxexp_coal_power_gen_part_before',
 'maxexp_coal_power_gen_part_after',
 'maxexp_coal_power_gen_prod_before',
 'maxexp_coal_power_gen_prod_after',
 'maxexp_contraceptives_part_before',
 'maxexp_contraceptives_part_after',
 'maxexp_depleted_uranium_part_before',
 'maxexp_depleted_uranium_part_after',
 'maxexp_embryonic_stem_cell_research_part_before',
 'maxexp_embryonic_stem_cell_research_part_after',
 'maxexp_fossil_fuels_part_before',
 'maxexp_fossil_fuels_part_after',
 'maxexp_fossil_fuels_prod_before',
 'maxexp_fossil_fuels_prod_after',
 'maxexp_fur_exotic_leather_part_before',
 'maxexp_fur_exotic_leather_part_after',
 'maxexp_gambling_part_before',
 'maxexp_gambling_part_after',
 'maxexp_gambling_prod_before',
 'maxexp_gambling_prod_after',
 'maxexp_gmo_products_part_before',
 'maxexp_gmo_products_part_after',
 'maxexp_gmo_research_part_before',
 'maxexp_gmo_research_part_after',
 'maxexp_meat_products_part_before',
 'maxexp_meat_products_part_after',
 'maxexp_meat_products_prod_before',
 'maxexp_meat_products_prod_after',
 'maxexp_nuclear_energy_part_before',
 'maxexp_nuclear_energy_part_after',
 'maxexp_nuclear_energy_prod_before',
 'maxexp_nuclear_energy_prod_after',
 'maxexp_nuclear_weapons_part_before',
 'maxexp_nuclear_weapons_part_after',
 'maxexp_oil_sands_part_before',
 'maxexp_oil_sands_part_after',
 'maxexp_oil_sands_prod_before',
 'maxexp_oil_sands_prod_after',
 'maxexp_palm_oil_part_before',
 'maxexp_palm_oil_part_after',
 'maxexp_pork_products_part_before',
 'maxexp_pork_products_part_after',
 'maxexp_pork_products_prod_before',
 'maxexp_pork_products_prod_after',
 'maxexp_pornography_part_before',
 'maxexp_pornography_part_after',
 'maxexp_predatory_lending_part_before',
 'maxexp_predatory_lending_part_after',
 'maxexp_shale_energy_part_before',
 'maxexp_shale_energy_part_after',
 'maxexp_shale_energy_prod_before',
 'maxexp_shale_energy_prod_after',
 'maxexp_small_arms_part_before',
 'maxexp_small_arms_part_after',
 'maxexp_stem_cell_research_before',
 'maxexp_stem_cell_research_after',
 'maxexp_tobacco_part_before',
 'maxexp_tobacco_part_after',
 'maxexp_tobacco_prod_before',
 'maxexp_tobacco_prod_after',
 'maxexp_white_phosporus_part_before',
 'maxexp_white_phosporus_part_after']]

In [108]:
#vista
n_df_e.head()

,permId,issuer_name,Max_Expo_Variation,Variation_maxexp_abortifacents_part,Variation_maxexp_agrochemical_products_part,Variation_maxexp_agrochemical_products_prod,Variation_maxexp_alchol_prod,Variation_maxexp_alcohol_part,Variation_maxexp_animal_testing_cosmetic_part,Variation_maxexp_animal_testing_part,...,maxexp_small_arms_part_before,maxexp_small_arms_part_after,maxexp_stem_cell_research_before,maxexp_stem_cell_research_after,maxexp_tobacco_part_before,maxexp_tobacco_part_after,maxexp_tobacco_prod_before,maxexp_tobacco_prod_after,maxexp_white_phosporus_part_before,maxexp_white_phosporus_part_after
0,8589934570,International Bank for Reconstruction and Deve...,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,0
1,4298009762,Cooperatieve Rabobank UA,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,0
2,4295903360,General Motors Financial Company Inc,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,0
3,5000001007,Sumitomo Mitsui Banking Corp,False,False,False,False,False,False,False,False,...,0,0,0,0,5,5,0,0,0,0
4,8589934159,European Investment Bank,False,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,0

In [109]:
#comprobar los resultados de cambio
Exp_True=n_df_e
in_True_Ex= Exp_True['Max_Expo_Variation']==True
Exp_True= Exp_True[in_True_Ex]
Exp_True.head()

,permId,issuer_name,Max_Expo_Variation,Variation_maxexp_abortifacents_part,Variation_maxexp_agrochemical_products_part,Variation_maxexp_agrochemical_products_prod,Variation_maxexp_alchol_prod,Variation_maxexp_alcohol_part,Variation_maxexp_animal_testing_cosmetic_part,Variation_maxexp_animal_testing_part,...,maxexp_small_arms_part_before,maxexp_small_arms_part_after,maxexp_stem_cell_research_before,maxexp_stem_cell_research_after,maxexp_tobacco_part_before,maxexp_tobacco_part_after,maxexp_tobacco_prod_before,maxexp_tobacco_prod_after,maxexp_white_phosporus_part_before,maxexp_white_phosporus_part_after
17,4295884692,Heineken NV,True,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
126,4297475585,Shell International Finance BV,True,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
170,4297665422,Schlumberger Finance BV,True,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,0
178,4295866751,Carrefour SA,True,False,False,False,False,False,False,False,...,0,0,0,0,5,5,0,0,0,0
392,4295889502,Enagas SA,True,False,False,False,False,False,False,False,...,0,0,0,0,0,0,0,0,0,0

In [110]:
Exp_True.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7 entries, 17 to 537
Columns: 144 entries, permId to maxexp_white_phosporus_part_after
dtypes: bool(48), int64(95), object(1)
memory usage: 5.6+ KB

In [111]:
pd.Series(Exp_True.Max_Expo_Variation).value_counts()

True    7
Name: Max_Expo_Variation, dtype: int64

In [112]:
#Solo columna final 
V_Max_Expo = Variation_Max_Expo[['permId','issuer_name', 'Max_Expo_Variation']]
V_Max_Expo.head()
V_Max_Expo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   permId              686 non-null    int64
 1   issuer_name         686 non-null    object
 2   Max_Expo_Variation  686 non-null    bool
dtypes: bool(1), int64(1), object(1)
memory usage: 16.7+ KB

In [113]:
pd.Series(V_Max_Expo.Max_Expo_Variation).value_counts()

False    679
True       7
Name: Max_Expo_Variation, dtype: int64

## CONTROVERSIAS

#### Nota: Si se agregan nuevas controversias before y after, se deben agregar , actual 39 controv.

In [114]:
Controv_before = DF_before_filtered.loc[:, ['issuer_name','permId','controv_access_to_basic_services','controv_accounting_and_taxation','controv_animal_welfare','controv_animal_welfare_sc','controv_anticompetitive_practices',
'controv_bribery_and_corruption','controv_bribery_and_corruption_sc','controv_business_ethics','controv_business_ethics_sc','controv_carbon_impact_of_products',
'controv_community_relations','controv_community_relations_sc','controv_corporate_governance','controv_data_privacy_and_security',
'controv_emissions_effluents_and_waste','controv_emissions_effluents_and_waste_sc','controv_employees_human_rights',
'controv_employees_human_rights_sc','controv_energy_use_and_ghg_emissions','controv_energy_use_and_ghg_emissions_sc',
'controv_environmental_impact_of_products','controv_intellectual_property','controv_labour_relations','controv_labour_relations_sc',
'controv_land_use_and_biodiversity','controv_land_use_and_biodiversity_sc','controv_lobbying_and_public_policy','controv_marketing_practices',
'controv_media_ethics','controv_occupational_health_and_safety','controv_occupational_health_and_safety_sc','controv_quality_and_safety',
'controv_sanctions','controv_social_impact_of_products','controv_society_human_rights','controv_society_human_rights_sc','controv_water_use',
'controv_water_use_sc','controv_weapons']]

Controv_before.head()
#Controv_before.to_excel('X:/INVDESPRO/INVESTIGACION/Fondos éticos/Misbel/Pruebas/Controv_before1.xlsx',index=False)

,issuer_name,permId,controv_access_to_basic_services,controv_accounting_and_taxation,controv_animal_welfare,controv_animal_welfare_sc,controv_anticompetitive_practices,controv_bribery_and_corruption,controv_bribery_and_corruption_sc,controv_business_ethics,...,controv_occupational_health_and_safety,controv_occupational_health_and_safety_sc,controv_quality_and_safety,controv_sanctions,controv_social_impact_of_products,controv_society_human_rights,controv_society_human_rights_sc,controv_water_use,controv_water_use_sc,controv_weapons
32,International Bank for Reconstruction and Deve...,8589934570,NaN,100.0,NaN,NaN,100.0,100.0,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,Cooperatieve Rabobank UA,4298009762,100.0,40.0,NaN,NaN,40.0,100.0,NaN,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092,General Motors Financial Company Inc,4295903360,NaN,100.0,NaN,NaN,100.0,100.0,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2114,Sumitomo Mitsui Banking Corp,5000001007,100.0,60.0,NaN,NaN,80.0,100.0,NaN,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2145,European Investment Bank,8589934159,100.0,100.0,NaN,NaN,60.0,100.0,NaN,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
Controv_after = DF_after_filtered.loc[:, ['issuer_name','permId','controv_access_to_basic_services','controv_accounting_and_taxation','controv_animal_welfare','controv_animal_welfare_sc','controv_anticompetitive_practices',
'controv_bribery_and_corruption','controv_bribery_and_corruption_sc','controv_business_ethics','controv_business_ethics_sc','controv_carbon_impact_of_products',
'controv_community_relations','controv_community_relations_sc','controv_corporate_governance','controv_data_privacy_and_security',
'controv_emissions_effluents_and_waste','controv_emissions_effluents_and_waste_sc','controv_employees_human_rights',
'controv_employees_human_rights_sc','controv_energy_use_and_ghg_emissions','controv_energy_use_and_ghg_emissions_sc',
'controv_environmental_impact_of_products','controv_intellectual_property','controv_labour_relations','controv_labour_relations_sc',
'controv_land_use_and_biodiversity','controv_land_use_and_biodiversity_sc','controv_lobbying_and_public_policy','controv_marketing_practices',
'controv_media_ethics','controv_occupational_health_and_safety','controv_occupational_health_and_safety_sc','controv_quality_and_safety',
'controv_sanctions','controv_social_impact_of_products','controv_society_human_rights','controv_society_human_rights_sc','controv_water_use',
'controv_water_use_sc','controv_weapons']]

Controv_after.head()
#Controv_after.to_excel('X:/INVDESPRO/INVESTIGACION/Fondos éticos/Misbel/Pruebas/Controv_after2.xlsx',index=False)

,issuer_name,permId,controv_access_to_basic_services,controv_accounting_and_taxation,controv_animal_welfare,controv_animal_welfare_sc,controv_anticompetitive_practices,controv_bribery_and_corruption,controv_bribery_and_corruption_sc,controv_business_ethics,...,controv_occupational_health_and_safety,controv_occupational_health_and_safety_sc,controv_quality_and_safety,controv_sanctions,controv_social_impact_of_products,controv_society_human_rights,controv_society_human_rights_sc,controv_water_use,controv_water_use_sc,controv_weapons
0,Banque Federative du Credit Mutuel SA,4296063555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Toronto-Dominion Bank,4295862902,100.0,40.0,NaN,NaN,80.0,100.0,NaN,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RCI Banque SA,4296537659,NaN,40.0,NaN,NaN,60.0,100.0,NaN,60.0,...,100.0,NaN,40.0,NaN,NaN,NaN,100.0,NaN,NaN,NaN
4,Intesa Sanpaolo SpA,4295875735,100.0,100.0,NaN,NaN,100.0,100.0,NaN,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Eni SpA,4295875633,60.0,80.0,NaN,NaN,80.0,40.0,NaN,80.0,...,100.0,NaN,NaN,NaN,NaN,60.0,NaN,100.0,NaN,NaN

In [116]:
Controv_before = Controv_before.drop_duplicates()
Controv_after = Controv_after.drop_duplicates()

In [117]:
# Combinar en función de permId
DF_merged_cont = pd.merge(Controv_before, Controv_after, on='permId', suffixes=('_before', '_after'))
DF_merged_cont.info()
DF_merged_cont.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 81 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   issuer_name_before                                686 non-null    object
 1   permId                                            686 non-null    int64
 2   controv_access_to_basic_services_before           392 non-null    object
 3   controv_accounting_and_taxation_before            674 non-null    object
 4   controv_animal_welfare_before                     38 non-null     object
 5   controv_animal_welfare_sc_before                  0 non-null      object
 6   controv_anticompetitive_practices_before          674 non-null    object
 7   controv_bribery_and_corruption_before             674 non-null    object
 8   controv_bribery_and_corruption_sc_before          0 non-null      object
 9   controv_business_ethics_before                    674 non-null    object
 10  controv_business_ethics_sc_before                 0 non-null      object
 11  controv_carbon_impact_of_products_before          0 non-null      object
 12  controv_community_relations_before                181 non-null    object
 13  controv_community_relations_sc_before             0 non-null      object
 14  controv_corporate_governance_before               674 non-null    object
 15  controv_data_privacy_and_security_before          469 non-null    object
 16  controv_emissions_effluents_and_waste_before      0 non-null      object
 17  controv_emissions_effluents_and_waste_sc_before   0 non-null      object
 18  controv_employees_human_rights_before             230 non-null    object
 19  controv_employees_human_rights_sc_before          145 non-null    object
 20  controv_energy_use_and_ghg_emissions_before       614 non-null    object
 21  controv_energy_use_and_ghg_emissions_sc_before    0 non-null      object
 22  controv_environmental_impact_of_products_before   0 non-null      object
 23  controv_intellectual_property_before              666 non-null    object
 24  controv_labour_relations_before                   674 non-null    object
 25  controv_labour_relations_sc_before                2 non-null      object
 26  controv_land_use_and_biodiversity_before          167 non-null    object
 27  controv_land_use_and_biodiversity_sc_before       0 non-null      object
 28  controv_lobbying_and_public_policy_before         654 non-null    object
 29  controv_marketing_practices_before                674 non-null    object
 30  controv_media_ethics_before                       0 non-null      object
 31  controv_occupational_health_and_safety_before     326 non-null    object
 32  controv_occupational_health_and_safety_sc_before  6 non-null      object
 33  controv_quality_and_safety_before                 375 non-null    object
 34  controv_sanctions_before                          0 non-null      object
 35  controv_social_impact_of_products_before          15 non-null     object
 36  controv_society_human_rights_before               125 non-null    object
 37  controv_society_human_rights_sc_before            143 non-null    object
 38  controv_water_use_before                          219 non-null    object
 39  controv_water_use_sc_before                       0 non-null      object
 40  controv_weapons_before                            0 non-null      object
 41  issuer_name_after                                 686 non-null    object
 42  controv_access_to_basic_services_after            392 non-null    object
 43  controv_accounting_and_taxation_after             674 non-null    object
 44  controv_animal_welfare_after                      38 non-null     object
 45  controv_animal_welfare_sc_after                   0 non-null      object
 46  controv_anticompetitive_practices_after           674 non-null    object
 47  controv_bribery_and_corruption_after              674 non-null    object
 48  controv_bribery_and_corruption_sc_after           0 non-null      object
 49  controv_business_ethics_after                     674 non-null    object
 50  controv_business_ethics_sc_after                  0 non-null      object
 51  controv_carbon_impact_of_products_after           0 non-null      object
 52  controv_community_relations_after                 181 non-null    object
 53  controv_community_relations_sc_after              0 non-null      object
 54  controv_corporate_governance_after                674 non-null    object
 55  controv_data_privacy_and_security_after           469 non-null    object
 56  controv_emissions_effluents_and_waste_after       0 non-null      object
 57  controv_emissions_effluents_and_waste_sc_after    0 non-null      object
 58  controv_employees_human_rights_after              230 non-null    object
 59  controv_employees_human_rights_sc_after           145 non-null    object
 60  controv_energy_use_and_ghg_emissions_after        614 non-null    object
 61  controv_energy_use_and_ghg_emissions_sc_after     0 non-null      object
 62  controv_environmental_impact_of_products_after    0 non-null      object
 63  controv_intellectual_property_after               666 non-null    object
 64  controv_labour_relations_after                    674 non-null    object
 65  controv_labour_relations_sc_after                 2 non-null      object
 66  controv_land_use_and_biodiversity_after           167 non-null    object
 67  controv_land_use_and_biodiversity_sc_after        0 non-null      object
 68  controv_lobbying_and_public_policy_after          654 non-null    object
 69  controv_marketing_practices_after                 674 non-null    object
 70  controv_media_ethics_after                        0 non-null      object
 71  controv_occupational_health_and_safety_after      326 non-null    object
 72  controv_occupational_health_and_safety_sc_after   6 non-null      object
 73  controv_quality_and_safety_after                  375 non-null    object
 74  controv_sanctions_after                           0 non-null      object
 75  controv_social_impact_of_products_after           15 non-null     object
 76  controv_society_human_rights_after                125 non-null    object
 77  controv_society_human_rights_sc_after             143 non-null    object
 78  controv_water_use_after                           219 non-null    object
 79  controv_water_use_sc_after                        0 non-null      object
 80  controv_weapons_after                             0 non-null      object
dtypes: int64(1), object(80)
memory usage: 439.5+ KB

,issuer_name_before,permId,controv_access_to_basic_services_before,controv_accounting_and_taxation_before,controv_animal_welfare_before,controv_animal_welfare_sc_before,controv_anticompetitive_practices_before,controv_bribery_and_corruption_before,controv_bribery_and_corruption_sc_before,controv_business_ethics_before,...,controv_occupational_health_and_safety_after,controv_occupational_health_and_safety_sc_after,controv_quality_and_safety_after,controv_sanctions_after,controv_social_impact_of_products_after,controv_society_human_rights_after,controv_society_human_rights_sc_after,controv_water_use_after,controv_water_use_sc_after,controv_weapons_after
0,International Bank for Reconstruction and Deve...,8589934570,NaN,100.0,NaN,NaN,100.0,100.0,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cooperatieve Rabobank UA,4298009762,100.0,40.0,NaN,NaN,40.0,100.0,NaN,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,General Motors Financial Company Inc,4295903360,NaN,100.0,NaN,NaN,100.0,100.0,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sumitomo Mitsui Banking Corp,5000001007,100.0,60.0,NaN,NaN,80.0,100.0,NaN,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,European Investment Bank,8589934159,100.0,100.0,NaN,NaN,60.0,100.0,NaN,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
DF_merged_cont.drop(['issuer_name_after'], axis = 'columns', inplace=True)
DF_merged_cont.rename(columns = {'issuer_name_before':'issuer_name'},inplace =True)
DF_merged_cont.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 80 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   issuer_name                                       686 non-null    object
 1   permId                                            686 non-null    int64
 2   controv_access_to_basic_services_before           392 non-null    object
 3   controv_accounting_and_taxation_before            674 non-null    object
 4   controv_animal_welfare_before                     38 non-null     object
 5   controv_animal_welfare_sc_before                  0 non-null      object
 6   controv_anticompetitive_practices_before          674 non-null    object
 7   controv_bribery_and_corruption_before             674 non-null    object
 8   controv_bribery_and_corruption_sc_before          0 non-null      object
 9   controv_business_ethics_before                    674 non-null    object
 10  controv_business_ethics_sc_before                 0 non-null      object
 11  controv_carbon_impact_of_products_before          0 non-null      object
 12  controv_community_relations_before                181 non-null    object
 13  controv_community_relations_sc_before             0 non-null      object
 14  controv_corporate_governance_before               674 non-null    object
 15  controv_data_privacy_and_security_before          469 non-null    object
 16  controv_emissions_effluents_and_waste_before      0 non-null      object
 17  controv_emissions_effluents_and_waste_sc_before   0 non-null      object
 18  controv_employees_human_rights_before             230 non-null    object
 19  controv_employees_human_rights_sc_before          145 non-null    object
 20  controv_energy_use_and_ghg_emissions_before       614 non-null    object
 21  controv_energy_use_and_ghg_emissions_sc_before    0 non-null      object
 22  controv_environmental_impact_of_products_before   0 non-null      object
 23  controv_intellectual_property_before              666 non-null    object
 24  controv_labour_relations_before                   674 non-null    object
 25  controv_labour_relations_sc_before                2 non-null      object
 26  controv_land_use_and_biodiversity_before          167 non-null    object
 27  controv_land_use_and_biodiversity_sc_before       0 non-null      object
 28  controv_lobbying_and_public_policy_before         654 non-null    object
 29  controv_marketing_practices_before                674 non-null    object
 30  controv_media_ethics_before                       0 non-null      object
 31  controv_occupational_health_and_safety_before     326 non-null    object
 32  controv_occupational_health_and_safety_sc_before  6 non-null      object
 33  controv_quality_and_safety_before                 375 non-null    object
 34  controv_sanctions_before                          0 non-null      object
 35  controv_social_impact_of_products_before          15 non-null     object
 36  controv_society_human_rights_before               125 non-null    object
 37  controv_society_human_rights_sc_before            143 non-null    object
 38  controv_water_use_before                          219 non-null    object
 39  controv_water_use_sc_before                       0 non-null      object
 40  controv_weapons_before                            0 non-null      object
 41  controv_access_to_basic_services_after            392 non-null    object
 42  controv_accounting_and_taxation_after             674 non-null    object
 43  controv_animal_welfare_after                      38 non-null     object
 44  controv_animal_welfare_sc_after                   0 non-null      object
 45  controv_anticompetitive_practices_after           674 non-null    object
 46  controv_bribery_and_corruption_after              674 non-null    object
 47  controv_bribery_and_corruption_sc_after           0 non-null      object
 48  controv_business_ethics_after                     674 non-null    object
 49  controv_business_ethics_sc_after                  0 non-null      object
 50  controv_carbon_impact_of_products_after           0 non-null      object
 51  controv_community_relations_after                 181 non-null    object
 52  controv_community_relations_sc_after              0 non-null      object
 53  controv_corporate_governance_after                674 non-null    object
 54  controv_data_privacy_and_security_after           469 non-null    object
 55  controv_emissions_effluents_and_waste_after       0 non-null      object
 56  controv_emissions_effluents_and_waste_sc_after    0 non-null      object
 57  controv_employees_human_rights_after              230 non-null    object
 58  controv_employees_human_rights_sc_after           145 non-null    object
 59  controv_energy_use_and_ghg_emissions_after        614 non-null    object
 60  controv_energy_use_and_ghg_emissions_sc_after     0 non-null      object
 61  controv_environmental_impact_of_products_after    0 non-null      object
 62  controv_intellectual_property_after               666 non-null    object
 63  controv_labour_relations_after                    674 non-null    object
 64  controv_labour_relations_sc_after                 2 non-null      object
 65  controv_land_use_and_biodiversity_after           167 non-null    object
 66  controv_land_use_and_biodiversity_sc_after        0 non-null      object
 67  controv_lobbying_and_public_policy_after          654 non-null    object
 68  controv_marketing_practices_after                 674 non-null    object
 69  controv_media_ethics_after                        0 non-null      object
 70  controv_occupational_health_and_safety_after      326 non-null    object
 71  controv_occupational_health_and_safety_sc_after   6 non-null      object
 72  controv_quality_and_safety_after                  375 non-null    object
 73  controv_sanctions_after                           0 non-null      object
 74  controv_social_impact_of_products_after           15 non-null     object
 75  controv_society_human_rights_after                125 non-null    object
 76  controv_society_human_rights_sc_after             143 non-null    object
 77  controv_water_use_after                           219 non-null    object
 78  controv_water_use_sc_after                        0 non-null      object
 79  controv_weapons_after                             0 non-null      object
dtypes: int64(1), object(79)
memory usage: 434.1+ KB

In [119]:
columns_to_fill = DF_merged_cont.columns.difference(['issuer_name', 'permId'])
DF_merged_cont[columns_to_fill] = DF_merged_cont[columns_to_fill].fillna('Faltante')

In [120]:
DF_merged_cont.info()
DF_merged_cont.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 80 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   issuer_name                                       686 non-null    object
 1   permId                                            686 non-null    int64
 2   controv_access_to_basic_services_before           686 non-null    object
 3   controv_accounting_and_taxation_before            686 non-null    object
 4   controv_animal_welfare_before                     686 non-null    object
 5   controv_animal_welfare_sc_before                  686 non-null    object
 6   controv_anticompetitive_practices_before          686 non-null    object
 7   controv_bribery_and_corruption_before             686 non-null    object
 8   controv_bribery_and_corruption_sc_before          686 non-null    object
 9   controv_business_ethics_before                    686 non-null    object
 10  controv_business_ethics_sc_before                 686 non-null    object
 11  controv_carbon_impact_of_products_before          686 non-null    object
 12  controv_community_relations_before                686 non-null    object
 13  controv_community_relations_sc_before             686 non-null    object
 14  controv_corporate_governance_before               686 non-null    object
 15  controv_data_privacy_and_security_before          686 non-null    object
 16  controv_emissions_effluents_and_waste_before      686 non-null    object
 17  controv_emissions_effluents_and_waste_sc_before   686 non-null    object
 18  controv_employees_human_rights_before             686 non-null    object
 19  controv_employees_human_rights_sc_before          686 non-null    object
 20  controv_energy_use_and_ghg_emissions_before       686 non-null    object
 21  controv_energy_use_and_ghg_emissions_sc_before    686 non-null    object
 22  controv_environmental_impact_of_products_before   686 non-null    object
 23  controv_intellectual_property_before              686 non-null    object
 24  controv_labour_relations_before                   686 non-null    object
 25  controv_labour_relations_sc_before                686 non-null    object
 26  controv_land_use_and_biodiversity_before          686 non-null    object
 27  controv_land_use_and_biodiversity_sc_before       686 non-null    object
 28  controv_lobbying_and_public_policy_before         686 non-null    object
 29  controv_marketing_practices_before                686 non-null    object
 30  controv_media_ethics_before                       686 non-null    object
 31  controv_occupational_health_and_safety_before     686 non-null    object
 32  controv_occupational_health_and_safety_sc_before  686 non-null    object
 33  controv_quality_and_safety_before                 686 non-null    object
 34  controv_sanctions_before                          686 non-null    object
 35  controv_social_impact_of_products_before          686 non-null    object
 36  controv_society_human_rights_before               686 non-null    object
 37  controv_society_human_rights_sc_before            686 non-null    object
 38  controv_water_use_before                          686 non-null    object
 39  controv_water_use_sc_before                       686 non-null    object
 40  controv_weapons_before                            686 non-null    object
 41  controv_access_to_basic_services_after            686 non-null    object
 42  controv_accounting_and_taxation_after             686 non-null    object
 43  controv_animal_welfare_after                      686 non-null    object
 44  controv_animal_welfare_sc_after                   686 non-null    object
 45  controv_anticompetitive_practices_after           686 non-null    object
 46  controv_bribery_and_corruption_after              686 non-null    object
 47  controv_bribery_and_corruption_sc_after           686 non-null    object
 48  controv_business_ethics_after                     686 non-null    object
 49  controv_business_ethics_sc_after                  686 non-null    object
 50  controv_carbon_impact_of_products_after           686 non-null    object
 51  controv_community_relations_after                 686 non-null    object
 52  controv_community_relations_sc_after              686 non-null    object
 53  controv_corporate_governance_after                686 non-null    object
 54  controv_data_privacy_and_security_after           686 non-null    object
 55  controv_emissions_effluents_and_waste_after       686 non-null    object
 56  controv_emissions_effluents_and_waste_sc_after    686 non-null    object
 57  controv_employees_human_rights_after              686 non-null    object
 58  controv_employees_human_rights_sc_after           686 non-null    object
 59  controv_energy_use_and_ghg_emissions_after        686 non-null    object
 60  controv_energy_use_and_ghg_emissions_sc_after     686 non-null    object
 61  controv_environmental_impact_of_products_after    686 non-null    object
 62  controv_intellectual_property_after               686 non-null    object
 63  controv_labour_relations_after                    686 non-null    object
 64  controv_labour_relations_sc_after                 686 non-null    object
 65  controv_land_use_and_biodiversity_after           686 non-null    object
 66  controv_land_use_and_biodiversity_sc_after        686 non-null    object
 67  controv_lobbying_and_public_policy_after          686 non-null    object
 68  controv_marketing_practices_after                 686 non-null    object
 69  controv_media_ethics_after                        686 non-null    object
 70  controv_occupational_health_and_safety_after      686 non-null    object
 71  controv_occupational_health_and_safety_sc_after   686 non-null    object
 72  controv_quality_and_safety_after                  686 non-null    object
 73  controv_sanctions_after                           686 non-null    object
 74  controv_social_impact_of_products_after           686 non-null    object
 75  controv_society_human_rights_after                686 non-null    object
 76  controv_society_human_rights_sc_after             686 non-null    object
 77  controv_water_use_after                           686 non-null    object
 78  controv_water_use_sc_after                        686 non-null    object
 79  controv_weapons_after                             686 non-null    object
dtypes: int64(1), object(79)
memory usage: 434.1+ KB

,issuer_name,permId,controv_access_to_basic_services_before,controv_accounting_and_taxation_before,controv_animal_welfare_before,controv_animal_welfare_sc_before,controv_anticompetitive_practices_before,controv_bribery_and_corruption_before,controv_bribery_and_corruption_sc_before,controv_business_ethics_before,...,controv_occupational_health_and_safety_after,controv_occupational_health_and_safety_sc_after,controv_quality_and_safety_after,controv_sanctions_after,controv_social_impact_of_products_after,controv_society_human_rights_after,controv_society_human_rights_sc_after,controv_water_use_after,controv_water_use_sc_after,controv_weapons_after
0,International Bank for Reconstruction and Deve...,8589934570,Faltante,100.0,Faltante,Faltante,100.0,100.0,Faltante,60.0,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante
1,Cooperatieve Rabobank UA,4298009762,100.0,40.0,Faltante,Faltante,40.0,100.0,Faltante,100.0,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante
2,General Motors Financial Company Inc,4295903360,Faltante,100.0,Faltante,Faltante,100.0,100.0,Faltante,60.0,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante
3,Sumitomo Mitsui Banking Corp,5000001007,100.0,60.0,Faltante,Faltante,80.0,100.0,Faltante,100.0,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante
4,European Investment Bank,8589934159,100.0,100.0,Faltante,Faltante,60.0,100.0,Faltante,80.0,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante

In [121]:
DF_merged_cont['permId'].value_counts()

8589934570    1
5042243092    1
5000023943    1
5045949737    1
4295904341    1
             ..
4295885708    1
4296669053    1
4295904557    1
8589934254    1
5051611662    1
Name: permId, Length: 686, dtype: int64

In [122]:
DF_controv_v = DF_merged_cont.copy()
DF_controv_v.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 80 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   issuer_name                                       686 non-null    object
 1   permId                                            686 non-null    int64
 2   controv_access_to_basic_services_before           686 non-null    object
 3   controv_accounting_and_taxation_before            686 non-null    object
 4   controv_animal_welfare_before                     686 non-null    object
 5   controv_animal_welfare_sc_before                  686 non-null    object
 6   controv_anticompetitive_practices_before          686 non-null    object
 7   controv_bribery_and_corruption_before             686 non-null    object
 8   controv_bribery_and_corruption_sc_before          686 non-null    object
 9   controv_business_ethics_before                    686 non-null    object
 10  controv_business_ethics_sc_before                 686 non-null    object
 11  controv_carbon_impact_of_products_before          686 non-null    object
 12  controv_community_relations_before                686 non-null    object
 13  controv_community_relations_sc_before             686 non-null    object
 14  controv_corporate_governance_before               686 non-null    object
 15  controv_data_privacy_and_security_before          686 non-null    object
 16  controv_emissions_effluents_and_waste_before      686 non-null    object
 17  controv_emissions_effluents_and_waste_sc_before   686 non-null    object
 18  controv_employees_human_rights_before             686 non-null    object
 19  controv_employees_human_rights_sc_before          686 non-null    object
 20  controv_energy_use_and_ghg_emissions_before       686 non-null    object
 21  controv_energy_use_and_ghg_emissions_sc_before    686 non-null    object
 22  controv_environmental_impact_of_products_before   686 non-null    object
 23  controv_intellectual_property_before              686 non-null    object
 24  controv_labour_relations_before                   686 non-null    object
 25  controv_labour_relations_sc_before                686 non-null    object
 26  controv_land_use_and_biodiversity_before          686 non-null    object
 27  controv_land_use_and_biodiversity_sc_before       686 non-null    object
 28  controv_lobbying_and_public_policy_before         686 non-null    object
 29  controv_marketing_practices_before                686 non-null    object
 30  controv_media_ethics_before                       686 non-null    object
 31  controv_occupational_health_and_safety_before     686 non-null    object
 32  controv_occupational_health_and_safety_sc_before  686 non-null    object
 33  controv_quality_and_safety_before                 686 non-null    object
 34  controv_sanctions_before                          686 non-null    object
 35  controv_social_impact_of_products_before          686 non-null    object
 36  controv_society_human_rights_before               686 non-null    object
 37  controv_society_human_rights_sc_before            686 non-null    object
 38  controv_water_use_before                          686 non-null    object
 39  controv_water_use_sc_before                       686 non-null    object
 40  controv_weapons_before                            686 non-null    object
 41  controv_access_to_basic_services_after            686 non-null    object
 42  controv_accounting_and_taxation_after             686 non-null    object
 43  controv_animal_welfare_after                      686 non-null    object
 44  controv_animal_welfare_sc_after                   686 non-null    object
 45  controv_anticompetitive_practices_after           686 non-null    object
 46  controv_bribery_and_corruption_after              686 non-null    object
 47  controv_bribery_and_corruption_sc_after           686 non-null    object
 48  controv_business_ethics_after                     686 non-null    object
 49  controv_business_ethics_sc_after                  686 non-null    object
 50  controv_carbon_impact_of_products_after           686 non-null    object
 51  controv_community_relations_after                 686 non-null    object
 52  controv_community_relations_sc_after              686 non-null    object
 53  controv_corporate_governance_after                686 non-null    object
 54  controv_data_privacy_and_security_after           686 non-null    object
 55  controv_emissions_effluents_and_waste_after       686 non-null    object
 56  controv_emissions_effluents_and_waste_sc_after    686 non-null    object
 57  controv_employees_human_rights_after              686 non-null    object
 58  controv_employees_human_rights_sc_after           686 non-null    object
 59  controv_energy_use_and_ghg_emissions_after        686 non-null    object
 60  controv_energy_use_and_ghg_emissions_sc_after     686 non-null    object
 61  controv_environmental_impact_of_products_after    686 non-null    object
 62  controv_intellectual_property_after               686 non-null    object
 63  controv_labour_relations_after                    686 non-null    object
 64  controv_labour_relations_sc_after                 686 non-null    object
 65  controv_land_use_and_biodiversity_after           686 non-null    object
 66  controv_land_use_and_biodiversity_sc_after        686 non-null    object
 67  controv_lobbying_and_public_policy_after          686 non-null    object
 68  controv_marketing_practices_after                 686 non-null    object
 69  controv_media_ethics_after                        686 non-null    object
 70  controv_occupational_health_and_safety_after      686 non-null    object
 71  controv_occupational_health_and_safety_sc_after   686 non-null    object
 72  controv_quality_and_safety_after                  686 non-null    object
 73  controv_sanctions_after                           686 non-null    object
 74  controv_social_impact_of_products_after           686 non-null    object
 75  controv_society_human_rights_after                686 non-null    object
 76  controv_society_human_rights_sc_after             686 non-null    object
 77  controv_water_use_after                           686 non-null    object
 78  controv_water_use_sc_after                        686 non-null    object
 79  controv_weapons_after                             686 non-null    object
dtypes: int64(1), object(79)
memory usage: 434.1+ KB

In [123]:
#Ordenar
col_groups = {}
for col in DF_controv_v.columns:
    col_name, _, suffix = col.rpartition('_')
    col_groups.setdefault(col_name, []).append((suffix, col))

sorted_cols = []
for col_name in sorted(col_groups.keys()):
    sorted_cols.extend(col for _, col in sorted(col_groups[col_name]))
    
df_sorted_c = DF_controv_v[sorted_cols]
df_sorted_c = df_sorted_c.reindex(sorted(df_sorted_c.columns), axis=1)

In [124]:
df_sorted_c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 80 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   controv_access_to_basic_services_after            686 non-null    object
 1   controv_access_to_basic_services_before           686 non-null    object
 2   controv_accounting_and_taxation_after             686 non-null    object
 3   controv_accounting_and_taxation_before            686 non-null    object
 4   controv_animal_welfare_after                      686 non-null    object
 5   controv_animal_welfare_before                     686 non-null    object
 6   controv_animal_welfare_sc_after                   686 non-null    object
 7   controv_animal_welfare_sc_before                  686 non-null    object
 8   controv_anticompetitive_practices_after           686 non-null    object
 9   controv_anticompetitive_practices_before          686 non-null    object
 10  controv_bribery_and_corruption_after              686 non-null    object
 11  controv_bribery_and_corruption_before             686 non-null    object
 12  controv_bribery_and_corruption_sc_after           686 non-null    object
 13  controv_bribery_and_corruption_sc_before          686 non-null    object
 14  controv_business_ethics_after                     686 non-null    object
 15  controv_business_ethics_before                    686 non-null    object
 16  controv_business_ethics_sc_after                  686 non-null    object
 17  controv_business_ethics_sc_before                 686 non-null    object
 18  controv_carbon_impact_of_products_after           686 non-null    object
 19  controv_carbon_impact_of_products_before          686 non-null    object
 20  controv_community_relations_after                 686 non-null    object
 21  controv_community_relations_before                686 non-null    object
 22  controv_community_relations_sc_after              686 non-null    object
 23  controv_community_relations_sc_before             686 non-null    object
 24  controv_corporate_governance_after                686 non-null    object
 25  controv_corporate_governance_before               686 non-null    object
 26  controv_data_privacy_and_security_after           686 non-null    object
 27  controv_data_privacy_and_security_before          686 non-null    object
 28  controv_emissions_effluents_and_waste_after       686 non-null    object
 29  controv_emissions_effluents_and_waste_before      686 non-null    object
 30  controv_emissions_effluents_and_waste_sc_after    686 non-null    object
 31  controv_emissions_effluents_and_waste_sc_before   686 non-null    object
 32  controv_employees_human_rights_after              686 non-null    object
 33  controv_employees_human_rights_before             686 non-null    object
 34  controv_employees_human_rights_sc_after           686 non-null    object
 35  controv_employees_human_rights_sc_before          686 non-null    object
 36  controv_energy_use_and_ghg_emissions_after        686 non-null    object
 37  controv_energy_use_and_ghg_emissions_before       686 non-null    object
 38  controv_energy_use_and_ghg_emissions_sc_after     686 non-null    object
 39  controv_energy_use_and_ghg_emissions_sc_before    686 non-null    object
 40  controv_environmental_impact_of_products_after    686 non-null    object
 41  controv_environmental_impact_of_products_before   686 non-null    object
 42  controv_intellectual_property_after               686 non-null    object
 43  controv_intellectual_property_before              686 non-null    object
 44  controv_labour_relations_after                    686 non-null    object
 45  controv_labour_relations_before                   686 non-null    object
 46  controv_labour_relations_sc_after                 686 non-null    object
 47  controv_labour_relations_sc_before                686 non-null    object
 48  controv_land_use_and_biodiversity_after           686 non-null    object
 49  controv_land_use_and_biodiversity_before          686 non-null    object
 50  controv_land_use_and_biodiversity_sc_after        686 non-null    object
 51  controv_land_use_and_biodiversity_sc_before       686 non-null    object
 52  controv_lobbying_and_public_policy_after          686 non-null    object
 53  controv_lobbying_and_public_policy_before         686 non-null    object
 54  controv_marketing_practices_after                 686 non-null    object
 55  controv_marketing_practices_before                686 non-null    object
 56  controv_media_ethics_after                        686 non-null    object
 57  controv_media_ethics_before                       686 non-null    object
 58  controv_occupational_health_and_safety_after      686 non-null    object
 59  controv_occupational_health_and_safety_before     686 non-null    object
 60  controv_occupational_health_and_safety_sc_after   686 non-null    object
 61  controv_occupational_health_and_safety_sc_before  686 non-null    object
 62  controv_quality_and_safety_after                  686 non-null    object
 63  controv_quality_and_safety_before                 686 non-null    object
 64  controv_sanctions_after                           686 non-null    object
 65  controv_sanctions_before                          686 non-null    object
 66  controv_social_impact_of_products_after           686 non-null    object
 67  controv_social_impact_of_products_before          686 non-null    object
 68  controv_society_human_rights_after                686 non-null    object
 69  controv_society_human_rights_before               686 non-null    object
 70  controv_society_human_rights_sc_after             686 non-null    object
 71  controv_society_human_rights_sc_before            686 non-null    object
 72  controv_water_use_after                           686 non-null    object
 73  controv_water_use_before                          686 non-null    object
 74  controv_water_use_sc_after                        686 non-null    object
 75  controv_water_use_sc_before                       686 non-null    object
 76  controv_weapons_after                             686 non-null    object
 77  controv_weapons_before                            686 non-null    object
 78  issuer_name                                       686 non-null    object
 79  permId                                            686 non-null    int64
dtypes: int64(1), object(79)
memory usage: 434.1+ KB

In [125]:
# Filtro 
cols = df_sorted_c.filter(regex='_before$').columns

def generate_variation_col(col):
    col_name = col.rpartition("_")[0]
    before_col = col.replace("_before","_after")
    verification_col = "Variation_" + col_name
    bool_series = df_sorted_c[col].ne(df_sorted_c[before_col])
    return verification_col, bool_series

# Comprobación
for col in cols:
    verification_col, bool_series = generate_variation_col(col)
    df_sorted_c.insert(df_sorted_c.columns.get_loc(col), verification_col, bool_series)

In [126]:
df_sorted_c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Columns: 119 entries, controv_access_to_basic_services_after to permId
dtypes: bool(39), int64(1), object(79)
memory usage: 460.2+ KB

In [127]:
df_sorted_c.head()

,controv_access_to_basic_services_after,Variation_controv_access_to_basic_services,controv_access_to_basic_services_before,controv_accounting_and_taxation_after,Variation_controv_accounting_and_taxation,controv_accounting_and_taxation_before,controv_animal_welfare_after,Variation_controv_animal_welfare,controv_animal_welfare_before,controv_animal_welfare_sc_after,...,Variation_controv_water_use,controv_water_use_before,controv_water_use_sc_after,Variation_controv_water_use_sc,controv_water_use_sc_before,controv_weapons_after,Variation_controv_weapons,controv_weapons_before,issuer_name,permId
0,Faltante,False,Faltante,100.0,False,100.0,Faltante,False,Faltante,Faltante,...,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,International Bank for Reconstruction and Deve...,8589934570
1,100.0,False,100.0,40.0,False,40.0,Faltante,False,Faltante,Faltante,...,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,Cooperatieve Rabobank UA,4298009762
2,Faltante,False,Faltante,100.0,False,100.0,Faltante,False,Faltante,Faltante,...,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,General Motors Financial Company Inc,4295903360
3,100.0,False,100.0,60.0,False,60.0,Faltante,False,Faltante,Faltante,...,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,Sumitomo Mitsui Banking Corp,5000001007
4,100.0,False,100.0,100.0,False,100.0,Faltante,False,Faltante,Faltante,...,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,European Investment Bank,8589934159

In [128]:
pd.Series(df_sorted_c.Variation_controv_access_to_basic_services).value_counts()

False    686
Name: Variation_controv_access_to_basic_services, dtype: int64

In [129]:
Variation_Controv =df_sorted_c.copy()

In [130]:
#Creación de las columnas de comprobación
Variation_cols_contr = [col for col in Variation_Controv.columns if col.startswith("Variation_")]

# Crear columna de variación
Variation_Controv["Controv_Variation"] = Variation_Controv[Variation_cols_contr].any(axis=1)

In [131]:
# Crear una lista con el orden deseado de las columnas
column_order = ['permId','issuer_name', 'Controv_Variation'] + [col for col in Variation_Controv.columns if col not in ['permId','issuer_name', 'Controv_Variation']]

# Reordenar las columnas del dataframe según la lista creada
Variation_Controv = Variation_Controv.reindex(columns=column_order)

In [132]:
Variation_Controv.head()

,permId,issuer_name,Controv_Variation,controv_access_to_basic_services_after,Variation_controv_access_to_basic_services,controv_access_to_basic_services_before,controv_accounting_and_taxation_after,Variation_controv_accounting_and_taxation,controv_accounting_and_taxation_before,controv_animal_welfare_after,...,controv_society_human_rights_sc_before,controv_water_use_after,Variation_controv_water_use,controv_water_use_before,controv_water_use_sc_after,Variation_controv_water_use_sc,controv_water_use_sc_before,controv_weapons_after,Variation_controv_weapons,controv_weapons_before
0,8589934570,International Bank for Reconstruction and Deve...,False,Faltante,False,Faltante,100.0,False,100.0,Faltante,...,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante
1,4298009762,Cooperatieve Rabobank UA,False,100.0,False,100.0,40.0,False,40.0,Faltante,...,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante
2,4295903360,General Motors Financial Company Inc,False,Faltante,False,Faltante,100.0,False,100.0,Faltante,...,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante
3,5000001007,Sumitomo Mitsui Banking Corp,False,100.0,False,100.0,60.0,False,60.0,Faltante,...,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante
4,8589934159,European Investment Bank,False,100.0,False,100.0,100.0,False,100.0,Faltante,...,Faltante,Faltante,False,Faltante,Faltante,False,Faltante,Faltante,False,Faltante

In [133]:
#ordenar vista 
column_order = ['permId','issuer_name', 'Controv_Variation']
variation_columns = [col for col in Variation_Controv.columns if col.startswith('Variation_')]
other_columns =sorted(set(Variation_Controv.columns)- set(column_order) - set(variation_columns))
n_df_Cont = Variation_Controv[column_order + variation_columns + other_columns]

In [134]:
nombres_columnas_n_df_Cont= n_df_Cont.columns.tolist()
nombres_columnas_n_df_Cont

['permId',
 'issuer_name',
 'Controv_Variation',
 'Variation_controv_access_to_basic_services',
 'Variation_controv_accounting_and_taxation',
 'Variation_controv_animal_welfare',
 'Variation_controv_animal_welfare_sc',
 'Variation_controv_anticompetitive_practices',
 'Variation_controv_bribery_and_corruption',
 'Variation_controv_bribery_and_corruption_sc',
 'Variation_controv_business_ethics',
 'Variation_controv_business_ethics_sc',
 'Variation_controv_carbon_impact_of_products',
 'Variation_controv_community_relations',
 'Variation_controv_community_relations_sc',
 'Variation_controv_corporate_governance',
 'Variation_controv_data_privacy_and_security',
 'Variation_controv_emissions_effluents_and_waste',
 'Variation_controv_emissions_effluents_and_waste_sc',
 'Variation_controv_employees_human_rights',
 'Variation_controv_employees_human_rights_sc',
 'Variation_controv_energy_use_and_ghg_emissions',
 'Variation_controv_energy_use_and_ghg_emissions_sc',
 'Variation_controv_environmental_impact_of_products',
 'Variation_controv_intellectual_property',
 'Variation_controv_labour_relations',
 'Variation_controv_labour_relations_sc',
 'Variation_controv_land_use_and_biodiversity',
 'Variation_controv_land_use_and_biodiversity_sc',
 'Variation_controv_lobbying_and_public_policy',
 'Variation_controv_marketing_practices',
 'Variation_controv_media_ethics',
 'Variation_controv_occupational_health_and_safety',
 'Variation_controv_occupational_health_and_safety_sc',
 'Variation_controv_quality_and_safety',
 'Variation_controv_sanctions',
 'Variation_controv_social_impact_of_products',
 'Variation_controv_society_human_rights',
 'Variation_controv_society_human_rights_sc',
 'Variation_controv_water_use',
 'Variation_controv_water_use_sc',
 'Variation_controv_weapons',
 'controv_access_to_basic_services_after',
 'controv_access_to_basic_services_before',
 'controv_accounting_and_taxation_after',
 'controv_accounting_and_taxation_before',
 'controv_animal_welfare_after',
 'controv_animal_welfare_before',
 'controv_animal_welfare_sc_after',
 'controv_animal_welfare_sc_before',
 'controv_anticompetitive_practices_after',
 'controv_anticompetitive_practices_before',
 'controv_bribery_and_corruption_after',
 'controv_bribery_and_corruption_before',
 'controv_bribery_and_corruption_sc_after',
 'controv_bribery_and_corruption_sc_before',
 'controv_business_ethics_after',
 'controv_business_ethics_before',
 'controv_business_ethics_sc_after',
 'controv_business_ethics_sc_before',
 'controv_carbon_impact_of_products_after',
 'controv_carbon_impact_of_products_before',
 'controv_community_relations_after',
 'controv_community_relations_before',
 'controv_community_relations_sc_after',
 'controv_community_relations_sc_before',
 'controv_corporate_governance_after',
 'controv_corporate_governance_before',
 'controv_data_privacy_and_security_after',
 'controv_data_privacy_and_security_before',
 'controv_emissions_effluents_and_waste_after',
 'controv_emissions_effluents_and_waste_before',
 'controv_emissions_effluents_and_waste_sc_after',
 'controv_emissions_effluents_and_waste_sc_before',
 'controv_employees_human_rights_after',
 'controv_employees_human_rights_before',
 'controv_employees_human_rights_sc_after',
 'controv_employees_human_rights_sc_before',
 'controv_energy_use_and_ghg_emissions_after',
 'controv_energy_use_and_ghg_emissions_before',
 'controv_energy_use_and_ghg_emissions_sc_after',
 'controv_energy_use_and_ghg_emissions_sc_before',
 'controv_environmental_impact_of_products_after',
 'controv_environmental_impact_of_products_before',
 'controv_intellectual_property_after',
 'controv_intellectual_property_before',
 'controv_labour_relations_after',
 'controv_labour_relations_before',
 'controv_labour_relations_sc_after',
 'controv_labour_relations_sc_before',
 'controv_land_use_and_biodiversity_after',
 'controv_land_use_and_biodiversity_before',
 'controv_land_use_and_biodiversity_sc_after',
 'controv_land_use_and_biodiversity_sc_before',
 'controv_lobbying_and_public_policy_after',
 'controv_lobbying_and_public_policy_before',
 'controv_marketing_practices_after',
 'controv_marketing_practices_before',
 'controv_media_ethics_after',
 'controv_media_ethics_before',
 'controv_occupational_health_and_safety_after',
 'controv_occupational_health_and_safety_before',
 'controv_occupational_health_and_safety_sc_after',
 'controv_occupational_health_and_safety_sc_before',
 'controv_quality_and_safety_after',
 'controv_quality_and_safety_before',
 'controv_sanctions_after',
 'controv_sanctions_before',
 'controv_social_impact_of_products_after',
 'controv_social_impact_of_products_before',
 'controv_society_human_rights_after',
 'controv_society_human_rights_before',
 'controv_society_human_rights_sc_after',
 'controv_society_human_rights_sc_before',
 'controv_water_use_after',
 'controv_water_use_before',
 'controv_water_use_sc_after',
 'controv_water_use_sc_before',
 'controv_weapons_after',
 'controv_weapons_before']

In [135]:
n_df_Cont=n_df_Cont[['permId',
 'issuer_name',
 'Controv_Variation',
 'Variation_controv_access_to_basic_services',
 'Variation_controv_accounting_and_taxation',
 'Variation_controv_animal_welfare',
 'Variation_controv_animal_welfare_sc',
 'Variation_controv_anticompetitive_practices',
 'Variation_controv_bribery_and_corruption',
 'Variation_controv_bribery_and_corruption_sc',
 'Variation_controv_business_ethics',
 'Variation_controv_business_ethics_sc',
 'Variation_controv_carbon_impact_of_products',
 'Variation_controv_community_relations',
 'Variation_controv_community_relations_sc',
 'Variation_controv_corporate_governance',
 'Variation_controv_data_privacy_and_security',
 'Variation_controv_emissions_effluents_and_waste',
 'Variation_controv_emissions_effluents_and_waste_sc',
 'Variation_controv_employees_human_rights',
 'Variation_controv_employees_human_rights_sc',
 'Variation_controv_energy_use_and_ghg_emissions',
 'Variation_controv_energy_use_and_ghg_emissions_sc',
 'Variation_controv_environmental_impact_of_products',
 'Variation_controv_intellectual_property',
 'Variation_controv_labour_relations',
 'Variation_controv_labour_relations_sc',
 'Variation_controv_land_use_and_biodiversity',
 'Variation_controv_land_use_and_biodiversity_sc',
 'Variation_controv_lobbying_and_public_policy',
 'Variation_controv_marketing_practices',
 'Variation_controv_media_ethics',
 'Variation_controv_occupational_health_and_safety',
 'Variation_controv_occupational_health_and_safety_sc',
 'Variation_controv_quality_and_safety',
 'Variation_controv_sanctions',
 'Variation_controv_social_impact_of_products',
 'Variation_controv_society_human_rights',
 'Variation_controv_society_human_rights_sc',
 'Variation_controv_water_use',
 'Variation_controv_water_use_sc',
 'Variation_controv_weapons',
 'controv_access_to_basic_services_before',                                                     
 'controv_access_to_basic_services_after',
 'controv_accounting_and_taxation_before',
 'controv_accounting_and_taxation_after',
 'controv_animal_welfare_before',
 'controv_animal_welfare_after',
 'controv_animal_welfare_sc_before',
 'controv_animal_welfare_sc_after',
 'controv_anticompetitive_practices_before',
 'controv_anticompetitive_practices_after',
 'controv_bribery_and_corruption_before',
 'controv_bribery_and_corruption_after',
 'controv_bribery_and_corruption_sc_before',
 'controv_bribery_and_corruption_sc_after',
 'controv_business_ethics_before',
 'controv_business_ethics_after',
 'controv_business_ethics_sc_before',
 'controv_business_ethics_sc_after',
 'controv_carbon_impact_of_products_before',
 'controv_carbon_impact_of_products_after',
 'controv_community_relations_before',
 'controv_community_relations_after',
 'controv_community_relations_sc_before',
 'controv_community_relations_sc_after',
 'controv_corporate_governance_before',
 'controv_corporate_governance_after',
 'controv_data_privacy_and_security_before',
 'controv_data_privacy_and_security_after',
 'controv_emissions_effluents_and_waste_before',
 'controv_emissions_effluents_and_waste_after',
 'controv_emissions_effluents_and_waste_sc_before',
 'controv_emissions_effluents_and_waste_sc_after',
 'controv_employees_human_rights_before',
 'controv_employees_human_rights_after',
 'controv_employees_human_rights_sc_before',
 'controv_employees_human_rights_sc_after',
 'controv_energy_use_and_ghg_emissions_before',
 'controv_energy_use_and_ghg_emissions_after',
 'controv_energy_use_and_ghg_emissions_sc_before',
 'controv_energy_use_and_ghg_emissions_sc_after',
 'controv_environmental_impact_of_products_before',
 'controv_environmental_impact_of_products_after',
 'controv_intellectual_property_before',
 'controv_intellectual_property_after',
 'controv_labour_relations_before',
 'controv_labour_relations_after',
 'controv_labour_relations_sc_before',
 'controv_labour_relations_sc_after',
 'controv_land_use_and_biodiversity_before',
 'controv_land_use_and_biodiversity_after',
 'controv_land_use_and_biodiversity_sc_before',
 'controv_land_use_and_biodiversity_sc_after',
 'controv_lobbying_and_public_policy_before',
 'controv_lobbying_and_public_policy_after',
 'controv_marketing_practices_before',
 'controv_marketing_practices_after',
 'controv_media_ethics_before',
 'controv_media_ethics_after',
 'controv_occupational_health_and_safety_before',
 'controv_occupational_health_and_safety_after',
 'controv_occupational_health_and_safety_sc_before',
 'controv_occupational_health_and_safety_sc_after',
 'controv_quality_and_safety_before',
 'controv_quality_and_safety_after',
 'controv_sanctions_before',
 'controv_sanctions_after',
 'controv_social_impact_of_products_before',
 'controv_social_impact_of_products_after',
 'controv_society_human_rights_before',
 'controv_society_human_rights_after',
 'controv_society_human_rights_sc_before',
 'controv_society_human_rights_sc_after',
 'controv_water_use_before',
 'controv_water_use_after',
 'controv_water_use_sc_before',
 'controv_water_use_sc_after',
 'controv_weapons_before',
 'controv_weapons_after']]

In [136]:
n_df_Cont.head()

,permId,issuer_name,Controv_Variation,Variation_controv_access_to_basic_services,Variation_controv_accounting_and_taxation,Variation_controv_animal_welfare,Variation_controv_animal_welfare_sc,Variation_controv_anticompetitive_practices,Variation_controv_bribery_and_corruption,Variation_controv_bribery_and_corruption_sc,...,controv_society_human_rights_before,controv_society_human_rights_after,controv_society_human_rights_sc_before,controv_society_human_rights_sc_after,controv_water_use_before,controv_water_use_after,controv_water_use_sc_before,controv_water_use_sc_after,controv_weapons_before,controv_weapons_after
0,8589934570,International Bank for Reconstruction and Deve...,False,False,False,False,False,False,False,False,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante
1,4298009762,Cooperatieve Rabobank UA,False,False,False,False,False,False,False,False,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante
2,4295903360,General Motors Financial Company Inc,False,False,False,False,False,False,False,False,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante
3,5000001007,Sumitomo Mitsui Banking Corp,False,False,False,False,False,False,False,False,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante
4,8589934159,European Investment Bank,False,False,False,False,False,False,False,False,...,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante,Faltante

In [137]:
n_df_Cont.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Columns: 120 entries, permId to controv_weapons_after
dtypes: bool(40), int64(1), object(79)
memory usage: 460.9+ KB

In [138]:
pd.Series(n_df_Cont.Controv_Variation).value_counts()

False    686
Name: Controv_Variation, dtype: int64

In [139]:
Cont_True=n_df_Cont
in_True_Cont= Cont_True['Controv_Variation']==True
Cont_True= Cont_True[in_True_Cont]
Cont_True.head()

Empty DataFrame
Columns: [permId, issuer_name, Controv_Variation, Variation_controv_access_to_basic_services, Variation_controv_accounting_and_taxation, Variation_controv_animal_welfare, Variation_controv_animal_welfare_sc, Variation_controv_anticompetitive_practices, Variation_controv_bribery_and_corruption, Variation_controv_bribery_and_corruption_sc, Variation_controv_business_ethics, Variation_controv_business_ethics_sc, Variation_controv_carbon_impact_of_products, Variation_controv_community_relations, Variation_controv_community_relations_sc, Variation_controv_corporate_governance, Variation_controv_data_privacy_and_security, Variation_controv_emissions_effluents_and_waste, Variation_controv_emissions_effluents_and_waste_sc, Variation_controv_employees_human_rights, Variation_controv_employees_human_rights_sc, Variation_controv_energy_use_and_ghg_emissions, Variation_controv_energy_use_and_ghg_emissions_sc, Variation_controv_environmental_impact_of_products, Variation_controv_intellectual_property, Variation_controv_labour_relations, Variation_controv_labour_relations_sc, Variation_controv_land_use_and_biodiversity, Variation_controv_land_use_and_biodiversity_sc, Variation_controv_lobbying_and_public_policy, Variation_controv_marketing_practices, Variation_controv_media_ethics, Variation_controv_occupational_health_and_safety, Variation_controv_occupational_health_and_safety_sc, Variation_controv_quality_and_safety, Variation_controv_sanctions, Variation_controv_social_impact_of_products, Variation_controv_society_human_rights, Variation_controv_society_human_rights_sc, Variation_controv_water_use, Variation_controv_water_use_sc, Variation_controv_weapons, controv_access_to_basic_services_before, controv_access_to_basic_services_after, controv_accounting_and_taxation_before, controv_accounting_and_taxation_after, controv_animal_welfare_before, controv_animal_welfare_after, controv_animal_welfare_sc_before, controv_animal_welfare_sc_after, controv_anticompetitive_practices_before, controv_anticompetitive_practices_after, controv_bribery_and_corruption_before, controv_bribery_and_corruption_after, controv_bribery_and_corruption_sc_before, controv_bribery_and_corruption_sc_after, controv_business_ethics_before, controv_business_ethics_after, controv_business_ethics_sc_before, controv_business_ethics_sc_after, controv_carbon_impact_of_products_before, controv_carbon_impact_of_products_after, controv_community_relations_before, controv_community_relations_after, controv_community_relations_sc_before, controv_community_relations_sc_after, controv_corporate_governance_before, controv_corporate_governance_after, controv_data_privacy_and_security_before, controv_data_privacy_and_security_after, controv_emissions_effluents_and_waste_before, controv_emissions_effluents_and_waste_after, controv_emissions_effluents_and_waste_sc_before, controv_emissions_effluents_and_waste_sc_after, controv_employees_human_rights_before, controv_employees_human_rights_after, controv_employees_human_rights_sc_before, controv_employees_human_rights_sc_after, controv_energy_use_and_ghg_emissions_before, controv_energy_use_and_ghg_emissions_after, controv_energy_use_and_ghg_emissions_sc_before, controv_energy_use_and_ghg_emissions_sc_after, controv_environmental_impact_of_products_before, controv_environmental_impact_of_products_after, controv_intellectual_property_before, controv_intellectual_property_after, controv_labour_relations_before, controv_labour_relations_after, controv_labour_relations_sc_before, controv_labour_relations_sc_after, controv_land_use_and_biodiversity_before, controv_land_use_and_biodiversity_after, controv_land_use_and_biodiversity_sc_before, controv_land_use_and_biodiversity_sc_after, controv_lobbying_and_public_policy_before, controv_lobbying_and_public_policy_after, controv_marketing_practices_before, controv_marketing_practices_after, controv_media_ethics_before, controv_media_ethics_after, ...]
Index: []

[0 rows x 120 columns]

In [140]:
pd.Series(Cont_True.Controv_Variation).value_counts()

Series([], Name: Controv_Variation, dtype: int64)

In [141]:
#COLUMNA FINAL DE VERIFICACION
Controversias= Variation_Controv[[ 'permId','issuer_name','Controv_Variation']]
Controversias.head()

,permId,issuer_name,Controv_Variation
0,8589934570,International Bank for Reconstruction and Deve...,False
1,4298009762,Cooperatieve Rabobank UA,False
2,4295903360,General Motors Financial Company Inc,False
3,5000001007,Sumitomo Mitsui Banking Corp,False
4,8589934159,European Investment Bank,False

In [142]:
pd.Series(Controversias.Controv_Variation).value_counts()

False    686
Name: Controv_Variation, dtype: int64

## ESTRATEGIAS

#### Nota: Si cambian o se agregan before o after, agregar al código

In [143]:
Estrategias_before = DF_before_filtered.loc[:, ['issuer_name','permId','str_001_s','str_002_ec','str_003_ec','str_004_asec','str_005_ec','cs_001_sec','cs_003_sec','cs_002_ec','str_006_sec','str_007_sect','art_8_basicos','str_003b_ec']]
Estrategias_before.shape

(686, 14)

In [144]:
Estrategias_after = DF_after_filtered.loc[:, ['issuer_name','permId','str_001_s','str_002_ec','str_003_ec','str_004_asec','str_005_ec','cs_001_sec','cs_003_sec','cs_002_ec','str_006_sec','str_007_sect','art_8_basicos','str_003b_ec']]
Estrategias_after.shape

(686, 14)

In [145]:
Estrategias_before = Estrategias_before.drop_duplicates()
Estrategias_after = Estrategias_after.drop_duplicates()

In [146]:
# Combinar en función de permId
DF_merged_estrategias = pd.merge(Estrategias_before, Estrategias_after, on='permId', suffixes=('_before', '_after'))
DF_merged_estrategias.info()
DF_merged_estrategias.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   issuer_name_before    686 non-null    object
 1   permId                686 non-null    int64
 2   str_001_s_before      686 non-null    object
 3   str_002_ec_before     686 non-null    object
 4   str_003_ec_before     686 non-null    object
 5   str_004_asec_before   686 non-null    object
 6   str_005_ec_before     686 non-null    object
 7   cs_001_sec_before     686 non-null    object
 8   cs_003_sec_before     686 non-null    object
 9   cs_002_ec_before      686 non-null    object
 10  str_006_sec_before    686 non-null    object
 11  str_007_sect_before   686 non-null    object
 12  art_8_basicos_before  686 non-null    object
 13  str_003b_ec_before    686 non-null    object
 14  issuer_name_after     686 non-null    object
 15  str_001_s_after       686 non-null    object
 16  str_002_ec_after      686 non-null    object
 17  str_003_ec_after      686 non-null    object
 18  str_004_asec_after    686 non-null    object
 19  str_005_ec_after      686 non-null    object
 20  cs_001_sec_after      686 non-null    object
 21  cs_003_sec_after      686 non-null    object
 22  cs_002_ec_after       686 non-null    object
 23  str_006_sec_after     686 non-null    object
 24  str_007_sect_after    686 non-null    object
 25  art_8_basicos_after   686 non-null    object
 26  str_003b_ec_after     686 non-null    object
dtypes: int64(1), object(26)
memory usage: 150.1+ KB

,issuer_name_before,permId,str_001_s_before,str_002_ec_before,str_003_ec_before,str_004_asec_before,str_005_ec_before,cs_001_sec_before,cs_003_sec_before,cs_002_ec_before,...,str_003_ec_after,str_004_asec_after,str_005_ec_after,cs_001_sec_after,cs_003_sec_after,cs_002_ec_after,str_006_sec_after,str_007_sect_after,art_8_basicos_after,str_003b_ec_after
0,International Bank for Reconstruction and Deve...,8589934570,OK,OK,OK,OK,OK,OK,OK,OK,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK
1,Cooperatieve Rabobank UA,4298009762,OK,OK,OK,EXCLUDED,OK,EXCLUDED,EXCLUDED,OK,...,OK,EXCLUDED,OK,EXCLUDED,EXCLUDED,OK,OK,EXCLUDED,OK,OK
2,General Motors Financial Company Inc,4295903360,EXCLUDED,OK,OK,EXCLUDED,OK,EXCLUDED,EXCLUDED,OK,...,OK,EXCLUDED,OK,EXCLUDED,EXCLUDED,OK,EXCLUDED,EXCLUDED,OK,OK
3,Sumitomo Mitsui Banking Corp,5000001007,OK,OK,OK,OK,OK,OK,EXCLUDED,OK,...,OK,OK,OK,OK,EXCLUDED,OK,OK,OK,OK,OK
4,European Investment Bank,8589934159,OK,OK,OK,OK,OK,OK,OK,OK,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK

In [147]:
DF_merged_estrategias.drop(['issuer_name_after'], axis = 'columns', inplace=True)
DF_merged_estrategias.rename(columns = {'issuer_name_before':'issuer_name'},inplace =True)
DF_merged_estrategias.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   issuer_name           686 non-null    object
 1   permId                686 non-null    int64
 2   str_001_s_before      686 non-null    object
 3   str_002_ec_before     686 non-null    object
 4   str_003_ec_before     686 non-null    object
 5   str_004_asec_before   686 non-null    object
 6   str_005_ec_before     686 non-null    object
 7   cs_001_sec_before     686 non-null    object
 8   cs_003_sec_before     686 non-null    object
 9   cs_002_ec_before      686 non-null    object
 10  str_006_sec_before    686 non-null    object
 11  str_007_sect_before   686 non-null    object
 12  art_8_basicos_before  686 non-null    object
 13  str_003b_ec_before    686 non-null    object
 14  str_001_s_after       686 non-null    object
 15  str_002_ec_after      686 non-null    object
 16  str_003_ec_after      686 non-null    object
 17  str_004_asec_after    686 non-null    object
 18  str_005_ec_after      686 non-null    object
 19  cs_001_sec_after      686 non-null    object
 20  cs_003_sec_after      686 non-null    object
 21  cs_002_ec_after       686 non-null    object
 22  str_006_sec_after     686 non-null    object
 23  str_007_sect_after    686 non-null    object
 24  art_8_basicos_after   686 non-null    object
 25  str_003b_ec_after     686 non-null    object
dtypes: int64(1), object(25)
memory usage: 144.7+ KB

In [148]:
columns_to_fill = DF_merged_estrategias.columns.difference(['permId','issuer_name'])
DF_merged_estrategias[columns_to_fill] = DF_merged_estrategias[columns_to_fill].fillna('Faltante')

In [149]:
df_estrategias_variacion= DF_merged_estrategias.copy()

In [150]:
#Ordenar
col_groups = {}
for col in df_estrategias_variacion.columns:
    col_name, _, suffix = col.rpartition('_')
    col_groups.setdefault(col_name, []).append((suffix, col))

sorted_cols = []
for col_name in sorted(col_groups.keys()):
    sorted_cols.extend(col for _, col in sorted(col_groups[col_name]))
    
df_sorted_e = df_estrategias_variacion[sorted_cols]
df_sorted_e = df_estrategias_variacion.reindex(sorted(df_estrategias_variacion.columns), axis=1)

In [151]:
df_sorted_e.head()

,art_8_basicos_after,art_8_basicos_before,cs_001_sec_after,cs_001_sec_before,cs_002_ec_after,cs_002_ec_before,cs_003_sec_after,cs_003_sec_before,issuer_name,permId,...,str_003b_ec_after,str_003b_ec_before,str_004_asec_after,str_004_asec_before,str_005_ec_after,str_005_ec_before,str_006_sec_after,str_006_sec_before,str_007_sect_after,str_007_sect_before
0,OK,OK,OK,OK,OK,OK,OK,OK,International Bank for Reconstruction and Deve...,8589934570,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK
1,OK,OK,EXCLUDED,EXCLUDED,OK,OK,EXCLUDED,EXCLUDED,Cooperatieve Rabobank UA,4298009762,...,OK,OK,EXCLUDED,EXCLUDED,OK,OK,OK,OK,EXCLUDED,EXCLUDED
2,OK,OK,EXCLUDED,EXCLUDED,OK,OK,EXCLUDED,EXCLUDED,General Motors Financial Company Inc,4295903360,...,OK,OK,EXCLUDED,EXCLUDED,OK,OK,EXCLUDED,EXCLUDED,EXCLUDED,EXCLUDED
3,OK,OK,OK,OK,OK,OK,EXCLUDED,EXCLUDED,Sumitomo Mitsui Banking Corp,5000001007,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK
4,OK,OK,OK,OK,OK,OK,OK,OK,European Investment Bank,8589934159,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK

In [152]:
# Filter 
cols = df_sorted_e.filter(regex='_after$').columns

# Define a function to generate the "Variation_" column for each "after" column
def generate_variation_col(col):
    col_name = col.rpartition("_")[0]
    before_col = col.replace("_after", "_before")
    verification_col = "Variation_" + col_name
    bool_series = df_sorted_e[col].ne(df_sorted_e[before_col])
    return verification_col, bool_series

# Comprobación
for col in cols:
    verification_col, bool_series = generate_variation_col(col)
    df_sorted_e.insert(df_sorted_e.columns.get_loc(col), verification_col, bool_series)

In [153]:
df_sorted_e.head()

,Variation_art_8_basicos,art_8_basicos_after,art_8_basicos_before,Variation_cs_001_sec,cs_001_sec_after,cs_001_sec_before,Variation_cs_002_ec,cs_002_ec_after,cs_002_ec_before,Variation_cs_003_sec,...,str_004_asec_before,Variation_str_005_ec,str_005_ec_after,str_005_ec_before,Variation_str_006_sec,str_006_sec_after,str_006_sec_before,Variation_str_007_sect,str_007_sect_after,str_007_sect_before
0,False,OK,OK,False,OK,OK,False,OK,OK,False,...,OK,False,OK,OK,False,OK,OK,False,OK,OK
1,False,OK,OK,False,EXCLUDED,EXCLUDED,False,OK,OK,False,...,EXCLUDED,False,OK,OK,False,OK,OK,False,EXCLUDED,EXCLUDED
2,False,OK,OK,False,EXCLUDED,EXCLUDED,False,OK,OK,False,...,EXCLUDED,False,OK,OK,False,EXCLUDED,EXCLUDED,False,EXCLUDED,EXCLUDED
3,False,OK,OK,False,OK,OK,False,OK,OK,False,...,OK,False,OK,OK,False,OK,OK,False,OK,OK
4,False,OK,OK,False,OK,OK,False,OK,OK,False,...,OK,False,OK,OK,False,OK,OK,False,OK,OK

In [154]:
df_sorted_e.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 38 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Variation_art_8_basicos  686 non-null    bool
 1   art_8_basicos_after      686 non-null    object
 2   art_8_basicos_before     686 non-null    object
 3   Variation_cs_001_sec     686 non-null    bool
 4   cs_001_sec_after         686 non-null    object
 5   cs_001_sec_before        686 non-null    object
 6   Variation_cs_002_ec      686 non-null    bool
 7   cs_002_ec_after          686 non-null    object
 8   cs_002_ec_before         686 non-null    object
 9   Variation_cs_003_sec     686 non-null    bool
 10  cs_003_sec_after         686 non-null    object
 11  cs_003_sec_before        686 non-null    object
 12  issuer_name              686 non-null    object
 13  permId                   686 non-null    int64
 14  Variation_str_001_s      686 non-null    bool
 15  str_001_s_after          686 non-null    object
 16  str_001_s_before         686 non-null    object
 17  Variation_str_002_ec     686 non-null    bool
 18  str_002_ec_after         686 non-null    object
 19  str_002_ec_before        686 non-null    object
 20  Variation_str_003_ec     686 non-null    bool
 21  str_003_ec_after         686 non-null    object
 22  str_003_ec_before        686 non-null    object
 23  Variation_str_003b_ec    686 non-null    bool
 24  str_003b_ec_after        686 non-null    object
 25  str_003b_ec_before       686 non-null    object
 26  Variation_str_004_asec   686 non-null    bool
 27  str_004_asec_after       686 non-null    object
 28  str_004_asec_before      686 non-null    object
 29  Variation_str_005_ec     686 non-null    bool
 30  str_005_ec_after         686 non-null    object
 31  str_005_ec_before        686 non-null    object
 32  Variation_str_006_sec    686 non-null    bool
 33  str_006_sec_after        686 non-null    object
 34  str_006_sec_before       686 non-null    object
 35  Variation_str_007_sect   686 non-null    bool
 36  str_007_sect_after       686 non-null    object
 37  str_007_sect_before      686 non-null    object
dtypes: bool(12), int64(1), object(25)
memory usage: 152.7+ KB

In [155]:
Variation_estrat = df_sorted_e.copy()

In [156]:
Variation_cols_estrat = [col for col in Variation_estrat.columns if col.startswith("Variation_")]

# Crear columna de variación
Variation_estrat["Variation_Estrategias"] = Variation_estrat[Variation_cols_estrat].any(axis=1)

In [157]:
# Crear una lista con el orden deseado de las columnas
column_order = ['permId','issuer_name', 'Variation_Estrategias'] + [col for col in Variation_estrat.columns if col not in ['permId','issuer_name', 'Variation_Estrategias']]

# Reordenar las columnas del dataframe según la lista creada
Variation_estrat = Variation_estrat.reindex(columns=column_order)

In [158]:
Variation_estrat.info()
Variation_estrat.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 39 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   permId                   686 non-null    int64
 1   issuer_name              686 non-null    object
 2   Variation_Estrategias    686 non-null    bool
 3   Variation_art_8_basicos  686 non-null    bool
 4   art_8_basicos_after      686 non-null    object
 5   art_8_basicos_before     686 non-null    object
 6   Variation_cs_001_sec     686 non-null    bool
 7   cs_001_sec_after         686 non-null    object
 8   cs_001_sec_before        686 non-null    object
 9   Variation_cs_002_ec      686 non-null    bool
 10  cs_002_ec_after          686 non-null    object
 11  cs_002_ec_before         686 non-null    object
 12  Variation_cs_003_sec     686 non-null    bool
 13  cs_003_sec_after         686 non-null    object
 14  cs_003_sec_before        686 non-null    object
 15  Variation_str_001_s      686 non-null    bool
 16  str_001_s_after          686 non-null    object
 17  str_001_s_before         686 non-null    object
 18  Variation_str_002_ec     686 non-null    bool
 19  str_002_ec_after         686 non-null    object
 20  str_002_ec_before        686 non-null    object
 21  Variation_str_003_ec     686 non-null    bool
 22  str_003_ec_after         686 non-null    object
 23  str_003_ec_before        686 non-null    object
 24  Variation_str_003b_ec    686 non-null    bool
 25  str_003b_ec_after        686 non-null    object
 26  str_003b_ec_before       686 non-null    object
 27  Variation_str_004_asec   686 non-null    bool
 28  str_004_asec_after       686 non-null    object
 29  str_004_asec_before      686 non-null    object
 30  Variation_str_005_ec     686 non-null    bool
 31  str_005_ec_after         686 non-null    object
 32  str_005_ec_before        686 non-null    object
 33  Variation_str_006_sec    686 non-null    bool
 34  str_006_sec_after        686 non-null    object
 35  str_006_sec_before       686 non-null    object
 36  Variation_str_007_sect   686 non-null    bool
 37  str_007_sect_after       686 non-null    object
 38  str_007_sect_before      686 non-null    object
dtypes: bool(13), int64(1), object(25)
memory usage: 153.4+ KB

,permId,issuer_name,Variation_Estrategias,Variation_art_8_basicos,art_8_basicos_after,art_8_basicos_before,Variation_cs_001_sec,cs_001_sec_after,cs_001_sec_before,Variation_cs_002_ec,...,str_004_asec_before,Variation_str_005_ec,str_005_ec_after,str_005_ec_before,Variation_str_006_sec,str_006_sec_after,str_006_sec_before,Variation_str_007_sect,str_007_sect_after,str_007_sect_before
0,8589934570,International Bank for Reconstruction and Deve...,False,False,OK,OK,False,OK,OK,False,...,OK,False,OK,OK,False,OK,OK,False,OK,OK
1,4298009762,Cooperatieve Rabobank UA,False,False,OK,OK,False,EXCLUDED,EXCLUDED,False,...,EXCLUDED,False,OK,OK,False,OK,OK,False,EXCLUDED,EXCLUDED
2,4295903360,General Motors Financial Company Inc,False,False,OK,OK,False,EXCLUDED,EXCLUDED,False,...,EXCLUDED,False,OK,OK,False,EXCLUDED,EXCLUDED,False,EXCLUDED,EXCLUDED
3,5000001007,Sumitomo Mitsui Banking Corp,False,False,OK,OK,False,OK,OK,False,...,OK,False,OK,OK,False,OK,OK,False,OK,OK
4,8589934159,European Investment Bank,False,False,OK,OK,False,OK,OK,False,...,OK,False,OK,OK,False,OK,OK,False,OK,OK

In [159]:
column_order_es = ['permId','issuer_name']
variation_columns_es = [col for col in Variation_estrat.columns if col.startswith('Variation_')]
other_columns_es =sorted(set(Variation_estrat.columns)- set(column_order_es) - set(variation_columns_es))
n_df_es = Variation_estrat[column_order_es + variation_columns_es + other_columns_es]
n_df_es.head()

,permId,issuer_name,Variation_Estrategias,Variation_art_8_basicos,Variation_cs_001_sec,Variation_cs_002_ec,Variation_cs_003_sec,Variation_str_001_s,Variation_str_002_ec,Variation_str_003_ec,...,str_003b_ec_after,str_003b_ec_before,str_004_asec_after,str_004_asec_before,str_005_ec_after,str_005_ec_before,str_006_sec_after,str_006_sec_before,str_007_sect_after,str_007_sect_before
0,8589934570,International Bank for Reconstruction and Deve...,False,False,False,False,False,False,False,False,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK
1,4298009762,Cooperatieve Rabobank UA,False,False,False,False,False,False,False,False,...,OK,OK,EXCLUDED,EXCLUDED,OK,OK,OK,OK,EXCLUDED,EXCLUDED
2,4295903360,General Motors Financial Company Inc,False,False,False,False,False,False,False,False,...,OK,OK,EXCLUDED,EXCLUDED,OK,OK,EXCLUDED,EXCLUDED,EXCLUDED,EXCLUDED
3,5000001007,Sumitomo Mitsui Banking Corp,False,False,False,False,False,False,False,False,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK
4,8589934159,European Investment Bank,False,False,False,False,False,False,False,False,...,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK

In [160]:
nombres_columnas_n_df_es= n_df_es.columns.tolist()
nombres_columnas_n_df_es

['permId',
 'issuer_name',
 'Variation_Estrategias',
 'Variation_art_8_basicos',
 'Variation_cs_001_sec',
 'Variation_cs_002_ec',
 'Variation_cs_003_sec',
 'Variation_str_001_s',
 'Variation_str_002_ec',
 'Variation_str_003_ec',
 'Variation_str_003b_ec',
 'Variation_str_004_asec',
 'Variation_str_005_ec',
 'Variation_str_006_sec',
 'Variation_str_007_sect',
 'art_8_basicos_after',
 'art_8_basicos_before',
 'cs_001_sec_after',
 'cs_001_sec_before',
 'cs_002_ec_after',
 'cs_002_ec_before',
 'cs_003_sec_after',
 'cs_003_sec_before',
 'str_001_s_after',
 'str_001_s_before',
 'str_002_ec_after',
 'str_002_ec_before',
 'str_003_ec_after',
 'str_003_ec_before',
 'str_003b_ec_after',
 'str_003b_ec_before',
 'str_004_asec_after',
 'str_004_asec_before',
 'str_005_ec_after',
 'str_005_ec_before',
 'str_006_sec_after',
 'str_006_sec_before',
 'str_007_sect_after',
 'str_007_sect_before']

In [161]:
n_df_es = n_df_es [['permId',
 'issuer_name',
 'Variation_Estrategias',
 'Variation_art_8_basicos',
 'Variation_cs_001_sec',
 'Variation_cs_002_ec',
 'Variation_cs_003_sec',
 'Variation_str_001_s',
 'Variation_str_002_ec',
 'Variation_str_003_ec',
 'Variation_str_004_asec',
 'Variation_str_005_ec',
 'Variation_str_006_sec',
 'Variation_str_007_sect',
 'art_8_basicos_before',                  
 'art_8_basicos_after',
 'cs_001_sec_before',                   
 'cs_001_sec_after',
 'cs_002_ec_before',
 'cs_002_ec_after',
 'cs_003_sec_before',
 'cs_003_sec_after',
 'str_001_s_before',
 'str_001_s_after',
 'str_002_ec_before',
 'str_002_ec_after',
 'str_003_ec_before',
 'str_003_ec_after',
 'str_004_asec_before',
 'str_004_asec_after',
 'str_005_ec_before',
 'str_005_ec_after',
 'str_006_sec_before',
 'str_006_sec_after',
 'str_007_sect_before',
 'str_007_sect_after',
'str_003b_ec_before',
'str_003b_ec_after']]

In [162]:
n_df_es.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 38 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   permId                   686 non-null    int64
 1   issuer_name              686 non-null    object
 2   Variation_Estrategias    686 non-null    bool
 3   Variation_art_8_basicos  686 non-null    bool
 4   Variation_cs_001_sec     686 non-null    bool
 5   Variation_cs_002_ec      686 non-null    bool
 6   Variation_cs_003_sec     686 non-null    bool
 7   Variation_str_001_s      686 non-null    bool
 8   Variation_str_002_ec     686 non-null    bool
 9   Variation_str_003_ec     686 non-null    bool
 10  Variation_str_004_asec   686 non-null    bool
 11  Variation_str_005_ec     686 non-null    bool
 12  Variation_str_006_sec    686 non-null    bool
 13  Variation_str_007_sect   686 non-null    bool
 14  art_8_basicos_before     686 non-null    object
 15  art_8_basicos_after      686 non-null    object
 16  cs_001_sec_before        686 non-null    object
 17  cs_001_sec_after         686 non-null    object
 18  cs_002_ec_before         686 non-null    object
 19  cs_002_ec_after          686 non-null    object
 20  cs_003_sec_before        686 non-null    object
 21  cs_003_sec_after         686 non-null    object
 22  str_001_s_before         686 non-null    object
 23  str_001_s_after          686 non-null    object
 24  str_002_ec_before        686 non-null    object
 25  str_002_ec_after         686 non-null    object
 26  str_003_ec_before        686 non-null    object
 27  str_003_ec_after         686 non-null    object
 28  str_004_asec_before      686 non-null    object
 29  str_004_asec_after       686 non-null    object
 30  str_005_ec_before        686 non-null    object
 31  str_005_ec_after         686 non-null    object
 32  str_006_sec_before       686 non-null    object
 33  str_006_sec_after        686 non-null    object
 34  str_007_sect_before      686 non-null    object
 35  str_007_sect_after       686 non-null    object
 36  str_003b_ec_before       686 non-null    object
 37  str_003b_ec_after        686 non-null    object
dtypes: bool(12), int64(1), object(25)
memory usage: 152.7+ KB

In [163]:
pd.Series(Variation_estrat.Variation_Estrategias).value_counts()

False    684
True       2
Name: Variation_Estrategias, dtype: int64

In [164]:
Est_True=n_df_es
in_True_Est= Est_True['Variation_Estrategias']==True
Est_True= Est_True[in_True_Est]
Est_True.head()

,permId,issuer_name,Variation_Estrategias,Variation_art_8_basicos,Variation_cs_001_sec,Variation_cs_002_ec,Variation_cs_003_sec,Variation_str_001_s,Variation_str_002_ec,Variation_str_003_ec,...,str_004_asec_before,str_004_asec_after,str_005_ec_before,str_005_ec_after,str_006_sec_before,str_006_sec_after,str_007_sect_before,str_007_sect_after,str_003b_ec_before,str_003b_ec_after
178,4295866751,Carrefour SA,True,False,False,False,False,False,False,False,...,EXCLUDED,OK,OK,OK,OK,OK,EXCLUDED,OK,OK,OK
506,4295903861,D R Horton Inc,True,False,False,False,False,False,False,False,...,OK,EXCLUDED,OK,OK,OK,OK,OK,EXCLUDED,OK,OK

In [165]:
pd.Series(Est_True.Variation_Estrategias).value_counts()

True    2
Name: Variation_Estrategias, dtype: int64

In [166]:
#COLUMNA FINAL DE VERIFICACION
Estrategias= Variation_estrat[['permId','issuer_name','Variation_Estrategias']]
Estrategias.head()
Estrategias.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permId                 686 non-null    int64
 1   issuer_name            686 non-null    object
 2   Variation_Estrategias  686 non-null    bool
dtypes: bool(1), int64(1), object(1)
memory usage: 16.7+ KB

## Sustainability Rating + Exposición + Controversia + Estrategias

In [167]:
V_sustainability_rating.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permId                 686 non-null    int64
 1   issuer_name            686 non-null    object
 2   Variation_Sust_rating  686 non-null    bool
dtypes: bool(1), int64(1), object(1)
memory usage: 16.7+ KB

In [168]:
pd.Series(V_sustainability_rating.Variation_Sust_rating).value_counts()

False    686
Name: Variation_Sust_rating, dtype: int64

In [169]:
V_Max_Expo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   permId              686 non-null    int64
 1   issuer_name         686 non-null    object
 2   Max_Expo_Variation  686 non-null    bool
dtypes: bool(1), int64(1), object(1)
memory usage: 16.7+ KB

In [170]:
pd.Series(V_Max_Expo.Max_Expo_Variation).value_counts()

False    679
True       7
Name: Max_Expo_Variation, dtype: int64

In [171]:
Controversias.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   permId             686 non-null    int64
 1   issuer_name        686 non-null    object
 2   Controv_Variation  686 non-null    bool
dtypes: bool(1), int64(1), object(1)
memory usage: 16.7+ KB

In [172]:
pd.Series(Controversias.Controv_Variation).value_counts()

False    686
Name: Controv_Variation, dtype: int64

In [173]:
Estrategias.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permId                 686 non-null    int64
 1   issuer_name            686 non-null    object
 2   Variation_Estrategias  686 non-null    bool
dtypes: bool(1), int64(1), object(1)
memory usage: 16.7+ KB

In [174]:
pd.Series(Estrategias.Variation_Estrategias).value_counts()

False    684
True       2
Name: Variation_Estrategias, dtype: int64

In [175]:
V_sustainability_rating = V_sustainability_rating[['permId','Variation_Sust_rating']]
Controversias = Controversias[['permId','Controv_Variation']]
Estrategias = Estrategias[['permId','Variation_Estrategias']]

In [176]:
data = pd.merge(V_Max_Expo, V_sustainability_rating , on='permId', how='outer')
data = pd.merge(data, Controversias, on='permId', how='outer')
data = pd.merge(data, Estrategias, on='permId', how='outer')

In [177]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permId                 686 non-null    int64
 1   issuer_name            686 non-null    object
 2   Max_Expo_Variation     686 non-null    bool
 3   Variation_Sust_rating  686 non-null    bool
 4   Controv_Variation      686 non-null    bool
 5   Variation_Estrategias  686 non-null    bool
dtypes: bool(4), int64(1), object(1)
memory usage: 18.8+ KB

In [178]:
data.rename(columns = {'Max_Expo_Variation':'Variation_Max_expo', 'Max_Expo_Variation':'Variation_Max_Exp', 'Controv_Variation':'Variation_Controv'},inplace =True)

In [179]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permId                 686 non-null    int64
 1   issuer_name            686 non-null    object
 2   Variation_Max_Exp      686 non-null    bool
 3   Variation_Sust_rating  686 non-null    bool
 4   Variation_Controv      686 non-null    bool
 5   Variation_Estrategias  686 non-null    bool
dtypes: bool(4), int64(1), object(1)
memory usage: 18.8+ KB

In [180]:
data=data[['permId','issuer_name','Variation_Sust_rating','Variation_Max_Exp','Variation_Controv','Variation_Estrategias']]

In [181]:
data.info() 
data.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permId                 686 non-null    int64
 1   issuer_name            686 non-null    object
 2   Variation_Sust_rating  686 non-null    bool
 3   Variation_Max_Exp      686 non-null    bool
 4   Variation_Controv      686 non-null    bool
 5   Variation_Estrategias  686 non-null    bool
dtypes: bool(4), int64(1), object(1)
memory usage: 18.8+ KB

,permId,issuer_name,Variation_Sust_rating,Variation_Max_Exp,Variation_Controv,Variation_Estrategias
0,8589934570,International Bank for Reconstruction and Deve...,False,False,False,False
1,4298009762,Cooperatieve Rabobank UA,False,False,False,False
2,4295903360,General Motors Financial Company Inc,False,False,False,False
3,5000001007,Sumitomo Mitsui Banking Corp,False,False,False,False
4,8589934159,European Investment Bank,False,False,False,False

In [182]:
Variation_DF= [col for col in data.columns if col.startswith("Variation_")]

# Crear columna de variación
data["Variation_DF"] = data[Variation_DF].any(axis=1)

In [183]:
data.info() 
data.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 686 entries, 0 to 685
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permId                 686 non-null    int64
 1   issuer_name            686 non-null    object
 2   Variation_Sust_rating  686 non-null    bool
 3   Variation_Max_Exp      686 non-null    bool
 4   Variation_Controv      686 non-null    bool
 5   Variation_Estrategias  686 non-null    bool
 6   Variation_DF           686 non-null    bool
dtypes: bool(5), int64(1), object(1)
memory usage: 19.4+ KB

,permId,issuer_name,Variation_Sust_rating,Variation_Max_Exp,Variation_Controv,Variation_Estrategias,Variation_DF
0,8589934570,International Bank for Reconstruction and Deve...,False,False,False,False,False
1,4298009762,Cooperatieve Rabobank UA,False,False,False,False,False
2,4295903360,General Motors Financial Company Inc,False,False,False,False,False
3,5000001007,Sumitomo Mitsui Banking Corp,False,False,False,False,False
4,8589934159,European Investment Bank,False,False,False,False,False

In [184]:
pd.Series(data.Variation_DF).value_counts()

False    679
True       7
Name: Variation_DF, dtype: int64

## FICHERO FINAL

## Cambiar antes de ejecutar, ruta y nombre: por lo general ya se ha cambiado nombre 
   - data = Fichero final resumen 
   
   - `data`.to_excel(r'X:/INVDESPRO/INVESTIGACION/Fondos éticos/Misbel/Pruebas/**`Resumen_Variaciones_'`**,index=False)

In [185]:
hoja_1=data
hoja_2=SR_True
hoja_3= Exp_True
hoja_4= Cont_True
hoja_5= Est_True

# CAMBIAR RUTA Y NOMBRE (antes de ejecutar)

In [186]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from openpyxl.utils import range_boundaries

In [187]:
ruta='X:/INVDESPRO/INVESTIGACION/Fondos éticos/3. DATASETS/04_Datos Clarity/01_Equities_feed/03_Overwrites/Análisis_Cambios_OVR/Resumen_Variaciones_sepoct2023.xlsx'

In [188]:
with pd.ExcelWriter(ruta) as writer:
    hoja_1.to_excel(writer, sheet_name='Resumen', index=False)
    hoja_2.to_excel(writer, sheet_name='Sust_R', index=False)
    hoja_3.to_excel(writer, sheet_name='Max_Exp', index=False)
    hoja_4.to_excel(writer, sheet_name='Controversias', index=False)
    hoja_5.to_excel(writer, sheet_name='Estrategias', index=False)